configured_endpoints: 25
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/context-dev/context.dev-021b48afe1d6e3f54c4ebe3d0da4beb3fb8b69a6d384a4aeadbc5bab7f967603.yml
openapi_spec_hash: 2aa5b59d78c708b094acf29cc0d9a68a
config_hash: c7b0cdaba3b9797b77efd89e1754d803
