module ContextDev
  module Resources
    class AI
      def extract_product: (
        url: String,
        ?max_age_ms: Integer,
        ?tags: ::Array[String],
        ?timeout_opts: ContextDev::AIExtractProductParams::TimeoutOpts,
        ?request_options: ContextDev::request_opts
      ) -> ContextDev::Models::AIExtractProductResponse

      def extract_products: (
        body: ContextDev::Models::AIExtractProductsParams::body,
        ?request_options: ContextDev::request_opts
      ) -> ContextDev::Models::AIExtractProductsResponse

      def initialize: (client: ContextDev::Client) -> void
    end
  end
end
