module ContextDev
  module Resources
    class Brand
      def retrieve: (
        body: ContextDev::Models::BrandRetrieveParams::body,
        ?request_options: ContextDev::request_opts
      ) -> ContextDev::Models::BrandRetrieveResponse

      def retrieve_simplified: (
        domain: String,
        ?max_age_ms: Integer,
        ?timeout_ms: Integer,
        ?request_options: ContextDev::request_opts
      ) -> ContextDev::Models::BrandRetrieveSimplifiedResponse

      def initialize: (client: ContextDev::Client) -> void
    end
  end
end
