module ContextDev
  module Resources
    class Brand
      def retrieve: (
        body: ContextDev::Models::BrandRetrieveParams::body,
        ?request_options: ContextDev::request_opts
      ) -> ContextDev::Models::BrandRetrieveResponse

      def retrieve_simplified: (
        domain: String,
        ?max_age_ms: Integer?,
        ?tags: ::Array[String],
        ?theme: ContextDev::Models::BrandRetrieveSimplifiedParams::theme,
        ?timeout_opts: ContextDev::BrandRetrieveSimplifiedParams::TimeoutOpts,
        ?request_options: ContextDev::request_opts
      ) -> ContextDev::Models::BrandRetrieveSimplifiedResponse

      def search: (
        query: String,
        ?autocomplete: bool,
        ?query_by: ::Array[ContextDev::Models::BrandSearchParams::query_by],
        ?tags: ::Array[String],
        ?typo_tolerance: Integer,
        ?request_options: ContextDev::request_opts
      ) -> ContextDev::Models::BrandSearchResponse

      def initialize: (client: ContextDev::Client) -> void
    end
  end
end
