module ContextDev
  module Resources
    class Industry
      def retrieve_naics: (
        input: String,
        ?max_results: Integer,
        ?min_results: Integer,
        ?tags: ::Array[String],
        ?timeout_opts: ContextDev::IndustryRetrieveNaicsParams::TimeoutOpts,
        ?request_options: ContextDev::request_opts
      ) -> ContextDev::Models::IndustryRetrieveNaicsResponse

      def retrieve_sic: (
        input: String,
        ?max_results: Integer,
        ?min_results: Integer,
        ?tags: ::Array[String],
        ?timeout_opts: ContextDev::IndustryRetrieveSicParams::TimeoutOpts,
        ?type: ContextDev::Models::IndustryRetrieveSicParams::type_,
        ?request_options: ContextDev::request_opts
      ) -> ContextDev::Models::IndustryRetrieveSicResponse

      def initialize: (client: ContextDev::Client) -> void
    end
  end
end
