module ContextDev
  module Resources
    class Monitors
      def create: (
        name: String,
        target: ContextDev::Models::MonitorCreateParams::target,
        ?change_detection: ContextDev::Models::MonitorCreateParams::change_detection,
        ?mode: ContextDev::Models::MonitorCreateParams::mode,
        ?schedule: ContextDev::MonitorCreateParams::Schedule,
        ?tags: ::Array[String],
        ?webhook: ContextDev::MonitorCreateParams::Webhook?,
        ?request_options: ContextDev::request_opts
      ) -> ContextDev::Models::MonitorCreateResponse

      def retrieve: (
        String monitor_id,
        ?request_options: ContextDev::request_opts
      ) -> ContextDev::Models::MonitorRetrieveResponse

      def update: (
        String monitor_id,
        ?change_detection: ContextDev::Models::MonitorUpdateParams::change_detection,
        ?name: String,
        ?schedule: ContextDev::MonitorUpdateParams::Schedule,
        ?status: ContextDev::Models::MonitorUpdateParams::status,
        ?tags: ::Array[String],
        ?target: ContextDev::Models::MonitorUpdateParams::target,
        ?webhook: ContextDev::MonitorUpdateParams::Webhook?,
        ?request_options: ContextDev::request_opts
      ) -> ContextDev::Models::MonitorUpdateResponse

      def list: (
        ?change_detection_type: ContextDev::Models::MonitorListParams::change_detection_type,
        ?cursor: String,
        ?limit: Integer,
        ?q: String,
        ?search_by: ::Array[ContextDev::Models::MonitorListParams::search_by]?,
        ?search_type: ContextDev::Models::MonitorListParams::search_type,
        ?status: ContextDev::Models::MonitorListParams::status,
        ?tag: String,
        ?tags: ::Array[String]?,
        ?target_type: ContextDev::Models::MonitorListParams::target_type,
        ?request_options: ContextDev::request_opts
      ) -> ContextDev::Models::MonitorListResponse

      def delete: (
        String monitor_id,
        ?request_options: ContextDev::request_opts
      ) -> ContextDev::Models::MonitorDeleteResponse

      def get_credit_usage: (
        ?since: Time,
        ?until_: Time,
        ?request_options: ContextDev::request_opts
      ) -> ContextDev::Models::MonitorGetCreditUsageResponse

      def get_limits: (
        ?request_options: ContextDev::request_opts
      ) -> ContextDev::Models::MonitorGetLimitsResponse

      def list_account_changes: (
        ?change_detection_type: ContextDev::Models::MonitorListAccountChangesParams::change_detection_type,
        ?cursor: String,
        ?limit: Integer,
        ?monitor_id: String,
        ?since: Time,
        ?tag: String,
        ?target_type: ContextDev::Models::MonitorListAccountChangesParams::target_type,
        ?until_: Time,
        ?request_options: ContextDev::request_opts
      ) -> ContextDev::Models::MonitorListAccountChangesResponse

      def list_account_runs: (
        ?cursor: String,
        ?limit: Integer,
        ?status: ContextDev::Models::MonitorListAccountRunsParams::status,
        ?request_options: ContextDev::request_opts
      ) -> ContextDev::Models::MonitorListAccountRunsResponse

      def list_changes: (
        String monitor_id,
        ?cursor: String,
        ?limit: Integer,
        ?since: Time,
        ?tag: String,
        ?until_: Time,
        ?request_options: ContextDev::request_opts
      ) -> ContextDev::Models::MonitorListChangesResponse

      def list_runs: (
        String monitor_id,
        ?cursor: String,
        ?limit: Integer,
        ?status: ContextDev::Models::MonitorListRunsParams::status,
        ?request_options: ContextDev::request_opts
      ) -> ContextDev::Models::MonitorListRunsResponse

      def retrieve_change: (
        String change_id,
        ?request_options: ContextDev::request_opts
      ) -> ContextDev::Models::MonitorRetrieveChangeResponse

      def retrieve_run: (
        String run_id,
        monitor_id: String,
        ?request_options: ContextDev::request_opts
      ) -> ContextDev::Models::MonitorRetrieveRunResponse

      def rotate_webhook_secret: (
        String monitor_id,
        ?request_options: ContextDev::request_opts
      ) -> ContextDev::Models::MonitorRotateWebhookSecretResponse

      def run: (
        String monitor_id,
        ?request_options: ContextDev::request_opts
      ) -> ContextDev::Models::MonitorRunResponse

      def initialize: (client: ContextDev::Client) -> void
    end
  end
end
