module ContextDev
  module Resources
    class Parse
      def handle: (
        body: ContextDev::Internal::file_input,
        ?client: String,
        ?extension: ContextDev::Models::ParseHandleParams::extension,
        ?include_images: bool,
        ?include_links: bool,
        ?ocr: bool,
        ?pdf: ContextDev::ParseHandleParams::Pdf,
        ?shorten_base64_images: bool,
        ?tags: ::Array[String],
        ?use_main_content_only: bool,
        ?zdr: ContextDev::Models::ParseHandleParams::zdr,
        ?request_options: ContextDev::request_opts
      ) -> ContextDev::Models::ParseHandleResponse

      def initialize: (client: ContextDev::Client) -> void
    end
  end
end
