module ContextDev
  module Resources
    class Utility
      def prefetch: (
        identifier: ContextDev::Models::UtilityPrefetchParams::identifier,
        type: ContextDev::Models::UtilityPrefetchParams::type_,
        ?tags: ::Array[String],
        ?timeout_ms: Integer,
        ?request_options: ContextDev::request_opts
      ) -> ContextDev::Models::UtilityPrefetchResponse

      def initialize: (client: ContextDev::Client) -> void
    end
  end
end
