module ContextDev
  module Resources
    class Web
      def extract_fonts: (
        ?direct_url: String,
        ?domain: String,
        ?timeout_ms: Integer,
        ?request_options: ContextDev::request_opts
      ) -> ContextDev::Models::WebExtractFontsResponse

      def web_crawl_md: (
        url: String,
        ?follow_subdomains: bool,
        ?include_images: bool,
        ?include_links: bool,
        ?max_depth: Integer,
        ?max_pages: Integer,
        ?shorten_base64_images: bool,
        ?url_regex: String,
        ?use_main_content_only: bool,
        ?request_options: ContextDev::request_opts
      ) -> ContextDev::Models::WebWebCrawlMdResponse

      def web_scrape_html: (
        url: String,
        ?max_age_ms: Integer,
        ?request_options: ContextDev::request_opts
      ) -> ContextDev::Models::WebWebScrapeHTMLResponse

      def web_scrape_images: (
        url: String,
        ?request_options: ContextDev::request_opts
      ) -> ContextDev::Models::WebWebScrapeImagesResponse

      def web_scrape_md: (
        url: String,
        ?include_images: bool,
        ?include_links: bool,
        ?max_age_ms: Integer,
        ?shorten_base64_images: bool,
        ?use_main_content_only: bool,
        ?request_options: ContextDev::request_opts
      ) -> ContextDev::Models::WebWebScrapeMdResponse

      def web_scrape_sitemap: (
        domain: String,
        ?max_links: Integer,
        ?request_options: ContextDev::request_opts
      ) -> ContextDev::Models::WebWebScrapeSitemapResponse

      def initialize: (client: ContextDev::Client) -> void
    end
  end
end
