module ContextDev
  module Resources
    class Web
      def extract_fonts: (
        ?direct_url: String,
        ?domain: String,
        ?timeout_ms: Integer,
        ?request_options: ContextDev::request_opts
      ) -> ContextDev::Models::WebExtractFontsResponse

      def extract_styleguide: (
        ?direct_url: String,
        ?domain: String,
        ?timeout_ms: Integer,
        ?request_options: ContextDev::request_opts
      ) -> ContextDev::Models::WebExtractStyleguideResponse

      def screenshot: (
        ?direct_url: String,
        ?domain: String,
        ?full_screenshot: ContextDev::Models::WebScreenshotParams::full_screenshot,
        ?handle_cookie_popup: ContextDev::Models::WebScreenshotParams::handle_cookie_popup,
        ?max_age_ms: Integer,
        ?page: ContextDev::Models::WebScreenshotParams::page,
        ?timeout_ms: Integer,
        ?viewport: ContextDev::WebScreenshotParams::Viewport,
        ?wait_for_ms: Integer,
        ?request_options: ContextDev::request_opts
      ) -> ContextDev::Models::WebScreenshotResponse

      def search: (
        query: String,
        ?exclude_domains: ::Array[String],
        ?freshness: ContextDev::Models::WebSearchParams::freshness,
        ?include_domains: ::Array[String],
        ?markdown_options: ContextDev::WebSearchParams::MarkdownOptions,
        ?query_fanout: bool,
        ?timeout_ms: Integer,
        ?request_options: ContextDev::request_opts
      ) -> ContextDev::Models::WebSearchResponse

      def web_crawl_md: (
        url: String,
        ?follow_subdomains: bool,
        ?include_frames: bool,
        ?include_images: bool,
        ?include_links: bool,
        ?max_age_ms: Integer,
        ?max_depth: Integer,
        ?max_pages: Integer,
        ?pdf: ContextDev::WebWebCrawlMdParams::Pdf,
        ?shorten_base64_images: bool,
        ?stop_after_ms: Integer,
        ?timeout_ms: Integer,
        ?url_regex: String,
        ?use_main_content_only: bool,
        ?wait_for_ms: Integer,
        ?request_options: ContextDev::request_opts
      ) -> ContextDev::Models::WebWebCrawlMdResponse

      def web_scrape_html: (
        url: String,
        ?include_frames: bool,
        ?max_age_ms: Integer,
        ?pdf: ContextDev::WebWebScrapeHTMLParams::Pdf,
        ?timeout_ms: Integer,
        ?wait_for_ms: Integer,
        ?request_options: ContextDev::request_opts
      ) -> ContextDev::Models::WebWebScrapeHTMLResponse

      def web_scrape_images: (
        url: String,
        ?enrichment: ContextDev::WebWebScrapeImagesParams::Enrichment,
        ?max_age_ms: Integer,
        ?timeout_ms: Integer,
        ?wait_for_ms: Integer,
        ?request_options: ContextDev::request_opts
      ) -> ContextDev::Models::WebWebScrapeImagesResponse

      def web_scrape_md: (
        url: String,
        ?include_frames: bool,
        ?include_images: bool,
        ?include_links: bool,
        ?max_age_ms: Integer,
        ?pdf: ContextDev::WebWebScrapeMdParams::Pdf,
        ?shorten_base64_images: bool,
        ?timeout_ms: Integer,
        ?use_main_content_only: bool,
        ?wait_for_ms: Integer,
        ?request_options: ContextDev::request_opts
      ) -> ContextDev::Models::WebWebScrapeMdResponse

      def web_scrape_sitemap: (
        domain: String,
        ?max_links: Integer,
        ?timeout_ms: Integer,
        ?url_regex: String,
        ?request_options: ContextDev::request_opts
      ) -> ContextDev::Models::WebWebScrapeSitemapResponse

      def initialize: (client: ContextDev::Client) -> void
    end
  end
end
