module ContextDev
  class Client < ContextDev::Internal::Transport::BaseClient
    DEFAULT_MAX_RETRIES: 2

    DEFAULT_TIMEOUT_IN_SECONDS: Float

    DEFAULT_INITIAL_RETRY_DELAY: Float

    DEFAULT_MAX_RETRY_DELAY: Float

    attr_reader api_key: String

    attr_reader parse: ContextDev::Resources::Parse

    attr_reader web: ContextDev::Resources::Web

    attr_reader ai: ContextDev::Resources::AI

    attr_reader brand: ContextDev::Resources::Brand

    attr_reader industry: ContextDev::Resources::Industry

    attr_reader utility: ContextDev::Resources::Utility

    attr_reader monitors: ContextDev::Resources::Monitors

    attr_reader batch: ContextDev::Resources::Batch

    attr_reader webhooks: ContextDev::Resources::Webhooks

    attr_reader people: ContextDev::Resources::People

    attr_reader news: ContextDev::Resources::News

    attr_reader logs: ContextDev::Resources::Logs

    private def auth_headers: -> ::Hash[String, String]

    def initialize: (
      ?api_key: String?,
      ?base_url: String?,
      ?max_retries: Integer,
      ?timeout: Float,
      ?initial_retry_delay: Float,
      ?max_retry_delay: Float
    ) -> void
  end
end
