module ContextDev
  class AIExtractProductParams = ContextDev::Models::AIExtractProductParams

  class AIExtractProductsParams = ContextDev::Models::AIExtractProductsParams

  class BrandRetrieveParams = ContextDev::Models::BrandRetrieveParams

  class BrandRetrieveSimplifiedParams = ContextDev::Models::BrandRetrieveSimplifiedParams

  class IndustryRetrieveNaicsParams = ContextDev::Models::IndustryRetrieveNaicsParams

  class IndustryRetrieveSicParams = ContextDev::Models::IndustryRetrieveSicParams

  class MonitorCreateParams = ContextDev::Models::MonitorCreateParams

  class MonitorDeleteParams = ContextDev::Models::MonitorDeleteParams

  class MonitorListAccountChangesParams = ContextDev::Models::MonitorListAccountChangesParams

  class MonitorListAccountRunsParams = ContextDev::Models::MonitorListAccountRunsParams

  class MonitorListChangesParams = ContextDev::Models::MonitorListChangesParams

  class MonitorListParams = ContextDev::Models::MonitorListParams

  class MonitorListRunsParams = ContextDev::Models::MonitorListRunsParams

  class MonitorRetrieveChangeParams = ContextDev::Models::MonitorRetrieveChangeParams

  class MonitorRetrieveParams = ContextDev::Models::MonitorRetrieveParams

  class MonitorRunParams = ContextDev::Models::MonitorRunParams

  class MonitorUpdateParams = ContextDev::Models::MonitorUpdateParams

  class UtilityPrefetchParams = ContextDev::Models::UtilityPrefetchParams

  class WebExtractCompetitorsParams = ContextDev::Models::WebExtractCompetitorsParams

  class WebExtractFontsParams = ContextDev::Models::WebExtractFontsParams

  class WebExtractParams = ContextDev::Models::WebExtractParams

  class WebExtractStyleguideParams = ContextDev::Models::WebExtractStyleguideParams

  class WebScreenshotParams = ContextDev::Models::WebScreenshotParams

  class WebSearchParams = ContextDev::Models::WebSearchParams

  class WebWebCrawlMdParams = ContextDev::Models::WebWebCrawlMdParams

  class WebWebScrapeHTMLParams = ContextDev::Models::WebWebScrapeHTMLParams

  class WebWebScrapeImagesParams = ContextDev::Models::WebWebScrapeImagesParams

  class WebWebScrapeMdParams = ContextDev::Models::WebWebScrapeMdParams

  class WebWebScrapeSitemapParams = ContextDev::Models::WebWebScrapeSitemapParams
end
