module ContextDev
  module Models
    type ai_extract_product_params =
      {
        url: String,
        max_age_ms: Integer,
        tags: ::Array[String],
        timeout_opts: ContextDev::AIExtractProductParams::TimeoutOpts
      }
      & ContextDev::Internal::Type::request_parameters

    class AIExtractProductParams < ContextDev::Internal::Type::BaseModel
      extend ContextDev::Internal::Type::RequestParameters::Converter
      include ContextDev::Internal::Type::RequestParameters

      attr_accessor url: String

      attr_reader max_age_ms: Integer?

      def max_age_ms=: (Integer) -> Integer

      attr_reader tags: ::Array[String]?

      def tags=: (::Array[String]) -> ::Array[String]

      attr_reader timeout_opts: ContextDev::AIExtractProductParams::TimeoutOpts?

      def timeout_opts=: (
        ContextDev::AIExtractProductParams::TimeoutOpts
      ) -> ContextDev::AIExtractProductParams::TimeoutOpts

      def initialize: (
        url: String,
        ?max_age_ms: Integer,
        ?tags: ::Array[String],
        ?timeout_opts: ContextDev::AIExtractProductParams::TimeoutOpts,
        ?request_options: ContextDev::request_opts
      ) -> void

      def to_hash: -> {
        url: String,
        max_age_ms: Integer,
        tags: ::Array[String],
        timeout_opts: ContextDev::AIExtractProductParams::TimeoutOpts,
        request_options: ContextDev::RequestOptions
      }

      type timeout_opts =
        {
          milliseconds: Integer,
          behavior: ContextDev::Models::AIExtractProductParams::TimeoutOpts::behavior
        }

      class TimeoutOpts < ContextDev::Internal::Type::BaseModel
        attr_accessor milliseconds: Integer

        attr_reader behavior: ContextDev::Models::AIExtractProductParams::TimeoutOpts::behavior?

        def behavior=: (
          ContextDev::Models::AIExtractProductParams::TimeoutOpts::behavior
        ) -> ContextDev::Models::AIExtractProductParams::TimeoutOpts::behavior

        def initialize: (
          milliseconds: Integer,
          ?behavior: ContextDev::Models::AIExtractProductParams::TimeoutOpts::behavior
        ) -> void

        def to_hash: -> {
          milliseconds: Integer,
          behavior: ContextDev::Models::AIExtractProductParams::TimeoutOpts::behavior
        }

        type behavior = :fail | :"return-partial"

        module Behavior
          extend ContextDev::Internal::Type::Enum

          FAIL: :fail
          RETURN_PARTIAL: :"return-partial"

          def self?.values: -> ::Array[ContextDev::Models::AIExtractProductParams::TimeoutOpts::behavior]
        end
      end
    end
  end
end
