module ContextDev
  module Models
    type brand_retrieve_simplified_params =
      {
        domain: String,
        max_age_ms: Integer?,
        tags: ::Array[String],
        theme: ContextDev::Models::BrandRetrieveSimplifiedParams::theme,
        timeout_opts: ContextDev::BrandRetrieveSimplifiedParams::TimeoutOpts
      }
      & ContextDev::Internal::Type::request_parameters

    class BrandRetrieveSimplifiedParams < ContextDev::Internal::Type::BaseModel
      extend ContextDev::Internal::Type::RequestParameters::Converter
      include ContextDev::Internal::Type::RequestParameters

      attr_accessor domain: String

      attr_accessor max_age_ms: Integer?

      attr_reader tags: ::Array[String]?

      def tags=: (::Array[String]) -> ::Array[String]

      attr_reader theme: ContextDev::Models::BrandRetrieveSimplifiedParams::theme?

      def theme=: (
        ContextDev::Models::BrandRetrieveSimplifiedParams::theme
      ) -> ContextDev::Models::BrandRetrieveSimplifiedParams::theme

      attr_reader timeout_opts: ContextDev::BrandRetrieveSimplifiedParams::TimeoutOpts?

      def timeout_opts=: (
        ContextDev::BrandRetrieveSimplifiedParams::TimeoutOpts
      ) -> ContextDev::BrandRetrieveSimplifiedParams::TimeoutOpts

      def initialize: (
        domain: String,
        ?max_age_ms: Integer?,
        ?tags: ::Array[String],
        ?theme: ContextDev::Models::BrandRetrieveSimplifiedParams::theme,
        ?timeout_opts: ContextDev::BrandRetrieveSimplifiedParams::TimeoutOpts,
        ?request_options: ContextDev::request_opts
      ) -> void

      def to_hash: -> {
        domain: String,
        max_age_ms: Integer?,
        tags: ::Array[String],
        theme: ContextDev::Models::BrandRetrieveSimplifiedParams::theme,
        timeout_opts: ContextDev::BrandRetrieveSimplifiedParams::TimeoutOpts,
        request_options: ContextDev::RequestOptions
      }

      type theme = :light | :dark

      module Theme
        extend ContextDev::Internal::Type::Enum

        LIGHT: :light
        DARK: :dark

        def self?.values: -> ::Array[ContextDev::Models::BrandRetrieveSimplifiedParams::theme]
      end

      type timeout_opts =
        {
          milliseconds: Integer,
          behavior: ContextDev::Models::BrandRetrieveSimplifiedParams::TimeoutOpts::behavior
        }

      class TimeoutOpts < ContextDev::Internal::Type::BaseModel
        attr_accessor milliseconds: Integer

        attr_reader behavior: ContextDev::Models::BrandRetrieveSimplifiedParams::TimeoutOpts::behavior?

        def behavior=: (
          ContextDev::Models::BrandRetrieveSimplifiedParams::TimeoutOpts::behavior
        ) -> ContextDev::Models::BrandRetrieveSimplifiedParams::TimeoutOpts::behavior

        def initialize: (
          milliseconds: Integer,
          ?behavior: ContextDev::Models::BrandRetrieveSimplifiedParams::TimeoutOpts::behavior
        ) -> void

        def to_hash: -> {
          milliseconds: Integer,
          behavior: ContextDev::Models::BrandRetrieveSimplifiedParams::TimeoutOpts::behavior
        }

        type behavior = :fail | :"return-partial"

        module Behavior
          extend ContextDev::Internal::Type::Enum

          FAIL: :fail
          RETURN_PARTIAL: :"return-partial"

          def self?.values: -> ::Array[ContextDev::Models::BrandRetrieveSimplifiedParams::TimeoutOpts::behavior]
        end
      end
    end
  end
end
