module ContextDev
  module Models
    type brand_retrieve_params =
      { body: ContextDev::Models::BrandRetrieveParams::body }
      & ContextDev::Internal::Type::request_parameters

    class BrandRetrieveParams < ContextDev::Internal::Type::BaseModel
      extend ContextDev::Internal::Type::RequestParameters::Converter
      include ContextDev::Internal::Type::RequestParameters

      attr_accessor body: ContextDev::Models::BrandRetrieveParams::body

      def initialize: (
        body: ContextDev::Models::BrandRetrieveParams::body,
        ?request_options: ContextDev::request_opts
      ) -> void

      def to_hash: -> {
        body: ContextDev::Models::BrandRetrieveParams::body,
        request_options: ContextDev::RequestOptions
      }

      type body =
        ContextDev::BrandRetrieveParams::Body::ByDomain
        | ContextDev::BrandRetrieveParams::Body::ByName
        | ContextDev::BrandRetrieveParams::Body::ByEmail
        | ContextDev::BrandRetrieveParams::Body::ByTicker
        | ContextDev::BrandRetrieveParams::Body::ByDirectURL
        | ContextDev::BrandRetrieveParams::Body::ByTransaction

      module Body
        extend ContextDev::Internal::Type::Union

        type by_domain =
          {
            domain: String,
            type: :by_domain,
            force_language: ContextDev::Models::BrandRetrieveParams::Body::ByDomain::force_language?,
            max_age_ms: Integer,
            max_speed: bool,
            tags: ::Array[String],
            timeout_opts: ContextDev::BrandRetrieveParams::Body::ByDomain::TimeoutOpts
          }

        class ByDomain < ContextDev::Internal::Type::BaseModel
          attr_accessor domain: String

          attr_accessor type: :by_domain

          attr_accessor force_language: ContextDev::Models::BrandRetrieveParams::Body::ByDomain::force_language?

          attr_reader max_age_ms: Integer?

          def max_age_ms=: (Integer) -> Integer

          attr_reader max_speed: bool?

          def max_speed=: (bool) -> bool

          attr_reader tags: ::Array[String]?

          def tags=: (::Array[String]) -> ::Array[String]

          attr_reader timeout_opts: ContextDev::BrandRetrieveParams::Body::ByDomain::TimeoutOpts?

          def timeout_opts=: (
            ContextDev::BrandRetrieveParams::Body::ByDomain::TimeoutOpts
          ) -> ContextDev::BrandRetrieveParams::Body::ByDomain::TimeoutOpts

          def initialize: (
            domain: String,
            ?force_language: ContextDev::Models::BrandRetrieveParams::Body::ByDomain::force_language?,
            ?max_age_ms: Integer,
            ?max_speed: bool,
            ?tags: ::Array[String],
            ?timeout_opts: ContextDev::BrandRetrieveParams::Body::ByDomain::TimeoutOpts,
            ?type: :by_domain
          ) -> void

          def to_hash: -> {
            domain: String,
            type: :by_domain,
            force_language: ContextDev::Models::BrandRetrieveParams::Body::ByDomain::force_language?,
            max_age_ms: Integer,
            max_speed: bool,
            tags: ::Array[String],
            timeout_opts: ContextDev::BrandRetrieveParams::Body::ByDomain::TimeoutOpts
          }

          type force_language =
            :afrikaans
            | :albanian
            | :amharic
            | :arabic
            | :armenian
            | :assamese
            | :aymara
            | :azeri
            | :basque
            | :belarusian
            | :bengali
            | :bosnian
            | :bulgarian
            | :burmese
            | :cantonese
            | :catalan
            | :cebuano
            | :chinese
            | :corsican
            | :croatian
            | :czech
            | :danish
            | :dutch
            | :english
            | :esperanto
            | :estonian
            | :farsi
            | :fijian
            | :finnish
            | :french
            | :galician
            | :georgian
            | :german
            | :greek
            | :guarani
            | :gujarati
            | :"haitian-creole"
            | :hausa
            | :hawaiian
            | :hebrew
            | :hindi
            | :hmong
            | :hungarian
            | :icelandic
            | :igbo
            | :indonesian
            | :irish
            | :italian
            | :japanese
            | :javanese
            | :kannada
            | :kazakh
            | :khmer
            | :kinyarwanda
            | :korean
            | :kurdish
            | :kyrgyz
            | :lao
            | :latin
            | :latvian
            | :lingala
            | :lithuanian
            | :luxembourgish
            | :macedonian
            | :malagasy
            | :malay
            | :malayalam
            | :maltese
            | :maori
            | :marathi
            | :mongolian
            | :nepali
            | :norwegian
            | :odia
            | :oromo
            | :pashto
            | :pidgin
            | :polish
            | :portuguese
            | :punjabi
            | :quechua
            | :romanian
            | :russian
            | :samoan
            | :"scottish-gaelic"
            | :serbian
            | :sesotho
            | :shona
            | :sindhi
            | :sinhala
            | :slovak
            | :slovene
            | :somali
            | :spanish
            | :sundanese
            | :swahili
            | :swedish
            | :tagalog
            | :tajik
            | :tamil
            | :tatar
            | :telugu
            | :thai
            | :tibetan
            | :tigrinya
            | :tongan
            | :tswana
            | :turkish
            | :turkmen
            | :ukrainian
            | :urdu
            | :uyghur
            | :uzbek
            | :vietnamese
            | :welsh
            | :wolof
            | :xhosa
            | :yiddish
            | :yoruba
            | :zulu

          module ForceLanguage
            extend ContextDev::Internal::Type::Enum

            AFRIKAANS: :afrikaans
            ALBANIAN: :albanian
            AMHARIC: :amharic
            ARABIC: :arabic
            ARMENIAN: :armenian
            ASSAMESE: :assamese
            AYMARA: :aymara
            AZERI: :azeri
            BASQUE: :basque
            BELARUSIAN: :belarusian
            BENGALI: :bengali
            BOSNIAN: :bosnian
            BULGARIAN: :bulgarian
            BURMESE: :burmese
            CANTONESE: :cantonese
            CATALAN: :catalan
            CEBUANO: :cebuano
            CHINESE: :chinese
            CORSICAN: :corsican
            CROATIAN: :croatian
            CZECH: :czech
            DANISH: :danish
            DUTCH: :dutch
            ENGLISH: :english
            ESPERANTO: :esperanto
            ESTONIAN: :estonian
            FARSI: :farsi
            FIJIAN: :fijian
            FINNISH: :finnish
            FRENCH: :french
            GALICIAN: :galician
            GEORGIAN: :georgian
            GERMAN: :german
            GREEK: :greek
            GUARANI: :guarani
            GUJARATI: :gujarati
            HAITIAN_CREOLE: :"haitian-creole"
            HAUSA: :hausa
            HAWAIIAN: :hawaiian
            HEBREW: :hebrew
            HINDI: :hindi
            HMONG: :hmong
            HUNGARIAN: :hungarian
            ICELANDIC: :icelandic
            IGBO: :igbo
            INDONESIAN: :indonesian
            IRISH: :irish
            ITALIAN: :italian
            JAPANESE: :japanese
            JAVANESE: :javanese
            KANNADA: :kannada
            KAZAKH: :kazakh
            KHMER: :khmer
            KINYARWANDA: :kinyarwanda
            KOREAN: :korean
            KURDISH: :kurdish
            KYRGYZ: :kyrgyz
            LAO: :lao
            LATIN: :latin
            LATVIAN: :latvian
            LINGALA: :lingala
            LITHUANIAN: :lithuanian
            LUXEMBOURGISH: :luxembourgish
            MACEDONIAN: :macedonian
            MALAGASY: :malagasy
            MALAY: :malay
            MALAYALAM: :malayalam
            MALTESE: :maltese
            MAORI: :maori
            MARATHI: :marathi
            MONGOLIAN: :mongolian
            NEPALI: :nepali
            NORWEGIAN: :norwegian
            ODIA: :odia
            OROMO: :oromo
            PASHTO: :pashto
            PIDGIN: :pidgin
            POLISH: :polish
            PORTUGUESE: :portuguese
            PUNJABI: :punjabi
            QUECHUA: :quechua
            ROMANIAN: :romanian
            RUSSIAN: :russian
            SAMOAN: :samoan
            SCOTTISH_GAELIC: :"scottish-gaelic"
            SERBIAN: :serbian
            SESOTHO: :sesotho
            SHONA: :shona
            SINDHI: :sindhi
            SINHALA: :sinhala
            SLOVAK: :slovak
            SLOVENE: :slovene
            SOMALI: :somali
            SPANISH: :spanish
            SUNDANESE: :sundanese
            SWAHILI: :swahili
            SWEDISH: :swedish
            TAGALOG: :tagalog
            TAJIK: :tajik
            TAMIL: :tamil
            TATAR: :tatar
            TELUGU: :telugu
            THAI: :thai
            TIBETAN: :tibetan
            TIGRINYA: :tigrinya
            TONGAN: :tongan
            TSWANA: :tswana
            TURKISH: :turkish
            TURKMEN: :turkmen
            UKRAINIAN: :ukrainian
            URDU: :urdu
            UYGHUR: :uyghur
            UZBEK: :uzbek
            VIETNAMESE: :vietnamese
            WELSH: :welsh
            WOLOF: :wolof
            XHOSA: :xhosa
            YIDDISH: :yiddish
            YORUBA: :yoruba
            ZULU: :zulu

            def self?.values: -> ::Array[ContextDev::Models::BrandRetrieveParams::Body::ByDomain::force_language]
          end

          type timeout_opts =
            {
              milliseconds: Integer,
              behavior: ContextDev::Models::BrandRetrieveParams::Body::ByDomain::TimeoutOpts::behavior
            }

          class TimeoutOpts < ContextDev::Internal::Type::BaseModel
            attr_accessor milliseconds: Integer

            attr_reader behavior: ContextDev::Models::BrandRetrieveParams::Body::ByDomain::TimeoutOpts::behavior?

            def behavior=: (
              ContextDev::Models::BrandRetrieveParams::Body::ByDomain::TimeoutOpts::behavior
            ) -> ContextDev::Models::BrandRetrieveParams::Body::ByDomain::TimeoutOpts::behavior

            def initialize: (
              milliseconds: Integer,
              ?behavior: ContextDev::Models::BrandRetrieveParams::Body::ByDomain::TimeoutOpts::behavior
            ) -> void

            def to_hash: -> {
              milliseconds: Integer,
              behavior: ContextDev::Models::BrandRetrieveParams::Body::ByDomain::TimeoutOpts::behavior
            }

            type behavior = :fail | :"return-partial"

            module Behavior
              extend ContextDev::Internal::Type::Enum

              FAIL: :fail
              RETURN_PARTIAL: :"return-partial"

              def self?.values: -> ::Array[ContextDev::Models::BrandRetrieveParams::Body::ByDomain::TimeoutOpts::behavior]
            end
          end
        end

        type by_name =
          {
            name: String,
            type: :by_name,
            country_gl: String,
            force_language: ContextDev::Models::BrandRetrieveParams::Body::ByName::force_language?,
            max_age_ms: Integer,
            max_speed: bool,
            tags: ::Array[String],
            timeout_opts: ContextDev::BrandRetrieveParams::Body::ByName::TimeoutOpts
          }

        class ByName < ContextDev::Internal::Type::BaseModel
          attr_accessor name: String

          attr_accessor type: :by_name

          attr_reader country_gl: String?

          def country_gl=: (String) -> String

          attr_accessor force_language: ContextDev::Models::BrandRetrieveParams::Body::ByName::force_language?

          attr_reader max_age_ms: Integer?

          def max_age_ms=: (Integer) -> Integer

          attr_reader max_speed: bool?

          def max_speed=: (bool) -> bool

          attr_reader tags: ::Array[String]?

          def tags=: (::Array[String]) -> ::Array[String]

          attr_reader timeout_opts: ContextDev::BrandRetrieveParams::Body::ByName::TimeoutOpts?

          def timeout_opts=: (
            ContextDev::BrandRetrieveParams::Body::ByName::TimeoutOpts
          ) -> ContextDev::BrandRetrieveParams::Body::ByName::TimeoutOpts

          def initialize: (
            name: String,
            ?country_gl: String,
            ?force_language: ContextDev::Models::BrandRetrieveParams::Body::ByName::force_language?,
            ?max_age_ms: Integer,
            ?max_speed: bool,
            ?tags: ::Array[String],
            ?timeout_opts: ContextDev::BrandRetrieveParams::Body::ByName::TimeoutOpts,
            ?type: :by_name
          ) -> void

          def to_hash: -> {
            name: String,
            type: :by_name,
            country_gl: String,
            force_language: ContextDev::Models::BrandRetrieveParams::Body::ByName::force_language?,
            max_age_ms: Integer,
            max_speed: bool,
            tags: ::Array[String],
            timeout_opts: ContextDev::BrandRetrieveParams::Body::ByName::TimeoutOpts
          }

          type force_language =
            :afrikaans
            | :albanian
            | :amharic
            | :arabic
            | :armenian
            | :assamese
            | :aymara
            | :azeri
            | :basque
            | :belarusian
            | :bengali
            | :bosnian
            | :bulgarian
            | :burmese
            | :cantonese
            | :catalan
            | :cebuano
            | :chinese
            | :corsican
            | :croatian
            | :czech
            | :danish
            | :dutch
            | :english
            | :esperanto
            | :estonian
            | :farsi
            | :fijian
            | :finnish
            | :french
            | :galician
            | :georgian
            | :german
            | :greek
            | :guarani
            | :gujarati
            | :"haitian-creole"
            | :hausa
            | :hawaiian
            | :hebrew
            | :hindi
            | :hmong
            | :hungarian
            | :icelandic
            | :igbo
            | :indonesian
            | :irish
            | :italian
            | :japanese
            | :javanese
            | :kannada
            | :kazakh
            | :khmer
            | :kinyarwanda
            | :korean
            | :kurdish
            | :kyrgyz
            | :lao
            | :latin
            | :latvian
            | :lingala
            | :lithuanian
            | :luxembourgish
            | :macedonian
            | :malagasy
            | :malay
            | :malayalam
            | :maltese
            | :maori
            | :marathi
            | :mongolian
            | :nepali
            | :norwegian
            | :odia
            | :oromo
            | :pashto
            | :pidgin
            | :polish
            | :portuguese
            | :punjabi
            | :quechua
            | :romanian
            | :russian
            | :samoan
            | :"scottish-gaelic"
            | :serbian
            | :sesotho
            | :shona
            | :sindhi
            | :sinhala
            | :slovak
            | :slovene
            | :somali
            | :spanish
            | :sundanese
            | :swahili
            | :swedish
            | :tagalog
            | :tajik
            | :tamil
            | :tatar
            | :telugu
            | :thai
            | :tibetan
            | :tigrinya
            | :tongan
            | :tswana
            | :turkish
            | :turkmen
            | :ukrainian
            | :urdu
            | :uyghur
            | :uzbek
            | :vietnamese
            | :welsh
            | :wolof
            | :xhosa
            | :yiddish
            | :yoruba
            | :zulu

          module ForceLanguage
            extend ContextDev::Internal::Type::Enum

            AFRIKAANS: :afrikaans
            ALBANIAN: :albanian
            AMHARIC: :amharic
            ARABIC: :arabic
            ARMENIAN: :armenian
            ASSAMESE: :assamese
            AYMARA: :aymara
            AZERI: :azeri
            BASQUE: :basque
            BELARUSIAN: :belarusian
            BENGALI: :bengali
            BOSNIAN: :bosnian
            BULGARIAN: :bulgarian
            BURMESE: :burmese
            CANTONESE: :cantonese
            CATALAN: :catalan
            CEBUANO: :cebuano
            CHINESE: :chinese
            CORSICAN: :corsican
            CROATIAN: :croatian
            CZECH: :czech
            DANISH: :danish
            DUTCH: :dutch
            ENGLISH: :english
            ESPERANTO: :esperanto
            ESTONIAN: :estonian
            FARSI: :farsi
            FIJIAN: :fijian
            FINNISH: :finnish
            FRENCH: :french
            GALICIAN: :galician
            GEORGIAN: :georgian
            GERMAN: :german
            GREEK: :greek
            GUARANI: :guarani
            GUJARATI: :gujarati
            HAITIAN_CREOLE: :"haitian-creole"
            HAUSA: :hausa
            HAWAIIAN: :hawaiian
            HEBREW: :hebrew
            HINDI: :hindi
            HMONG: :hmong
            HUNGARIAN: :hungarian
            ICELANDIC: :icelandic
            IGBO: :igbo
            INDONESIAN: :indonesian
            IRISH: :irish
            ITALIAN: :italian
            JAPANESE: :japanese
            JAVANESE: :javanese
            KANNADA: :kannada
            KAZAKH: :kazakh
            KHMER: :khmer
            KINYARWANDA: :kinyarwanda
            KOREAN: :korean
            KURDISH: :kurdish
            KYRGYZ: :kyrgyz
            LAO: :lao
            LATIN: :latin
            LATVIAN: :latvian
            LINGALA: :lingala
            LITHUANIAN: :lithuanian
            LUXEMBOURGISH: :luxembourgish
            MACEDONIAN: :macedonian
            MALAGASY: :malagasy
            MALAY: :malay
            MALAYALAM: :malayalam
            MALTESE: :maltese
            MAORI: :maori
            MARATHI: :marathi
            MONGOLIAN: :mongolian
            NEPALI: :nepali
            NORWEGIAN: :norwegian
            ODIA: :odia
            OROMO: :oromo
            PASHTO: :pashto
            PIDGIN: :pidgin
            POLISH: :polish
            PORTUGUESE: :portuguese
            PUNJABI: :punjabi
            QUECHUA: :quechua
            ROMANIAN: :romanian
            RUSSIAN: :russian
            SAMOAN: :samoan
            SCOTTISH_GAELIC: :"scottish-gaelic"
            SERBIAN: :serbian
            SESOTHO: :sesotho
            SHONA: :shona
            SINDHI: :sindhi
            SINHALA: :sinhala
            SLOVAK: :slovak
            SLOVENE: :slovene
            SOMALI: :somali
            SPANISH: :spanish
            SUNDANESE: :sundanese
            SWAHILI: :swahili
            SWEDISH: :swedish
            TAGALOG: :tagalog
            TAJIK: :tajik
            TAMIL: :tamil
            TATAR: :tatar
            TELUGU: :telugu
            THAI: :thai
            TIBETAN: :tibetan
            TIGRINYA: :tigrinya
            TONGAN: :tongan
            TSWANA: :tswana
            TURKISH: :turkish
            TURKMEN: :turkmen
            UKRAINIAN: :ukrainian
            URDU: :urdu
            UYGHUR: :uyghur
            UZBEK: :uzbek
            VIETNAMESE: :vietnamese
            WELSH: :welsh
            WOLOF: :wolof
            XHOSA: :xhosa
            YIDDISH: :yiddish
            YORUBA: :yoruba
            ZULU: :zulu

            def self?.values: -> ::Array[ContextDev::Models::BrandRetrieveParams::Body::ByName::force_language]
          end

          type timeout_opts =
            {
              milliseconds: Integer,
              behavior: ContextDev::Models::BrandRetrieveParams::Body::ByName::TimeoutOpts::behavior
            }

          class TimeoutOpts < ContextDev::Internal::Type::BaseModel
            attr_accessor milliseconds: Integer

            attr_reader behavior: ContextDev::Models::BrandRetrieveParams::Body::ByName::TimeoutOpts::behavior?

            def behavior=: (
              ContextDev::Models::BrandRetrieveParams::Body::ByName::TimeoutOpts::behavior
            ) -> ContextDev::Models::BrandRetrieveParams::Body::ByName::TimeoutOpts::behavior

            def initialize: (
              milliseconds: Integer,
              ?behavior: ContextDev::Models::BrandRetrieveParams::Body::ByName::TimeoutOpts::behavior
            ) -> void

            def to_hash: -> {
              milliseconds: Integer,
              behavior: ContextDev::Models::BrandRetrieveParams::Body::ByName::TimeoutOpts::behavior
            }

            type behavior = :fail | :"return-partial"

            module Behavior
              extend ContextDev::Internal::Type::Enum

              FAIL: :fail
              RETURN_PARTIAL: :"return-partial"

              def self?.values: -> ::Array[ContextDev::Models::BrandRetrieveParams::Body::ByName::TimeoutOpts::behavior]
            end
          end
        end

        type by_email =
          {
            email: String,
            type: :by_email,
            force_language: ContextDev::Models::BrandRetrieveParams::Body::ByEmail::force_language?,
            max_age_ms: Integer,
            max_speed: bool,
            tags: ::Array[String],
            timeout_opts: ContextDev::BrandRetrieveParams::Body::ByEmail::TimeoutOpts
          }

        class ByEmail < ContextDev::Internal::Type::BaseModel
          attr_accessor email: String

          attr_accessor type: :by_email

          attr_accessor force_language: ContextDev::Models::BrandRetrieveParams::Body::ByEmail::force_language?

          attr_reader max_age_ms: Integer?

          def max_age_ms=: (Integer) -> Integer

          attr_reader max_speed: bool?

          def max_speed=: (bool) -> bool

          attr_reader tags: ::Array[String]?

          def tags=: (::Array[String]) -> ::Array[String]

          attr_reader timeout_opts: ContextDev::BrandRetrieveParams::Body::ByEmail::TimeoutOpts?

          def timeout_opts=: (
            ContextDev::BrandRetrieveParams::Body::ByEmail::TimeoutOpts
          ) -> ContextDev::BrandRetrieveParams::Body::ByEmail::TimeoutOpts

          def initialize: (
            email: String,
            ?force_language: ContextDev::Models::BrandRetrieveParams::Body::ByEmail::force_language?,
            ?max_age_ms: Integer,
            ?max_speed: bool,
            ?tags: ::Array[String],
            ?timeout_opts: ContextDev::BrandRetrieveParams::Body::ByEmail::TimeoutOpts,
            ?type: :by_email
          ) -> void

          def to_hash: -> {
            email: String,
            type: :by_email,
            force_language: ContextDev::Models::BrandRetrieveParams::Body::ByEmail::force_language?,
            max_age_ms: Integer,
            max_speed: bool,
            tags: ::Array[String],
            timeout_opts: ContextDev::BrandRetrieveParams::Body::ByEmail::TimeoutOpts
          }

          type force_language =
            :afrikaans
            | :albanian
            | :amharic
            | :arabic
            | :armenian
            | :assamese
            | :aymara
            | :azeri
            | :basque
            | :belarusian
            | :bengali
            | :bosnian
            | :bulgarian
            | :burmese
            | :cantonese
            | :catalan
            | :cebuano
            | :chinese
            | :corsican
            | :croatian
            | :czech
            | :danish
            | :dutch
            | :english
            | :esperanto
            | :estonian
            | :farsi
            | :fijian
            | :finnish
            | :french
            | :galician
            | :georgian
            | :german
            | :greek
            | :guarani
            | :gujarati
            | :"haitian-creole"
            | :hausa
            | :hawaiian
            | :hebrew
            | :hindi
            | :hmong
            | :hungarian
            | :icelandic
            | :igbo
            | :indonesian
            | :irish
            | :italian
            | :japanese
            | :javanese
            | :kannada
            | :kazakh
            | :khmer
            | :kinyarwanda
            | :korean
            | :kurdish
            | :kyrgyz
            | :lao
            | :latin
            | :latvian
            | :lingala
            | :lithuanian
            | :luxembourgish
            | :macedonian
            | :malagasy
            | :malay
            | :malayalam
            | :maltese
            | :maori
            | :marathi
            | :mongolian
            | :nepali
            | :norwegian
            | :odia
            | :oromo
            | :pashto
            | :pidgin
            | :polish
            | :portuguese
            | :punjabi
            | :quechua
            | :romanian
            | :russian
            | :samoan
            | :"scottish-gaelic"
            | :serbian
            | :sesotho
            | :shona
            | :sindhi
            | :sinhala
            | :slovak
            | :slovene
            | :somali
            | :spanish
            | :sundanese
            | :swahili
            | :swedish
            | :tagalog
            | :tajik
            | :tamil
            | :tatar
            | :telugu
            | :thai
            | :tibetan
            | :tigrinya
            | :tongan
            | :tswana
            | :turkish
            | :turkmen
            | :ukrainian
            | :urdu
            | :uyghur
            | :uzbek
            | :vietnamese
            | :welsh
            | :wolof
            | :xhosa
            | :yiddish
            | :yoruba
            | :zulu

          module ForceLanguage
            extend ContextDev::Internal::Type::Enum

            AFRIKAANS: :afrikaans
            ALBANIAN: :albanian
            AMHARIC: :amharic
            ARABIC: :arabic
            ARMENIAN: :armenian
            ASSAMESE: :assamese
            AYMARA: :aymara
            AZERI: :azeri
            BASQUE: :basque
            BELARUSIAN: :belarusian
            BENGALI: :bengali
            BOSNIAN: :bosnian
            BULGARIAN: :bulgarian
            BURMESE: :burmese
            CANTONESE: :cantonese
            CATALAN: :catalan
            CEBUANO: :cebuano
            CHINESE: :chinese
            CORSICAN: :corsican
            CROATIAN: :croatian
            CZECH: :czech
            DANISH: :danish
            DUTCH: :dutch
            ENGLISH: :english
            ESPERANTO: :esperanto
            ESTONIAN: :estonian
            FARSI: :farsi
            FIJIAN: :fijian
            FINNISH: :finnish
            FRENCH: :french
            GALICIAN: :galician
            GEORGIAN: :georgian
            GERMAN: :german
            GREEK: :greek
            GUARANI: :guarani
            GUJARATI: :gujarati
            HAITIAN_CREOLE: :"haitian-creole"
            HAUSA: :hausa
            HAWAIIAN: :hawaiian
            HEBREW: :hebrew
            HINDI: :hindi
            HMONG: :hmong
            HUNGARIAN: :hungarian
            ICELANDIC: :icelandic
            IGBO: :igbo
            INDONESIAN: :indonesian
            IRISH: :irish
            ITALIAN: :italian
            JAPANESE: :japanese
            JAVANESE: :javanese
            KANNADA: :kannada
            KAZAKH: :kazakh
            KHMER: :khmer
            KINYARWANDA: :kinyarwanda
            KOREAN: :korean
            KURDISH: :kurdish
            KYRGYZ: :kyrgyz
            LAO: :lao
            LATIN: :latin
            LATVIAN: :latvian
            LINGALA: :lingala
            LITHUANIAN: :lithuanian
            LUXEMBOURGISH: :luxembourgish
            MACEDONIAN: :macedonian
            MALAGASY: :malagasy
            MALAY: :malay
            MALAYALAM: :malayalam
            MALTESE: :maltese
            MAORI: :maori
            MARATHI: :marathi
            MONGOLIAN: :mongolian
            NEPALI: :nepali
            NORWEGIAN: :norwegian
            ODIA: :odia
            OROMO: :oromo
            PASHTO: :pashto
            PIDGIN: :pidgin
            POLISH: :polish
            PORTUGUESE: :portuguese
            PUNJABI: :punjabi
            QUECHUA: :quechua
            ROMANIAN: :romanian
            RUSSIAN: :russian
            SAMOAN: :samoan
            SCOTTISH_GAELIC: :"scottish-gaelic"
            SERBIAN: :serbian
            SESOTHO: :sesotho
            SHONA: :shona
            SINDHI: :sindhi
            SINHALA: :sinhala
            SLOVAK: :slovak
            SLOVENE: :slovene
            SOMALI: :somali
            SPANISH: :spanish
            SUNDANESE: :sundanese
            SWAHILI: :swahili
            SWEDISH: :swedish
            TAGALOG: :tagalog
            TAJIK: :tajik
            TAMIL: :tamil
            TATAR: :tatar
            TELUGU: :telugu
            THAI: :thai
            TIBETAN: :tibetan
            TIGRINYA: :tigrinya
            TONGAN: :tongan
            TSWANA: :tswana
            TURKISH: :turkish
            TURKMEN: :turkmen
            UKRAINIAN: :ukrainian
            URDU: :urdu
            UYGHUR: :uyghur
            UZBEK: :uzbek
            VIETNAMESE: :vietnamese
            WELSH: :welsh
            WOLOF: :wolof
            XHOSA: :xhosa
            YIDDISH: :yiddish
            YORUBA: :yoruba
            ZULU: :zulu

            def self?.values: -> ::Array[ContextDev::Models::BrandRetrieveParams::Body::ByEmail::force_language]
          end

          type timeout_opts =
            {
              milliseconds: Integer,
              behavior: ContextDev::Models::BrandRetrieveParams::Body::ByEmail::TimeoutOpts::behavior
            }

          class TimeoutOpts < ContextDev::Internal::Type::BaseModel
            attr_accessor milliseconds: Integer

            attr_reader behavior: ContextDev::Models::BrandRetrieveParams::Body::ByEmail::TimeoutOpts::behavior?

            def behavior=: (
              ContextDev::Models::BrandRetrieveParams::Body::ByEmail::TimeoutOpts::behavior
            ) -> ContextDev::Models::BrandRetrieveParams::Body::ByEmail::TimeoutOpts::behavior

            def initialize: (
              milliseconds: Integer,
              ?behavior: ContextDev::Models::BrandRetrieveParams::Body::ByEmail::TimeoutOpts::behavior
            ) -> void

            def to_hash: -> {
              milliseconds: Integer,
              behavior: ContextDev::Models::BrandRetrieveParams::Body::ByEmail::TimeoutOpts::behavior
            }

            type behavior = :fail | :"return-partial"

            module Behavior
              extend ContextDev::Internal::Type::Enum

              FAIL: :fail
              RETURN_PARTIAL: :"return-partial"

              def self?.values: -> ::Array[ContextDev::Models::BrandRetrieveParams::Body::ByEmail::TimeoutOpts::behavior]
            end
          end
        end

        type by_ticker =
          {
            ticker: String,
            type: :by_ticker,
            force_language: ContextDev::Models::BrandRetrieveParams::Body::ByTicker::force_language?,
            max_age_ms: Integer,
            max_speed: bool,
            tags: ::Array[String],
            ticker_exchange: String,
            timeout_opts: ContextDev::BrandRetrieveParams::Body::ByTicker::TimeoutOpts
          }

        class ByTicker < ContextDev::Internal::Type::BaseModel
          attr_accessor ticker: String

          attr_accessor type: :by_ticker

          attr_accessor force_language: ContextDev::Models::BrandRetrieveParams::Body::ByTicker::force_language?

          attr_reader max_age_ms: Integer?

          def max_age_ms=: (Integer) -> Integer

          attr_reader max_speed: bool?

          def max_speed=: (bool) -> bool

          attr_reader tags: ::Array[String]?

          def tags=: (::Array[String]) -> ::Array[String]

          attr_reader ticker_exchange: String?

          def ticker_exchange=: (String) -> String

          attr_reader timeout_opts: ContextDev::BrandRetrieveParams::Body::ByTicker::TimeoutOpts?

          def timeout_opts=: (
            ContextDev::BrandRetrieveParams::Body::ByTicker::TimeoutOpts
          ) -> ContextDev::BrandRetrieveParams::Body::ByTicker::TimeoutOpts

          def initialize: (
            ticker: String,
            ?force_language: ContextDev::Models::BrandRetrieveParams::Body::ByTicker::force_language?,
            ?max_age_ms: Integer,
            ?max_speed: bool,
            ?tags: ::Array[String],
            ?ticker_exchange: String,
            ?timeout_opts: ContextDev::BrandRetrieveParams::Body::ByTicker::TimeoutOpts,
            ?type: :by_ticker
          ) -> void

          def to_hash: -> {
            ticker: String,
            type: :by_ticker,
            force_language: ContextDev::Models::BrandRetrieveParams::Body::ByTicker::force_language?,
            max_age_ms: Integer,
            max_speed: bool,
            tags: ::Array[String],
            ticker_exchange: String,
            timeout_opts: ContextDev::BrandRetrieveParams::Body::ByTicker::TimeoutOpts
          }

          type force_language =
            :afrikaans
            | :albanian
            | :amharic
            | :arabic
            | :armenian
            | :assamese
            | :aymara
            | :azeri
            | :basque
            | :belarusian
            | :bengali
            | :bosnian
            | :bulgarian
            | :burmese
            | :cantonese
            | :catalan
            | :cebuano
            | :chinese
            | :corsican
            | :croatian
            | :czech
            | :danish
            | :dutch
            | :english
            | :esperanto
            | :estonian
            | :farsi
            | :fijian
            | :finnish
            | :french
            | :galician
            | :georgian
            | :german
            | :greek
            | :guarani
            | :gujarati
            | :"haitian-creole"
            | :hausa
            | :hawaiian
            | :hebrew
            | :hindi
            | :hmong
            | :hungarian
            | :icelandic
            | :igbo
            | :indonesian
            | :irish
            | :italian
            | :japanese
            | :javanese
            | :kannada
            | :kazakh
            | :khmer
            | :kinyarwanda
            | :korean
            | :kurdish
            | :kyrgyz
            | :lao
            | :latin
            | :latvian
            | :lingala
            | :lithuanian
            | :luxembourgish
            | :macedonian
            | :malagasy
            | :malay
            | :malayalam
            | :maltese
            | :maori
            | :marathi
            | :mongolian
            | :nepali
            | :norwegian
            | :odia
            | :oromo
            | :pashto
            | :pidgin
            | :polish
            | :portuguese
            | :punjabi
            | :quechua
            | :romanian
            | :russian
            | :samoan
            | :"scottish-gaelic"
            | :serbian
            | :sesotho
            | :shona
            | :sindhi
            | :sinhala
            | :slovak
            | :slovene
            | :somali
            | :spanish
            | :sundanese
            | :swahili
            | :swedish
            | :tagalog
            | :tajik
            | :tamil
            | :tatar
            | :telugu
            | :thai
            | :tibetan
            | :tigrinya
            | :tongan
            | :tswana
            | :turkish
            | :turkmen
            | :ukrainian
            | :urdu
            | :uyghur
            | :uzbek
            | :vietnamese
            | :welsh
            | :wolof
            | :xhosa
            | :yiddish
            | :yoruba
            | :zulu

          module ForceLanguage
            extend ContextDev::Internal::Type::Enum

            AFRIKAANS: :afrikaans
            ALBANIAN: :albanian
            AMHARIC: :amharic
            ARABIC: :arabic
            ARMENIAN: :armenian
            ASSAMESE: :assamese
            AYMARA: :aymara
            AZERI: :azeri
            BASQUE: :basque
            BELARUSIAN: :belarusian
            BENGALI: :bengali
            BOSNIAN: :bosnian
            BULGARIAN: :bulgarian
            BURMESE: :burmese
            CANTONESE: :cantonese
            CATALAN: :catalan
            CEBUANO: :cebuano
            CHINESE: :chinese
            CORSICAN: :corsican
            CROATIAN: :croatian
            CZECH: :czech
            DANISH: :danish
            DUTCH: :dutch
            ENGLISH: :english
            ESPERANTO: :esperanto
            ESTONIAN: :estonian
            FARSI: :farsi
            FIJIAN: :fijian
            FINNISH: :finnish
            FRENCH: :french
            GALICIAN: :galician
            GEORGIAN: :georgian
            GERMAN: :german
            GREEK: :greek
            GUARANI: :guarani
            GUJARATI: :gujarati
            HAITIAN_CREOLE: :"haitian-creole"
            HAUSA: :hausa
            HAWAIIAN: :hawaiian
            HEBREW: :hebrew
            HINDI: :hindi
            HMONG: :hmong
            HUNGARIAN: :hungarian
            ICELANDIC: :icelandic
            IGBO: :igbo
            INDONESIAN: :indonesian
            IRISH: :irish
            ITALIAN: :italian
            JAPANESE: :japanese
            JAVANESE: :javanese
            KANNADA: :kannada
            KAZAKH: :kazakh
            KHMER: :khmer
            KINYARWANDA: :kinyarwanda
            KOREAN: :korean
            KURDISH: :kurdish
            KYRGYZ: :kyrgyz
            LAO: :lao
            LATIN: :latin
            LATVIAN: :latvian
            LINGALA: :lingala
            LITHUANIAN: :lithuanian
            LUXEMBOURGISH: :luxembourgish
            MACEDONIAN: :macedonian
            MALAGASY: :malagasy
            MALAY: :malay
            MALAYALAM: :malayalam
            MALTESE: :maltese
            MAORI: :maori
            MARATHI: :marathi
            MONGOLIAN: :mongolian
            NEPALI: :nepali
            NORWEGIAN: :norwegian
            ODIA: :odia
            OROMO: :oromo
            PASHTO: :pashto
            PIDGIN: :pidgin
            POLISH: :polish
            PORTUGUESE: :portuguese
            PUNJABI: :punjabi
            QUECHUA: :quechua
            ROMANIAN: :romanian
            RUSSIAN: :russian
            SAMOAN: :samoan
            SCOTTISH_GAELIC: :"scottish-gaelic"
            SERBIAN: :serbian
            SESOTHO: :sesotho
            SHONA: :shona
            SINDHI: :sindhi
            SINHALA: :sinhala
            SLOVAK: :slovak
            SLOVENE: :slovene
            SOMALI: :somali
            SPANISH: :spanish
            SUNDANESE: :sundanese
            SWAHILI: :swahili
            SWEDISH: :swedish
            TAGALOG: :tagalog
            TAJIK: :tajik
            TAMIL: :tamil
            TATAR: :tatar
            TELUGU: :telugu
            THAI: :thai
            TIBETAN: :tibetan
            TIGRINYA: :tigrinya
            TONGAN: :tongan
            TSWANA: :tswana
            TURKISH: :turkish
            TURKMEN: :turkmen
            UKRAINIAN: :ukrainian
            URDU: :urdu
            UYGHUR: :uyghur
            UZBEK: :uzbek
            VIETNAMESE: :vietnamese
            WELSH: :welsh
            WOLOF: :wolof
            XHOSA: :xhosa
            YIDDISH: :yiddish
            YORUBA: :yoruba
            ZULU: :zulu

            def self?.values: -> ::Array[ContextDev::Models::BrandRetrieveParams::Body::ByTicker::force_language]
          end

          type timeout_opts =
            {
              milliseconds: Integer,
              behavior: ContextDev::Models::BrandRetrieveParams::Body::ByTicker::TimeoutOpts::behavior
            }

          class TimeoutOpts < ContextDev::Internal::Type::BaseModel
            attr_accessor milliseconds: Integer

            attr_reader behavior: ContextDev::Models::BrandRetrieveParams::Body::ByTicker::TimeoutOpts::behavior?

            def behavior=: (
              ContextDev::Models::BrandRetrieveParams::Body::ByTicker::TimeoutOpts::behavior
            ) -> ContextDev::Models::BrandRetrieveParams::Body::ByTicker::TimeoutOpts::behavior

            def initialize: (
              milliseconds: Integer,
              ?behavior: ContextDev::Models::BrandRetrieveParams::Body::ByTicker::TimeoutOpts::behavior
            ) -> void

            def to_hash: -> {
              milliseconds: Integer,
              behavior: ContextDev::Models::BrandRetrieveParams::Body::ByTicker::TimeoutOpts::behavior
            }

            type behavior = :fail | :"return-partial"

            module Behavior
              extend ContextDev::Internal::Type::Enum

              FAIL: :fail
              RETURN_PARTIAL: :"return-partial"

              def self?.values: -> ::Array[ContextDev::Models::BrandRetrieveParams::Body::ByTicker::TimeoutOpts::behavior]
            end
          end
        end

        type by_direct_url =
          {
            direct_url: String,
            type: :by_direct_url,
            tags: ::Array[String],
            timeout_opts: ContextDev::BrandRetrieveParams::Body::ByDirectURL::TimeoutOpts
          }

        class ByDirectURL < ContextDev::Internal::Type::BaseModel
          attr_accessor direct_url: String

          attr_accessor type: :by_direct_url

          attr_reader tags: ::Array[String]?

          def tags=: (::Array[String]) -> ::Array[String]

          attr_reader timeout_opts: ContextDev::BrandRetrieveParams::Body::ByDirectURL::TimeoutOpts?

          def timeout_opts=: (
            ContextDev::BrandRetrieveParams::Body::ByDirectURL::TimeoutOpts
          ) -> ContextDev::BrandRetrieveParams::Body::ByDirectURL::TimeoutOpts

          def initialize: (
            direct_url: String,
            ?tags: ::Array[String],
            ?timeout_opts: ContextDev::BrandRetrieveParams::Body::ByDirectURL::TimeoutOpts,
            ?type: :by_direct_url
          ) -> void

          def to_hash: -> {
            direct_url: String,
            type: :by_direct_url,
            tags: ::Array[String],
            timeout_opts: ContextDev::BrandRetrieveParams::Body::ByDirectURL::TimeoutOpts
          }

          type timeout_opts =
            {
              milliseconds: Integer,
              behavior: ContextDev::Models::BrandRetrieveParams::Body::ByDirectURL::TimeoutOpts::behavior
            }

          class TimeoutOpts < ContextDev::Internal::Type::BaseModel
            attr_accessor milliseconds: Integer

            attr_reader behavior: ContextDev::Models::BrandRetrieveParams::Body::ByDirectURL::TimeoutOpts::behavior?

            def behavior=: (
              ContextDev::Models::BrandRetrieveParams::Body::ByDirectURL::TimeoutOpts::behavior
            ) -> ContextDev::Models::BrandRetrieveParams::Body::ByDirectURL::TimeoutOpts::behavior

            def initialize: (
              milliseconds: Integer,
              ?behavior: ContextDev::Models::BrandRetrieveParams::Body::ByDirectURL::TimeoutOpts::behavior
            ) -> void

            def to_hash: -> {
              milliseconds: Integer,
              behavior: ContextDev::Models::BrandRetrieveParams::Body::ByDirectURL::TimeoutOpts::behavior
            }

            type behavior = :fail | :"return-partial"

            module Behavior
              extend ContextDev::Internal::Type::Enum

              FAIL: :fail
              RETURN_PARTIAL: :"return-partial"

              def self?.values: -> ::Array[ContextDev::Models::BrandRetrieveParams::Body::ByDirectURL::TimeoutOpts::behavior]
            end
          end
        end

        type by_transaction =
          {
            transaction_info: String,
            type: :by_transaction,
            city: String,
            country_gl: String,
            force_language: ContextDev::Models::BrandRetrieveParams::Body::ByTransaction::force_language?,
            high_confidence_only: bool,
            max_speed: bool,
            mcc: ContextDev::Models::BrandRetrieveParams::Body::ByTransaction::mcc,
            phone: ContextDev::Models::BrandRetrieveParams::Body::ByTransaction::phone,
            tags: ::Array[String],
            timeout_opts: ContextDev::BrandRetrieveParams::Body::ByTransaction::TimeoutOpts
          }

        class ByTransaction < ContextDev::Internal::Type::BaseModel
          attr_accessor transaction_info: String

          attr_accessor type: :by_transaction

          attr_reader city: String?

          def city=: (String) -> String

          attr_reader country_gl: String?

          def country_gl=: (String) -> String

          attr_accessor force_language: ContextDev::Models::BrandRetrieveParams::Body::ByTransaction::force_language?

          attr_reader high_confidence_only: bool?

          def high_confidence_only=: (bool) -> bool

          attr_reader max_speed: bool?

          def max_speed=: (bool) -> bool

          attr_reader mcc: ContextDev::Models::BrandRetrieveParams::Body::ByTransaction::mcc?

          def mcc=: (
            ContextDev::Models::BrandRetrieveParams::Body::ByTransaction::mcc
          ) -> ContextDev::Models::BrandRetrieveParams::Body::ByTransaction::mcc

          attr_reader phone: ContextDev::Models::BrandRetrieveParams::Body::ByTransaction::phone?

          def phone=: (
            ContextDev::Models::BrandRetrieveParams::Body::ByTransaction::phone
          ) -> ContextDev::Models::BrandRetrieveParams::Body::ByTransaction::phone

          attr_reader tags: ::Array[String]?

          def tags=: (::Array[String]) -> ::Array[String]

          attr_reader timeout_opts: ContextDev::BrandRetrieveParams::Body::ByTransaction::TimeoutOpts?

          def timeout_opts=: (
            ContextDev::BrandRetrieveParams::Body::ByTransaction::TimeoutOpts
          ) -> ContextDev::BrandRetrieveParams::Body::ByTransaction::TimeoutOpts

          def initialize: (
            transaction_info: String,
            ?city: String,
            ?country_gl: String,
            ?force_language: ContextDev::Models::BrandRetrieveParams::Body::ByTransaction::force_language?,
            ?high_confidence_only: bool,
            ?max_speed: bool,
            ?mcc: ContextDev::Models::BrandRetrieveParams::Body::ByTransaction::mcc,
            ?phone: ContextDev::Models::BrandRetrieveParams::Body::ByTransaction::phone,
            ?tags: ::Array[String],
            ?timeout_opts: ContextDev::BrandRetrieveParams::Body::ByTransaction::TimeoutOpts,
            ?type: :by_transaction
          ) -> void

          def to_hash: -> {
            transaction_info: String,
            type: :by_transaction,
            city: String,
            country_gl: String,
            force_language: ContextDev::Models::BrandRetrieveParams::Body::ByTransaction::force_language?,
            high_confidence_only: bool,
            max_speed: bool,
            mcc: ContextDev::Models::BrandRetrieveParams::Body::ByTransaction::mcc,
            phone: ContextDev::Models::BrandRetrieveParams::Body::ByTransaction::phone,
            tags: ::Array[String],
            timeout_opts: ContextDev::BrandRetrieveParams::Body::ByTransaction::TimeoutOpts
          }

          type force_language =
            :afrikaans
            | :albanian
            | :amharic
            | :arabic
            | :armenian
            | :assamese
            | :aymara
            | :azeri
            | :basque
            | :belarusian
            | :bengali
            | :bosnian
            | :bulgarian
            | :burmese
            | :cantonese
            | :catalan
            | :cebuano
            | :chinese
            | :corsican
            | :croatian
            | :czech
            | :danish
            | :dutch
            | :english
            | :esperanto
            | :estonian
            | :farsi
            | :fijian
            | :finnish
            | :french
            | :galician
            | :georgian
            | :german
            | :greek
            | :guarani
            | :gujarati
            | :"haitian-creole"
            | :hausa
            | :hawaiian
            | :hebrew
            | :hindi
            | :hmong
            | :hungarian
            | :icelandic
            | :igbo
            | :indonesian
            | :irish
            | :italian
            | :japanese
            | :javanese
            | :kannada
            | :kazakh
            | :khmer
            | :kinyarwanda
            | :korean
            | :kurdish
            | :kyrgyz
            | :lao
            | :latin
            | :latvian
            | :lingala
            | :lithuanian
            | :luxembourgish
            | :macedonian
            | :malagasy
            | :malay
            | :malayalam
            | :maltese
            | :maori
            | :marathi
            | :mongolian
            | :nepali
            | :norwegian
            | :odia
            | :oromo
            | :pashto
            | :pidgin
            | :polish
            | :portuguese
            | :punjabi
            | :quechua
            | :romanian
            | :russian
            | :samoan
            | :"scottish-gaelic"
            | :serbian
            | :sesotho
            | :shona
            | :sindhi
            | :sinhala
            | :slovak
            | :slovene
            | :somali
            | :spanish
            | :sundanese
            | :swahili
            | :swedish
            | :tagalog
            | :tajik
            | :tamil
            | :tatar
            | :telugu
            | :thai
            | :tibetan
            | :tigrinya
            | :tongan
            | :tswana
            | :turkish
            | :turkmen
            | :ukrainian
            | :urdu
            | :uyghur
            | :uzbek
            | :vietnamese
            | :welsh
            | :wolof
            | :xhosa
            | :yiddish
            | :yoruba
            | :zulu

          module ForceLanguage
            extend ContextDev::Internal::Type::Enum

            AFRIKAANS: :afrikaans
            ALBANIAN: :albanian
            AMHARIC: :amharic
            ARABIC: :arabic
            ARMENIAN: :armenian
            ASSAMESE: :assamese
            AYMARA: :aymara
            AZERI: :azeri
            BASQUE: :basque
            BELARUSIAN: :belarusian
            BENGALI: :bengali
            BOSNIAN: :bosnian
            BULGARIAN: :bulgarian
            BURMESE: :burmese
            CANTONESE: :cantonese
            CATALAN: :catalan
            CEBUANO: :cebuano
            CHINESE: :chinese
            CORSICAN: :corsican
            CROATIAN: :croatian
            CZECH: :czech
            DANISH: :danish
            DUTCH: :dutch
            ENGLISH: :english
            ESPERANTO: :esperanto
            ESTONIAN: :estonian
            FARSI: :farsi
            FIJIAN: :fijian
            FINNISH: :finnish
            FRENCH: :french
            GALICIAN: :galician
            GEORGIAN: :georgian
            GERMAN: :german
            GREEK: :greek
            GUARANI: :guarani
            GUJARATI: :gujarati
            HAITIAN_CREOLE: :"haitian-creole"
            HAUSA: :hausa
            HAWAIIAN: :hawaiian
            HEBREW: :hebrew
            HINDI: :hindi
            HMONG: :hmong
            HUNGARIAN: :hungarian
            ICELANDIC: :icelandic
            IGBO: :igbo
            INDONESIAN: :indonesian
            IRISH: :irish
            ITALIAN: :italian
            JAPANESE: :japanese
            JAVANESE: :javanese
            KANNADA: :kannada
            KAZAKH: :kazakh
            KHMER: :khmer
            KINYARWANDA: :kinyarwanda
            KOREAN: :korean
            KURDISH: :kurdish
            KYRGYZ: :kyrgyz
            LAO: :lao
            LATIN: :latin
            LATVIAN: :latvian
            LINGALA: :lingala
            LITHUANIAN: :lithuanian
            LUXEMBOURGISH: :luxembourgish
            MACEDONIAN: :macedonian
            MALAGASY: :malagasy
            MALAY: :malay
            MALAYALAM: :malayalam
            MALTESE: :maltese
            MAORI: :maori
            MARATHI: :marathi
            MONGOLIAN: :mongolian
            NEPALI: :nepali
            NORWEGIAN: :norwegian
            ODIA: :odia
            OROMO: :oromo
            PASHTO: :pashto
            PIDGIN: :pidgin
            POLISH: :polish
            PORTUGUESE: :portuguese
            PUNJABI: :punjabi
            QUECHUA: :quechua
            ROMANIAN: :romanian
            RUSSIAN: :russian
            SAMOAN: :samoan
            SCOTTISH_GAELIC: :"scottish-gaelic"
            SERBIAN: :serbian
            SESOTHO: :sesotho
            SHONA: :shona
            SINDHI: :sindhi
            SINHALA: :sinhala
            SLOVAK: :slovak
            SLOVENE: :slovene
            SOMALI: :somali
            SPANISH: :spanish
            SUNDANESE: :sundanese
            SWAHILI: :swahili
            SWEDISH: :swedish
            TAGALOG: :tagalog
            TAJIK: :tajik
            TAMIL: :tamil
            TATAR: :tatar
            TELUGU: :telugu
            THAI: :thai
            TIBETAN: :tibetan
            TIGRINYA: :tigrinya
            TONGAN: :tongan
            TSWANA: :tswana
            TURKISH: :turkish
            TURKMEN: :turkmen
            UKRAINIAN: :ukrainian
            URDU: :urdu
            UYGHUR: :uyghur
            UZBEK: :uzbek
            VIETNAMESE: :vietnamese
            WELSH: :welsh
            WOLOF: :wolof
            XHOSA: :xhosa
            YIDDISH: :yiddish
            YORUBA: :yoruba
            ZULU: :zulu

            def self?.values: -> ::Array[ContextDev::Models::BrandRetrieveParams::Body::ByTransaction::force_language]
          end

          type mcc = String | Float

          module Mcc
            extend ContextDev::Internal::Type::Union

            def self?.variants: -> ::Array[ContextDev::Models::BrandRetrieveParams::Body::ByTransaction::mcc]
          end

          type phone = String | Float

          module Phone
            extend ContextDev::Internal::Type::Union

            def self?.variants: -> ::Array[ContextDev::Models::BrandRetrieveParams::Body::ByTransaction::phone]
          end

          type timeout_opts =
            {
              milliseconds: Integer,
              behavior: ContextDev::Models::BrandRetrieveParams::Body::ByTransaction::TimeoutOpts::behavior
            }

          class TimeoutOpts < ContextDev::Internal::Type::BaseModel
            attr_accessor milliseconds: Integer

            attr_reader behavior: ContextDev::Models::BrandRetrieveParams::Body::ByTransaction::TimeoutOpts::behavior?

            def behavior=: (
              ContextDev::Models::BrandRetrieveParams::Body::ByTransaction::TimeoutOpts::behavior
            ) -> ContextDev::Models::BrandRetrieveParams::Body::ByTransaction::TimeoutOpts::behavior

            def initialize: (
              milliseconds: Integer,
              ?behavior: ContextDev::Models::BrandRetrieveParams::Body::ByTransaction::TimeoutOpts::behavior
            ) -> void

            def to_hash: -> {
              milliseconds: Integer,
              behavior: ContextDev::Models::BrandRetrieveParams::Body::ByTransaction::TimeoutOpts::behavior
            }

            type behavior = :fail | :"return-partial"

            module Behavior
              extend ContextDev::Internal::Type::Enum

              FAIL: :fail
              RETURN_PARTIAL: :"return-partial"

              def self?.values: -> ::Array[ContextDev::Models::BrandRetrieveParams::Body::ByTransaction::TimeoutOpts::behavior]
            end
          end
        end

        def self?.variants: -> ::Array[ContextDev::Models::BrandRetrieveParams::body]
      end
    end
  end
end
