module ContextDev
  module Models
    type brand_search_params =
      {
        query: String,
        autocomplete: bool,
        query_by: ::Array[ContextDev::Models::BrandSearchParams::query_by],
        tags: ::Array[String],
        typo_tolerance: Integer
      }
      & ContextDev::Internal::Type::request_parameters

    class BrandSearchParams < ContextDev::Internal::Type::BaseModel
      extend ContextDev::Internal::Type::RequestParameters::Converter
      include ContextDev::Internal::Type::RequestParameters

      attr_accessor query: String

      attr_reader autocomplete: bool?

      def autocomplete=: (bool) -> bool

      attr_reader query_by: ::Array[ContextDev::Models::BrandSearchParams::query_by]?

      def query_by=: (
        ::Array[ContextDev::Models::BrandSearchParams::query_by]
      ) -> ::Array[ContextDev::Models::BrandSearchParams::query_by]

      attr_reader tags: ::Array[String]?

      def tags=: (::Array[String]) -> ::Array[String]

      attr_reader typo_tolerance: Integer?

      def typo_tolerance=: (Integer) -> Integer

      def initialize: (
        query: String,
        ?autocomplete: bool,
        ?query_by: ::Array[ContextDev::Models::BrandSearchParams::query_by],
        ?tags: ::Array[String],
        ?typo_tolerance: Integer,
        ?request_options: ContextDev::request_opts
      ) -> void

      def to_hash: -> {
        query: String,
        autocomplete: bool,
        query_by: ::Array[ContextDev::Models::BrandSearchParams::query_by],
        tags: ::Array[String],
        typo_tolerance: Integer,
        request_options: ContextDev::RequestOptions
      }

      type query_by = :name | :domain

      module QueryBy
        extend ContextDev::Internal::Type::Enum

        NAME: :name
        DOMAIN: :domain

        def self?.values: -> ::Array[ContextDev::Models::BrandSearchParams::query_by]
      end
    end
  end
end
