module ContextDev
  module Models
    type failure = { code: String, message: String }

    class Failure < ContextDev::Internal::Type::BaseModel
      attr_accessor code: String

      attr_accessor message: String

      def initialize: (code: String, message: String) -> void

      def to_hash: -> { code: String, message: String }
    end
  end
end
