module ContextDev
  module Models
    type feedback_submit_response =
      {
        already_submitted: bool,
        feedback_id: String,
        request_id: String,
        key_metadata: ContextDev::Models::FeedbackSubmitResponse::KeyMetadata
      }

    class FeedbackSubmitResponse < ContextDev::Internal::Type::BaseModel
      attr_accessor already_submitted: bool

      attr_accessor feedback_id: String

      attr_accessor request_id: String

      attr_reader key_metadata: ContextDev::Models::FeedbackSubmitResponse::KeyMetadata?

      def key_metadata=: (
        ContextDev::Models::FeedbackSubmitResponse::KeyMetadata
      ) -> ContextDev::Models::FeedbackSubmitResponse::KeyMetadata

      def initialize: (
        already_submitted: bool,
        feedback_id: String,
        request_id: String,
        ?key_metadata: ContextDev::Models::FeedbackSubmitResponse::KeyMetadata
      ) -> void

      def to_hash: -> {
        already_submitted: bool,
        feedback_id: String,
        request_id: String,
        key_metadata: ContextDev::Models::FeedbackSubmitResponse::KeyMetadata
      }

      type key_metadata =
        { credits_consumed: Integer, credits_remaining: Integer }

      class KeyMetadata < ContextDev::Internal::Type::BaseModel
        attr_accessor credits_consumed: Integer

        attr_accessor credits_remaining: Integer

        def initialize: (
          credits_consumed: Integer,
          credits_remaining: Integer
        ) -> void

        def to_hash: -> {
          credits_consumed: Integer,
          credits_remaining: Integer
        }
      end
    end
  end
end
