module ContextDev
  module Models
    type monitor_list_changes_response =
      {
        data: ::Array[ContextDev::Models::MonitorListChangesResponse::data],
        has_more: bool,
        next_cursor: String?
      }

    class MonitorListChangesResponse < ContextDev::Internal::Type::BaseModel
      attr_accessor data: ::Array[ContextDev::Models::MonitorListChangesResponse::data]

      attr_accessor has_more: bool

      attr_accessor next_cursor: String?

      def initialize: (
        data: ::Array[ContextDev::Models::MonitorListChangesResponse::data],
        has_more: bool,
        next_cursor: String?
      ) -> void

      def to_hash: -> {
        data: ::Array[ContextDev::Models::MonitorListChangesResponse::data],
        has_more: bool,
        next_cursor: String?
      }

      type data =
        ContextDev::Models::MonitorListChangesResponse::Data::MonitorsPageExactChangeSummary
        | ContextDev::Models::MonitorListChangesResponse::Data::MonitorsSitemapExactChangeSummary
        | ContextDev::Models::MonitorListChangesResponse::Data::MonitorsPageSemanticChangeSummary
        | ContextDev::Models::MonitorListChangesResponse::Data::MonitorsExtractSemanticChangeSummary

      module Data
        extend ContextDev::Internal::Type::Union

        type monitors_page_exact_change_summary =
          {
            id: String,
            change_detection_type: ContextDev::Models::MonitorListChangesResponse::Data::MonitorsPageExactChangeSummary::change_detection_type,
            detected_at: Time,
            monitor_id: String,
            summary: String,
            target_type: ContextDev::Models::MonitorListChangesResponse::Data::MonitorsPageExactChangeSummary::target_type,
            title: String,
            url: String,
            tags: ::Array[String]
          }

        class MonitorsPageExactChangeSummary < ContextDev::Internal::Type::BaseModel
          attr_accessor id: String

          attr_accessor change_detection_type: ContextDev::Models::MonitorListChangesResponse::Data::MonitorsPageExactChangeSummary::change_detection_type

          attr_accessor detected_at: Time

          attr_accessor monitor_id: String

          attr_accessor summary: String

          attr_accessor target_type: ContextDev::Models::MonitorListChangesResponse::Data::MonitorsPageExactChangeSummary::target_type

          attr_accessor title: String

          attr_accessor url: String

          attr_reader tags: ::Array[String]?

          def tags=: (::Array[String]) -> ::Array[String]

          def initialize: (
            id: String,
            change_detection_type: ContextDev::Models::MonitorListChangesResponse::Data::MonitorsPageExactChangeSummary::change_detection_type,
            detected_at: Time,
            monitor_id: String,
            summary: String,
            target_type: ContextDev::Models::MonitorListChangesResponse::Data::MonitorsPageExactChangeSummary::target_type,
            title: String,
            url: String,
            ?tags: ::Array[String]
          ) -> void

          def to_hash: -> {
            id: String,
            change_detection_type: ContextDev::Models::MonitorListChangesResponse::Data::MonitorsPageExactChangeSummary::change_detection_type,
            detected_at: Time,
            monitor_id: String,
            summary: String,
            target_type: ContextDev::Models::MonitorListChangesResponse::Data::MonitorsPageExactChangeSummary::target_type,
            title: String,
            url: String,
            tags: ::Array[String]
          }

          type change_detection_type = :exact

          module ChangeDetectionType
            extend ContextDev::Internal::Type::Enum

            EXACT: :exact

            def self?.values: -> ::Array[ContextDev::Models::MonitorListChangesResponse::Data::MonitorsPageExactChangeSummary::change_detection_type]
          end

          type target_type = :page

          module TargetType
            extend ContextDev::Internal::Type::Enum

            PAGE: :page

            def self?.values: -> ::Array[ContextDev::Models::MonitorListChangesResponse::Data::MonitorsPageExactChangeSummary::target_type]
          end
        end

        type monitors_sitemap_exact_change_summary =
          {
            id: String,
            added_url_count: Integer,
            change_detection_type: ContextDev::Models::MonitorListChangesResponse::Data::MonitorsSitemapExactChangeSummary::change_detection_type,
            detected_at: Time,
            monitor_id: String,
            removed_url_count: Integer,
            summary: String,
            target_type: ContextDev::Models::MonitorListChangesResponse::Data::MonitorsSitemapExactChangeSummary::target_type,
            title: String,
            url: String,
            tags: ::Array[String]
          }

        class MonitorsSitemapExactChangeSummary < ContextDev::Internal::Type::BaseModel
          attr_accessor id: String

          attr_accessor added_url_count: Integer

          attr_accessor change_detection_type: ContextDev::Models::MonitorListChangesResponse::Data::MonitorsSitemapExactChangeSummary::change_detection_type

          attr_accessor detected_at: Time

          attr_accessor monitor_id: String

          attr_accessor removed_url_count: Integer

          attr_accessor summary: String

          attr_accessor target_type: ContextDev::Models::MonitorListChangesResponse::Data::MonitorsSitemapExactChangeSummary::target_type

          attr_accessor title: String

          attr_accessor url: String

          attr_reader tags: ::Array[String]?

          def tags=: (::Array[String]) -> ::Array[String]

          def initialize: (
            id: String,
            added_url_count: Integer,
            change_detection_type: ContextDev::Models::MonitorListChangesResponse::Data::MonitorsSitemapExactChangeSummary::change_detection_type,
            detected_at: Time,
            monitor_id: String,
            removed_url_count: Integer,
            summary: String,
            target_type: ContextDev::Models::MonitorListChangesResponse::Data::MonitorsSitemapExactChangeSummary::target_type,
            title: String,
            url: String,
            ?tags: ::Array[String]
          ) -> void

          def to_hash: -> {
            id: String,
            added_url_count: Integer,
            change_detection_type: ContextDev::Models::MonitorListChangesResponse::Data::MonitorsSitemapExactChangeSummary::change_detection_type,
            detected_at: Time,
            monitor_id: String,
            removed_url_count: Integer,
            summary: String,
            target_type: ContextDev::Models::MonitorListChangesResponse::Data::MonitorsSitemapExactChangeSummary::target_type,
            title: String,
            url: String,
            tags: ::Array[String]
          }

          type change_detection_type = :exact

          module ChangeDetectionType
            extend ContextDev::Internal::Type::Enum

            EXACT: :exact

            def self?.values: -> ::Array[ContextDev::Models::MonitorListChangesResponse::Data::MonitorsSitemapExactChangeSummary::change_detection_type]
          end

          type target_type = :sitemap

          module TargetType
            extend ContextDev::Internal::Type::Enum

            SITEMAP: :sitemap

            def self?.values: -> ::Array[ContextDev::Models::MonitorListChangesResponse::Data::MonitorsSitemapExactChangeSummary::target_type]
          end
        end

        type monitors_page_semantic_change_summary =
          {
            id: String,
            change_detection_type: ContextDev::Models::MonitorListChangesResponse::Data::MonitorsPageSemanticChangeSummary::change_detection_type,
            confidence: Float,
            detected_at: Time,
            importance: ContextDev::Models::MonitorListChangesResponse::Data::MonitorsPageSemanticChangeSummary::importance,
            monitor_id: String,
            summary: String,
            target_type: ContextDev::Models::MonitorListChangesResponse::Data::MonitorsPageSemanticChangeSummary::target_type,
            title: String,
            url: String,
            tags: ::Array[String]
          }

        class MonitorsPageSemanticChangeSummary < ContextDev::Internal::Type::BaseModel
          attr_accessor id: String

          attr_accessor change_detection_type: ContextDev::Models::MonitorListChangesResponse::Data::MonitorsPageSemanticChangeSummary::change_detection_type

          attr_accessor confidence: Float

          attr_accessor detected_at: Time

          attr_accessor importance: ContextDev::Models::MonitorListChangesResponse::Data::MonitorsPageSemanticChangeSummary::importance

          attr_accessor monitor_id: String

          attr_accessor summary: String

          attr_accessor target_type: ContextDev::Models::MonitorListChangesResponse::Data::MonitorsPageSemanticChangeSummary::target_type

          attr_accessor title: String

          attr_accessor url: String

          attr_reader tags: ::Array[String]?

          def tags=: (::Array[String]) -> ::Array[String]

          def initialize: (
            id: String,
            change_detection_type: ContextDev::Models::MonitorListChangesResponse::Data::MonitorsPageSemanticChangeSummary::change_detection_type,
            confidence: Float,
            detected_at: Time,
            importance: ContextDev::Models::MonitorListChangesResponse::Data::MonitorsPageSemanticChangeSummary::importance,
            monitor_id: String,
            summary: String,
            target_type: ContextDev::Models::MonitorListChangesResponse::Data::MonitorsPageSemanticChangeSummary::target_type,
            title: String,
            url: String,
            ?tags: ::Array[String]
          ) -> void

          def to_hash: -> {
            id: String,
            change_detection_type: ContextDev::Models::MonitorListChangesResponse::Data::MonitorsPageSemanticChangeSummary::change_detection_type,
            confidence: Float,
            detected_at: Time,
            importance: ContextDev::Models::MonitorListChangesResponse::Data::MonitorsPageSemanticChangeSummary::importance,
            monitor_id: String,
            summary: String,
            target_type: ContextDev::Models::MonitorListChangesResponse::Data::MonitorsPageSemanticChangeSummary::target_type,
            title: String,
            url: String,
            tags: ::Array[String]
          }

          type change_detection_type = :semantic

          module ChangeDetectionType
            extend ContextDev::Internal::Type::Enum

            SEMANTIC: :semantic

            def self?.values: -> ::Array[ContextDev::Models::MonitorListChangesResponse::Data::MonitorsPageSemanticChangeSummary::change_detection_type]
          end

          type importance = :low | :medium | :high

          module Importance
            extend ContextDev::Internal::Type::Enum

            LOW: :low
            MEDIUM: :medium
            HIGH: :high

            def self?.values: -> ::Array[ContextDev::Models::MonitorListChangesResponse::Data::MonitorsPageSemanticChangeSummary::importance]
          end

          type target_type = :page

          module TargetType
            extend ContextDev::Internal::Type::Enum

            PAGE: :page

            def self?.values: -> ::Array[ContextDev::Models::MonitorListChangesResponse::Data::MonitorsPageSemanticChangeSummary::target_type]
          end
        end

        type monitors_extract_semantic_change_summary =
          {
            id: String,
            change_detection_type: ContextDev::Models::MonitorListChangesResponse::Data::MonitorsExtractSemanticChangeSummary::change_detection_type,
            confidence: Float,
            detected_at: Time,
            importance: ContextDev::Models::MonitorListChangesResponse::Data::MonitorsExtractSemanticChangeSummary::importance,
            matched_url_count: Integer,
            monitor_id: String,
            summary: String,
            target_type: ContextDev::Models::MonitorListChangesResponse::Data::MonitorsExtractSemanticChangeSummary::target_type,
            title: String,
            url: String,
            tags: ::Array[String]
          }

        class MonitorsExtractSemanticChangeSummary < ContextDev::Internal::Type::BaseModel
          attr_accessor id: String

          attr_accessor change_detection_type: ContextDev::Models::MonitorListChangesResponse::Data::MonitorsExtractSemanticChangeSummary::change_detection_type

          attr_accessor confidence: Float

          attr_accessor detected_at: Time

          attr_accessor importance: ContextDev::Models::MonitorListChangesResponse::Data::MonitorsExtractSemanticChangeSummary::importance

          attr_accessor matched_url_count: Integer

          attr_accessor monitor_id: String

          attr_accessor summary: String

          attr_accessor target_type: ContextDev::Models::MonitorListChangesResponse::Data::MonitorsExtractSemanticChangeSummary::target_type

          attr_accessor title: String

          attr_accessor url: String

          attr_reader tags: ::Array[String]?

          def tags=: (::Array[String]) -> ::Array[String]

          def initialize: (
            id: String,
            change_detection_type: ContextDev::Models::MonitorListChangesResponse::Data::MonitorsExtractSemanticChangeSummary::change_detection_type,
            confidence: Float,
            detected_at: Time,
            importance: ContextDev::Models::MonitorListChangesResponse::Data::MonitorsExtractSemanticChangeSummary::importance,
            matched_url_count: Integer,
            monitor_id: String,
            summary: String,
            target_type: ContextDev::Models::MonitorListChangesResponse::Data::MonitorsExtractSemanticChangeSummary::target_type,
            title: String,
            url: String,
            ?tags: ::Array[String]
          ) -> void

          def to_hash: -> {
            id: String,
            change_detection_type: ContextDev::Models::MonitorListChangesResponse::Data::MonitorsExtractSemanticChangeSummary::change_detection_type,
            confidence: Float,
            detected_at: Time,
            importance: ContextDev::Models::MonitorListChangesResponse::Data::MonitorsExtractSemanticChangeSummary::importance,
            matched_url_count: Integer,
            monitor_id: String,
            summary: String,
            target_type: ContextDev::Models::MonitorListChangesResponse::Data::MonitorsExtractSemanticChangeSummary::target_type,
            title: String,
            url: String,
            tags: ::Array[String]
          }

          type change_detection_type = :semantic

          module ChangeDetectionType
            extend ContextDev::Internal::Type::Enum

            SEMANTIC: :semantic

            def self?.values: -> ::Array[ContextDev::Models::MonitorListChangesResponse::Data::MonitorsExtractSemanticChangeSummary::change_detection_type]
          end

          type importance = :low | :medium | :high

          module Importance
            extend ContextDev::Internal::Type::Enum

            LOW: :low
            MEDIUM: :medium
            HIGH: :high

            def self?.values: -> ::Array[ContextDev::Models::MonitorListChangesResponse::Data::MonitorsExtractSemanticChangeSummary::importance]
          end

          type target_type = :extract

          module TargetType
            extend ContextDev::Internal::Type::Enum

            EXTRACT: :extract

            def self?.values: -> ::Array[ContextDev::Models::MonitorListChangesResponse::Data::MonitorsExtractSemanticChangeSummary::target_type]
          end
        end

        def self?.variants: -> ::Array[ContextDev::Models::MonitorListChangesResponse::data]
      end
    end
  end
end
