module ContextDev
  module Models
    type monitor_list_account_changes_params =
      {
        change_detection_type: ContextDev::Models::MonitorListAccountChangesParams::change_detection_type,
        cursor: String,
        limit: Integer,
        monitor_id: String,
        since: Time,
        tag: String,
        target_type: ContextDev::Models::MonitorListAccountChangesParams::target_type,
        until_: Time
      }
      & ContextDev::Internal::Type::request_parameters

    class MonitorListAccountChangesParams < ContextDev::Internal::Type::BaseModel
      extend ContextDev::Internal::Type::RequestParameters::Converter
      include ContextDev::Internal::Type::RequestParameters

      attr_reader change_detection_type: ContextDev::Models::MonitorListAccountChangesParams::change_detection_type?

      def change_detection_type=: (
        ContextDev::Models::MonitorListAccountChangesParams::change_detection_type
      ) -> ContextDev::Models::MonitorListAccountChangesParams::change_detection_type

      attr_reader cursor: String?

      def cursor=: (String) -> String

      attr_reader limit: Integer?

      def limit=: (Integer) -> Integer

      attr_reader monitor_id: String?

      def monitor_id=: (String) -> String

      attr_reader since: Time?

      def since=: (Time) -> Time

      attr_reader tag: String?

      def tag=: (String) -> String

      attr_reader target_type: ContextDev::Models::MonitorListAccountChangesParams::target_type?

      def target_type=: (
        ContextDev::Models::MonitorListAccountChangesParams::target_type
      ) -> ContextDev::Models::MonitorListAccountChangesParams::target_type

      attr_reader until_: Time?

      def until_=: (Time) -> Time

      def initialize: (
        ?change_detection_type: ContextDev::Models::MonitorListAccountChangesParams::change_detection_type,
        ?cursor: String,
        ?limit: Integer,
        ?monitor_id: String,
        ?since: Time,
        ?tag: String,
        ?target_type: ContextDev::Models::MonitorListAccountChangesParams::target_type,
        ?until_: Time,
        ?request_options: ContextDev::request_opts
      ) -> void

      def to_hash: -> {
        change_detection_type: ContextDev::Models::MonitorListAccountChangesParams::change_detection_type,
        cursor: String,
        limit: Integer,
        monitor_id: String,
        since: Time,
        tag: String,
        target_type: ContextDev::Models::MonitorListAccountChangesParams::target_type,
        until_: Time,
        request_options: ContextDev::RequestOptions
      }

      type change_detection_type = :exact | :semantic

      module ChangeDetectionType
        extend ContextDev::Internal::Type::Enum

        EXACT: :exact
        SEMANTIC: :semantic

        def self?.values: -> ::Array[ContextDev::Models::MonitorListAccountChangesParams::change_detection_type]
      end

      type target_type = :page | :sitemap | :extract

      module TargetType
        extend ContextDev::Internal::Type::Enum

        PAGE: :page
        SITEMAP: :sitemap
        EXTRACT: :extract

        def self?.values: -> ::Array[ContextDev::Models::MonitorListAccountChangesParams::target_type]
      end
    end
  end
end
