module ContextDev
  module Models
    type monitor_get_credit_usage_response =
      {
        data: ::Array[ContextDev::Models::MonitorGetCreditUsageResponse::Data],
        request_id: String,
        total_credits: Integer,
        key_metadata: ContextDev::Models::MonitorGetCreditUsageResponse::KeyMetadata
      }

    class MonitorGetCreditUsageResponse < ContextDev::Internal::Type::BaseModel
      attr_accessor data: ::Array[ContextDev::Models::MonitorGetCreditUsageResponse::Data]

      attr_accessor request_id: String

      attr_accessor total_credits: Integer

      attr_reader key_metadata: ContextDev::Models::MonitorGetCreditUsageResponse::KeyMetadata?

      def key_metadata=: (
        ContextDev::Models::MonitorGetCreditUsageResponse::KeyMetadata
      ) -> ContextDev::Models::MonitorGetCreditUsageResponse::KeyMetadata

      def initialize: (
        data: ::Array[ContextDev::Models::MonitorGetCreditUsageResponse::Data],
        request_id: String,
        total_credits: Integer,
        ?key_metadata: ContextDev::Models::MonitorGetCreditUsageResponse::KeyMetadata
      ) -> void

      def to_hash: -> {
        data: ::Array[ContextDev::Models::MonitorGetCreditUsageResponse::Data],
        request_id: String,
        total_credits: Integer,
        key_metadata: ContextDev::Models::MonitorGetCreditUsageResponse::KeyMetadata
      }

      type data =
        { credits: Integer, monitor_id: String, name: String, runs: Integer }

      class Data < ContextDev::Internal::Type::BaseModel
        attr_accessor credits: Integer

        attr_accessor monitor_id: String

        attr_accessor name: String

        attr_accessor runs: Integer

        def initialize: (
          credits: Integer,
          monitor_id: String,
          name: String,
          runs: Integer
        ) -> void

        def to_hash: -> {
          credits: Integer,
          monitor_id: String,
          name: String,
          runs: Integer
        }
      end

      type key_metadata =
        { credits_consumed: Integer, credits_remaining: Integer }

      class KeyMetadata < ContextDev::Internal::Type::BaseModel
        attr_accessor credits_consumed: Integer

        attr_accessor credits_remaining: Integer

        def initialize: (
          credits_consumed: Integer,
          credits_remaining: Integer
        ) -> void

        def to_hash: -> {
          credits_consumed: Integer,
          credits_remaining: Integer
        }
      end
    end
  end
end
