module ContextDev
  module Models
    type monitor_retrieve_params =
      { monitor_id: String } & ContextDev::Internal::Type::request_parameters

    class MonitorRetrieveParams < ContextDev::Internal::Type::BaseModel
      extend ContextDev::Internal::Type::RequestParameters::Converter
      include ContextDev::Internal::Type::RequestParameters

      attr_accessor monitor_id: String

      def initialize: (
        monitor_id: String,
        ?request_options: ContextDev::request_opts
      ) -> void

      def to_hash: -> {
        monitor_id: String,
        request_options: ContextDev::RequestOptions
      }
    end
  end
end
