module ContextDev
  module Models
    type monitor_retrieve_response =
      {
        id: String,
        change_detection: ContextDev::Models::MonitorRetrieveResponse::change_detection,
        created_at: Time,
        mode: ContextDev::Models::MonitorRetrieveResponse::mode,
        name: String,
        schedule: ContextDev::Models::MonitorRetrieveResponse::Schedule,
        status: ContextDev::Models::MonitorRetrieveResponse::status,
        target: ContextDev::Models::MonitorRetrieveResponse::target,
        updated_at: Time,
        baseline: ContextDev::Models::MonitorRetrieveResponse::baseline?,
        last_change_at: Time?,
        last_error: ContextDev::Models::MonitorRetrieveResponse::LastError?,
        last_run_at: Time?,
        next_run_at: Time?,
        tags: ::Array[String],
        webhook: ContextDev::Models::MonitorRetrieveResponse::Webhook?
      }

    class MonitorRetrieveResponse < ContextDev::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor change_detection: ContextDev::Models::MonitorRetrieveResponse::change_detection

      attr_accessor created_at: Time

      attr_accessor mode: ContextDev::Models::MonitorRetrieveResponse::mode

      attr_accessor name: String

      attr_accessor schedule: ContextDev::Models::MonitorRetrieveResponse::Schedule

      attr_accessor status: ContextDev::Models::MonitorRetrieveResponse::status

      attr_accessor target: ContextDev::Models::MonitorRetrieveResponse::target

      attr_accessor updated_at: Time

      attr_accessor baseline: ContextDev::Models::MonitorRetrieveResponse::baseline?

      attr_accessor last_change_at: Time?

      attr_accessor last_error: ContextDev::Models::MonitorRetrieveResponse::LastError?

      attr_accessor last_run_at: Time?

      attr_accessor next_run_at: Time?

      attr_reader tags: ::Array[String]?

      def tags=: (::Array[String]) -> ::Array[String]

      attr_accessor webhook: ContextDev::Models::MonitorRetrieveResponse::Webhook?

      def initialize: (
        id: String,
        change_detection: ContextDev::Models::MonitorRetrieveResponse::change_detection,
        created_at: Time,
        mode: ContextDev::Models::MonitorRetrieveResponse::mode,
        name: String,
        schedule: ContextDev::Models::MonitorRetrieveResponse::Schedule,
        status: ContextDev::Models::MonitorRetrieveResponse::status,
        target: ContextDev::Models::MonitorRetrieveResponse::target,
        updated_at: Time,
        ?baseline: ContextDev::Models::MonitorRetrieveResponse::baseline?,
        ?last_change_at: Time?,
        ?last_error: ContextDev::Models::MonitorRetrieveResponse::LastError?,
        ?last_run_at: Time?,
        ?next_run_at: Time?,
        ?tags: ::Array[String],
        ?webhook: ContextDev::Models::MonitorRetrieveResponse::Webhook?
      ) -> void

      def to_hash: -> {
        id: String,
        change_detection: ContextDev::Models::MonitorRetrieveResponse::change_detection,
        created_at: Time,
        mode: ContextDev::Models::MonitorRetrieveResponse::mode,
        name: String,
        schedule: ContextDev::Models::MonitorRetrieveResponse::Schedule,
        status: ContextDev::Models::MonitorRetrieveResponse::status,
        target: ContextDev::Models::MonitorRetrieveResponse::target,
        updated_at: Time,
        baseline: ContextDev::Models::MonitorRetrieveResponse::baseline?,
        last_change_at: Time?,
        last_error: ContextDev::Models::MonitorRetrieveResponse::LastError?,
        last_run_at: Time?,
        next_run_at: Time?,
        tags: ::Array[String],
        webhook: ContextDev::Models::MonitorRetrieveResponse::Webhook?
      }

      type change_detection =
        ContextDev::Models::MonitorRetrieveResponse::ChangeDetection::Exact
        | ContextDev::Models::MonitorRetrieveResponse::ChangeDetection::Semantic

      module ChangeDetection
        extend ContextDev::Internal::Type::Union

        type exact = { type: :exact }

        class Exact < ContextDev::Internal::Type::BaseModel
          attr_accessor type: :exact

          def initialize: (?type: :exact) -> void

          def to_hash: -> { type: :exact }
        end

        type semantic = { type: :semantic, confidence_threshold: Float }

        class Semantic < ContextDev::Internal::Type::BaseModel
          attr_accessor type: :semantic

          attr_reader confidence_threshold: Float?

          def confidence_threshold=: (Float) -> Float

          def initialize: (
            ?confidence_threshold: Float,
            ?type: :semantic
          ) -> void

          def to_hash: -> { type: :semantic, confidence_threshold: Float }
        end

        def self?.variants: -> ::Array[ContextDev::Models::MonitorRetrieveResponse::change_detection]
      end

      type mode = :web

      module Mode
        extend ContextDev::Internal::Type::Enum

        WEB: :web

        def self?.values: -> ::Array[ContextDev::Models::MonitorRetrieveResponse::mode]
      end

      type schedule =
        {
          frequency: Integer,
          type: ContextDev::Models::MonitorRetrieveResponse::Schedule::type_,
          unit: ContextDev::Models::MonitorRetrieveResponse::Schedule::unit
        }

      class Schedule < ContextDev::Internal::Type::BaseModel
        attr_accessor frequency: Integer

        attr_accessor type: ContextDev::Models::MonitorRetrieveResponse::Schedule::type_

        attr_accessor unit: ContextDev::Models::MonitorRetrieveResponse::Schedule::unit

        def initialize: (
          frequency: Integer,
          type: ContextDev::Models::MonitorRetrieveResponse::Schedule::type_,
          unit: ContextDev::Models::MonitorRetrieveResponse::Schedule::unit
        ) -> void

        def to_hash: -> {
          frequency: Integer,
          type: ContextDev::Models::MonitorRetrieveResponse::Schedule::type_,
          unit: ContextDev::Models::MonitorRetrieveResponse::Schedule::unit
        }

        type type_ = :interval

        module Type
          extend ContextDev::Internal::Type::Enum

          INTERVAL: :interval

          def self?.values: -> ::Array[ContextDev::Models::MonitorRetrieveResponse::Schedule::type_]
        end

        type unit = :minutes | :hours | :days

        module Unit
          extend ContextDev::Internal::Type::Enum

          MINUTES: :minutes
          HOURS: :hours
          DAYS: :days

          def self?.values: -> ::Array[ContextDev::Models::MonitorRetrieveResponse::Schedule::unit]
        end
      end

      type status = :active | :paused | :failed

      module Status
        extend ContextDev::Internal::Type::Enum

        ACTIVE: :active
        PAUSED: :paused
        FAILED: :failed

        def self?.values: -> ::Array[ContextDev::Models::MonitorRetrieveResponse::status]
      end

      type target =
        ContextDev::Models::MonitorRetrieveResponse::Target::Page
        | ContextDev::Models::MonitorRetrieveResponse::Target::Sitemap
        | ContextDev::Models::MonitorRetrieveResponse::Target::Extract

      module Target
        extend ContextDev::Internal::Type::Union

        type page = { type: :page, url: String, normalize_whitespace: bool }

        class Page < ContextDev::Internal::Type::BaseModel
          attr_accessor type: :page

          attr_accessor url: String

          attr_reader normalize_whitespace: bool?

          def normalize_whitespace=: (bool) -> bool

          def initialize: (
            url: String,
            ?normalize_whitespace: bool,
            ?type: :page
          ) -> void

          def to_hash: -> {
            type: :page,
            url: String,
            normalize_whitespace: bool
          }
        end

        type sitemap =
          {
            type: :sitemap,
            url: String,
            exclude: ::Array[String],
            include: ::Array[String],
            max_urls: Integer
          }

        class Sitemap < ContextDev::Internal::Type::BaseModel
          attr_accessor type: :sitemap

          attr_accessor url: String

          attr_reader exclude: ::Array[String]?

          def exclude=: (::Array[String]) -> ::Array[String]

          attr_reader include: ::Array[String]?

          def include=: (::Array[String]) -> ::Array[String]

          attr_reader max_urls: Integer?

          def max_urls=: (Integer) -> Integer

          def initialize: (
            url: String,
            ?exclude: ::Array[String],
            ?include: ::Array[String],
            ?max_urls: Integer,
            ?type: :sitemap
          ) -> void

          def to_hash: -> {
            type: :sitemap,
            url: String,
            exclude: ::Array[String],
            include: ::Array[String],
            max_urls: Integer
          }
        end

        type extract =
          {
            instructions: String,
            type: :extract,
            url: String,
            follow_subdomains: bool,
            max_depth: Integer,
            max_pages: Integer,
            schema: ::Hash[Symbol, top]
          }

        class Extract < ContextDev::Internal::Type::BaseModel
          attr_accessor instructions: String

          attr_accessor type: :extract

          attr_accessor url: String

          attr_reader follow_subdomains: bool?

          def follow_subdomains=: (bool) -> bool

          attr_reader max_depth: Integer?

          def max_depth=: (Integer) -> Integer

          attr_reader max_pages: Integer?

          def max_pages=: (Integer) -> Integer

          attr_reader schema: ::Hash[Symbol, top]?

          def schema=: (::Hash[Symbol, top]) -> ::Hash[Symbol, top]

          def initialize: (
            instructions: String,
            url: String,
            ?follow_subdomains: bool,
            ?max_depth: Integer,
            ?max_pages: Integer,
            ?schema: ::Hash[Symbol, top],
            ?type: :extract
          ) -> void

          def to_hash: -> {
            instructions: String,
            type: :extract,
            url: String,
            follow_subdomains: bool,
            max_depth: Integer,
            max_pages: Integer,
            schema: ::Hash[Symbol, top]
          }
        end

        def self?.variants: -> ::Array[ContextDev::Models::MonitorRetrieveResponse::target]
      end

      type baseline =
        ContextDev::Models::MonitorRetrieveResponse::Baseline::MonitorsPageBaseline
        | ContextDev::Models::MonitorRetrieveResponse::Baseline::MonitorsSitemapBaseline
        | ContextDev::Models::MonitorRetrieveResponse::Baseline::MonitorsExtractBaseline

      module Baseline
        extend ContextDev::Internal::Type::Union

        type monitors_page_baseline = { captured_at: Time, text: String }

        class MonitorsPageBaseline < ContextDev::Internal::Type::BaseModel
          attr_accessor captured_at: Time

          attr_accessor text: String

          def initialize: (captured_at: Time, text: String) -> void

          def to_hash: -> { captured_at: Time, text: String }
        end

        type monitors_sitemap_baseline =
          { captured_at: Time, url_count: Integer, urls: ::Array[String] }

        class MonitorsSitemapBaseline < ContextDev::Internal::Type::BaseModel
          attr_accessor captured_at: Time

          attr_accessor url_count: Integer

          attr_accessor urls: ::Array[String]

          def initialize: (
            captured_at: Time,
            url_count: Integer,
            urls: ::Array[String]
          ) -> void

          def to_hash: -> {
            captured_at: Time,
            url_count: Integer,
            urls: ::Array[String]
          }
        end

        type monitors_extract_baseline =
          { captured_at: Time, data: top, urls_analyzed: ::Array[String] }

        class MonitorsExtractBaseline < ContextDev::Internal::Type::BaseModel
          attr_accessor captured_at: Time

          attr_accessor data: top

          attr_accessor urls_analyzed: ::Array[String]

          def initialize: (
            captured_at: Time,
            data: top,
            urls_analyzed: ::Array[String]
          ) -> void

          def to_hash: -> {
            captured_at: Time,
            data: top,
            urls_analyzed: ::Array[String]
          }
        end

        def self?.variants: -> ::Array[ContextDev::Models::MonitorRetrieveResponse::baseline]
      end

      type last_error = { code: String, message: String }

      class LastError < ContextDev::Internal::Type::BaseModel
        attr_accessor code: String

        attr_accessor message: String

        def initialize: (code: String, message: String) -> void

        def to_hash: -> { code: String, message: String }
      end

      type webhook = { url: String, secret: String }

      class Webhook < ContextDev::Internal::Type::BaseModel
        attr_accessor url: String

        attr_reader secret: String?

        def secret=: (String) -> String

        def initialize: (url: String, ?secret: String) -> void

        def to_hash: -> { url: String, secret: String }
      end
    end
  end
end
