module ContextDev
  module Models
    type monitor_get_limits_params =
      {  } & ContextDev::Internal::Type::request_parameters

    class MonitorGetLimitsParams < ContextDev::Internal::Type::BaseModel
      extend ContextDev::Internal::Type::RequestParameters::Converter
      include ContextDev::Internal::Type::RequestParameters

      def initialize: (?request_options: ContextDev::request_opts) -> void

      def to_hash: -> { request_options: ContextDev::RequestOptions }
    end
  end
end
