module ContextDev
  module Models
    type news_search_params =
      {
        search_by: ContextDev::NewsSearchParams::SearchBy,
        cursor: String?,
        filter_by: ContextDev::NewsSearchParams::FilterBy,
        limit: Integer,
        sort_by: ContextDev::NewsSearchParams::SortBy,
        tags: ::Array[String]
      }
      & ContextDev::Internal::Type::request_parameters

    class NewsSearchParams < ContextDev::Internal::Type::BaseModel
      extend ContextDev::Internal::Type::RequestParameters::Converter
      include ContextDev::Internal::Type::RequestParameters

      attr_accessor search_by: ContextDev::NewsSearchParams::SearchBy

      attr_accessor cursor: String?

      attr_reader filter_by: ContextDev::NewsSearchParams::FilterBy?

      def filter_by=: (
        ContextDev::NewsSearchParams::FilterBy
      ) -> ContextDev::NewsSearchParams::FilterBy

      attr_reader limit: Integer?

      def limit=: (Integer) -> Integer

      attr_reader sort_by: ContextDev::NewsSearchParams::SortBy?

      def sort_by=: (
        ContextDev::NewsSearchParams::SortBy
      ) -> ContextDev::NewsSearchParams::SortBy

      attr_reader tags: ::Array[String]?

      def tags=: (::Array[String]) -> ::Array[String]

      def initialize: (
        search_by: ContextDev::NewsSearchParams::SearchBy,
        ?cursor: String?,
        ?filter_by: ContextDev::NewsSearchParams::FilterBy,
        ?limit: Integer,
        ?sort_by: ContextDev::NewsSearchParams::SortBy,
        ?tags: ::Array[String],
        ?request_options: ContextDev::request_opts
      ) -> void

      def to_hash: -> {
        search_by: ContextDev::NewsSearchParams::SearchBy,
        cursor: String?,
        filter_by: ContextDev::NewsSearchParams::FilterBy,
        limit: Integer,
        sort_by: ContextDev::NewsSearchParams::SortBy,
        tags: ::Array[String],
        request_options: ContextDev::RequestOptions
      }

      type search_by =
        {
          entity: ContextDev::Models::NewsSearchParams::SearchBy::entity,
          type: ContextDev::Models::NewsSearchParams::SearchBy::type_
        }

      class SearchBy < ContextDev::Internal::Type::BaseModel
        attr_accessor entity: ContextDev::Models::NewsSearchParams::SearchBy::entity

        attr_accessor type: ContextDev::Models::NewsSearchParams::SearchBy::type_

        def initialize: (
          entity: ContextDev::Models::NewsSearchParams::SearchBy::entity,
          type: ContextDev::Models::NewsSearchParams::SearchBy::type_
        ) -> void

        def to_hash: -> {
          entity: ContextDev::Models::NewsSearchParams::SearchBy::entity,
          type: ContextDev::Models::NewsSearchParams::SearchBy::type_
        }

        type entity =
          ContextDev::NewsSearchParams::SearchBy::Entity::Name
          | ContextDev::NewsSearchParams::SearchBy::Entity::Domain
          | ContextDev::NewsSearchParams::SearchBy::Entity::Ticker
          | ContextDev::NewsSearchParams::SearchBy::Entity::Isin

        module Entity
          extend ContextDev::Internal::Type::Union

          type name_ = { name: String, type: :name }

          class Name < ContextDev::Internal::Type::BaseModel
            attr_accessor name: String

            attr_accessor type: :name

            def initialize: (name: String, ?type: :name) -> void

            def to_hash: -> { name: String, type: :name }
          end

          type domain = { domain: String, type: :domain }

          class Domain < ContextDev::Internal::Type::BaseModel
            attr_accessor domain: String

            attr_accessor type: :domain

            def initialize: (domain: String, ?type: :domain) -> void

            def to_hash: -> { domain: String, type: :domain }
          end

          type ticker =
            {
              ticker: String,
              type: :ticker,
              exchange: ContextDev::Models::NewsSearchParams::SearchBy::Entity::Ticker::exchange
            }

          class Ticker < ContextDev::Internal::Type::BaseModel
            attr_accessor ticker: String

            attr_accessor type: :ticker

            attr_reader exchange: ContextDev::Models::NewsSearchParams::SearchBy::Entity::Ticker::exchange?

            def exchange=: (
              ContextDev::Models::NewsSearchParams::SearchBy::Entity::Ticker::exchange
            ) -> ContextDev::Models::NewsSearchParams::SearchBy::Entity::Ticker::exchange

            def initialize: (
              ticker: String,
              ?exchange: ContextDev::Models::NewsSearchParams::SearchBy::Entity::Ticker::exchange,
              ?type: :ticker
            ) -> void

            def to_hash: -> {
              ticker: String,
              type: :ticker,
              exchange: ContextDev::Models::NewsSearchParams::SearchBy::Entity::Ticker::exchange
            }

            type exchange =
              :AMEX
              | :AMS
              | :AQS
              | :ASX
              | :ATH
              | :BER
              | :BME
              | :BRU
              | :BSE
              | :BUD
              | :BUE
              | :BVC
              | :CBOE
              | :CNQ
              | :CPH
              | :DFM
              | :DOH
              | :DUB
              | :DUS
              | :DXE
              | :EGX
              | :FSX
              | :HAM
              | :HEL
              | :HKSE
              | :HOSE
              | :ICE
              | :IOB
              | :IST
              | :JKT
              | :JNB
              | :JPX
              | :KLS
              | :KOE
              | :KSC
              | :KUW
              | :LIS
              | :LSE
              | :MCX
              | :MEX
              | :MIL
              | :MUN
              | :NASDAQ
              | :NEO
              | :NSE
              | :NYSE
              | :NZE
              | :OSL
              | :OTC
              | :PAR
              | :PNK
              | :PRA
              | :RIS
              | :SAO
              | :SAU
              | :SES
              | :SET
              | :SGO
              | :SHH
              | :SHZ
              | :SIX
              | :STO
              | :STU
              | :TAI
              | :TAL
              | :TLV
              | :TSX
              | :TSXV
              | :TWO
              | :VIE
              | :WSE
              | :XETRA

            module Exchange
              extend ContextDev::Internal::Type::Enum

              AMEX: :AMEX
              AMS: :AMS
              AQS: :AQS
              ASX: :ASX
              ATH: :ATH
              BER: :BER
              BME: :BME
              BRU: :BRU
              BSE: :BSE
              BUD: :BUD
              BUE: :BUE
              BVC: :BVC
              CBOE: :CBOE
              CNQ: :CNQ
              CPH: :CPH
              DFM: :DFM
              DOH: :DOH
              DUB: :DUB
              DUS: :DUS
              DXE: :DXE
              EGX: :EGX
              FSX: :FSX
              HAM: :HAM
              HEL: :HEL
              HKSE: :HKSE
              HOSE: :HOSE
              ICE: :ICE
              IOB: :IOB
              IST: :IST
              JKT: :JKT
              JNB: :JNB
              JPX: :JPX
              KLS: :KLS
              KOE: :KOE
              KSC: :KSC
              KUW: :KUW
              LIS: :LIS
              LSE: :LSE
              MCX: :MCX
              MEX: :MEX
              MIL: :MIL
              MUN: :MUN
              NASDAQ: :NASDAQ
              NEO: :NEO
              NSE: :NSE
              NYSE: :NYSE
              NZE: :NZE
              OSL: :OSL
              OTC: :OTC
              PAR: :PAR
              PNK: :PNK
              PRA: :PRA
              RIS: :RIS
              SAO: :SAO
              SAU: :SAU
              SES: :SES
              SET: :SET
              SGO: :SGO
              SHH: :SHH
              SHZ: :SHZ
              SIX: :SIX
              STO: :STO
              STU: :STU
              TAI: :TAI
              TAL: :TAL
              TLV: :TLV
              TSX: :TSX
              TSXV: :TSXV
              TWO: :TWO
              VIE: :VIE
              WSE: :WSE
              XETRA: :XETRA

              def self?.values: -> ::Array[ContextDev::Models::NewsSearchParams::SearchBy::Entity::Ticker::exchange]
            end
          end

          type isin = { isin: String, type: :isin }

          class Isin < ContextDev::Internal::Type::BaseModel
            attr_accessor isin: String

            attr_accessor type: :isin

            def initialize: (isin: String, ?type: :isin) -> void

            def to_hash: -> { isin: String, type: :isin }
          end

          def self?.variants: -> ::Array[ContextDev::Models::NewsSearchParams::SearchBy::entity]
        end

        type type_ = :entity

        module Type
          extend ContextDev::Internal::Type::Enum

          ENTITY: :entity

          def self?.values: -> ::Array[ContextDev::Models::NewsSearchParams::SearchBy::type_]
        end
      end

      type filter_by =
        {
          article_language: ::Array[ContextDev::Models::NewsSearchParams::FilterBy::article_language],
          article_type: ::Array[ContextDev::Models::NewsSearchParams::FilterBy::article_type],
          date: ContextDev::NewsSearchParams::FilterBy::Date,
          source_country: ::Array[ContextDev::Models::NewsSearchParams::FilterBy::source_country],
          source_domain: ::Array[String]
        }

      class FilterBy < ContextDev::Internal::Type::BaseModel
        attr_reader article_language: ::Array[ContextDev::Models::NewsSearchParams::FilterBy::article_language]?

        def article_language=: (
          ::Array[ContextDev::Models::NewsSearchParams::FilterBy::article_language]
        ) -> ::Array[ContextDev::Models::NewsSearchParams::FilterBy::article_language]

        attr_reader article_type: ::Array[ContextDev::Models::NewsSearchParams::FilterBy::article_type]?

        def article_type=: (
          ::Array[ContextDev::Models::NewsSearchParams::FilterBy::article_type]
        ) -> ::Array[ContextDev::Models::NewsSearchParams::FilterBy::article_type]

        attr_reader date: ContextDev::NewsSearchParams::FilterBy::Date?

        def date=: (
          ContextDev::NewsSearchParams::FilterBy::Date
        ) -> ContextDev::NewsSearchParams::FilterBy::Date

        attr_reader source_country: ::Array[ContextDev::Models::NewsSearchParams::FilterBy::source_country]?

        def source_country=: (
          ::Array[ContextDev::Models::NewsSearchParams::FilterBy::source_country]
        ) -> ::Array[ContextDev::Models::NewsSearchParams::FilterBy::source_country]

        attr_reader source_domain: ::Array[String]?

        def source_domain=: (::Array[String]) -> ::Array[String]

        def initialize: (
          ?article_language: ::Array[ContextDev::Models::NewsSearchParams::FilterBy::article_language],
          ?article_type: ::Array[ContextDev::Models::NewsSearchParams::FilterBy::article_type],
          ?date: ContextDev::NewsSearchParams::FilterBy::Date,
          ?source_country: ::Array[ContextDev::Models::NewsSearchParams::FilterBy::source_country],
          ?source_domain: ::Array[String]
        ) -> void

        def to_hash: -> {
          article_language: ::Array[ContextDev::Models::NewsSearchParams::FilterBy::article_language],
          article_type: ::Array[ContextDev::Models::NewsSearchParams::FilterBy::article_type],
          date: ContextDev::NewsSearchParams::FilterBy::Date,
          source_country: ::Array[ContextDev::Models::NewsSearchParams::FilterBy::source_country],
          source_domain: ::Array[String]
        }

        type article_language =
          :ar
          | :de
          | :en
          | :es
          | :fr
          | :hi
          | :it
          | :ja
          | :ko
          | :nl
          | :pt
          | :ru
          | :zh

        module ArticleLanguage
          extend ContextDev::Internal::Type::Enum

          AR: :ar
          DE: :de
          EN: :en
          ES: :es
          FR: :fr
          HI: :hi
          IT: :it
          JA: :ja
          KO: :ko
          NL: :nl
          PT: :pt
          RU: :ru
          ZH: :zh

          def self?.values: -> ::Array[ContextDev::Models::NewsSearchParams::FilterBy::article_language]
        end

        type article_type =
          :editorial | :press_release | :regulatory_filing | :advisory

        module ArticleType
          extend ContextDev::Internal::Type::Enum

          EDITORIAL: :editorial
          PRESS_RELEASE: :press_release
          REGULATORY_FILING: :regulatory_filing
          ADVISORY: :advisory

          def self?.values: -> ::Array[ContextDev::Models::NewsSearchParams::FilterBy::article_type]
        end

        type date = { from: Integer, to: Integer }

        class Date < ContextDev::Internal::Type::BaseModel
          attr_reader from: Integer?

          def from=: (Integer) -> Integer

          attr_reader to: Integer?

          def to=: (Integer) -> Integer

          def initialize: (?from: Integer, ?to: Integer) -> void

          def to_hash: -> { from: Integer, to: Integer }
        end

        type source_country =
          :ae
          | :ar
          | :au
          | :ca
          | :cg
          | :ch
          | :cl
          | :cz
          | :de
          | :fi
          | :fr
          | :gb
          | :hk
          | :il
          | :in
          | :jp
          | :kr
          | :mx
          | :ng
          | :nl
          | :qa
          | :sa
          | :se
          | :sg
          | :us
          | :za

        module SourceCountry
          extend ContextDev::Internal::Type::Enum

          AE: :ae
          AR: :ar
          AU: :au
          CA: :ca
          CG: :cg
          CH: :ch
          CL: :cl
          CZ: :cz
          DE: :de
          FI: :fi
          FR: :fr
          GB: :gb
          HK: :hk
          IL: :il
          IN: :in
          JP: :jp
          KR: :kr
          MX: :mx
          NG: :ng
          NL: :nl
          QA: :qa
          SA: :sa
          SE: :se
          SG: :sg
          US: :us
          ZA: :za

          def self?.values: -> ::Array[ContextDev::Models::NewsSearchParams::FilterBy::source_country]
        end
      end

      type sort_by =
        { type: ContextDev::Models::NewsSearchParams::SortBy::type_ }

      class SortBy < ContextDev::Internal::Type::BaseModel
        attr_accessor type: ContextDev::Models::NewsSearchParams::SortBy::type_

        def initialize: (
          type: ContextDev::Models::NewsSearchParams::SortBy::type_
        ) -> void

        def to_hash: -> {
          type: ContextDev::Models::NewsSearchParams::SortBy::type_
        }

        type type_ = :relevance | :newest

        module Type
          extend ContextDev::Internal::Type::Enum

          RELEVANCE: :relevance
          NEWEST: :newest

          def self?.values: -> ::Array[ContextDev::Models::NewsSearchParams::SortBy::type_]
        end
      end
    end
  end
end
