module ContextDev
  module Models
    type page_error_count = { code: String, count: Integer }

    class PageErrorCount < ContextDev::Internal::Type::BaseModel
      attr_accessor code: String

      attr_accessor count: Integer

      def initialize: (code: String, count: Integer) -> void

      def to_hash: -> { code: String, count: Integer }
    end
  end
end
