module ContextDev
  module Models
    type parse_handle_params =
      {
        body: ContextDev::Internal::file_input,
        client: String,
        extension: ContextDev::Models::ParseHandleParams::extension,
        include_images: ContextDev::Models::ParseHandleParams::include_images,
        include_links: ContextDev::Models::ParseHandleParams::include_links,
        ocr: ContextDev::Models::ParseHandleParams::ocr,
        pdf: ContextDev::ParseHandleParams::Pdf,
        :shorten_base64_images => ContextDev::Models::ParseHandleParams::shorten_base64_images,
        tags: ::Array[String],
        use_main_content_only: ContextDev::Models::ParseHandleParams::use_main_content_only
      }
      & ContextDev::Internal::Type::request_parameters

    class ParseHandleParams < ContextDev::Internal::Type::BaseModel
      extend ContextDev::Internal::Type::RequestParameters::Converter
      include ContextDev::Internal::Type::RequestParameters

      attr_accessor body: ContextDev::Internal::file_input

      attr_reader client: String?

      def client=: (String) -> String

      attr_reader extension: ContextDev::Models::ParseHandleParams::extension?

      def extension=: (
        ContextDev::Models::ParseHandleParams::extension
      ) -> ContextDev::Models::ParseHandleParams::extension

      attr_reader include_images: ContextDev::Models::ParseHandleParams::include_images?

      def include_images=: (
        ContextDev::Models::ParseHandleParams::include_images
      ) -> ContextDev::Models::ParseHandleParams::include_images

      attr_reader include_links: ContextDev::Models::ParseHandleParams::include_links?

      def include_links=: (
        ContextDev::Models::ParseHandleParams::include_links
      ) -> ContextDev::Models::ParseHandleParams::include_links

      attr_reader ocr: ContextDev::Models::ParseHandleParams::ocr?

      def ocr=: (
        ContextDev::Models::ParseHandleParams::ocr
      ) -> ContextDev::Models::ParseHandleParams::ocr

      attr_reader pdf: ContextDev::ParseHandleParams::Pdf?

      def pdf=: (
        ContextDev::ParseHandleParams::Pdf
      ) -> ContextDev::ParseHandleParams::Pdf

      attr_reader shorten_base64_images: ContextDev::Models::ParseHandleParams::shorten_base64_images?

      def shorten_base64_images=: (
        ContextDev::Models::ParseHandleParams::shorten_base64_images
      ) -> ContextDev::Models::ParseHandleParams::shorten_base64_images

      attr_reader tags: ::Array[String]?

      def tags=: (::Array[String]) -> ::Array[String]

      attr_reader use_main_content_only: ContextDev::Models::ParseHandleParams::use_main_content_only?

      def use_main_content_only=: (
        ContextDev::Models::ParseHandleParams::use_main_content_only
      ) -> ContextDev::Models::ParseHandleParams::use_main_content_only

      def initialize: (
        body: ContextDev::Internal::file_input,
        ?client: String,
        ?extension: ContextDev::Models::ParseHandleParams::extension,
        ?include_images: ContextDev::Models::ParseHandleParams::include_images,
        ?include_links: ContextDev::Models::ParseHandleParams::include_links,
        ?ocr: ContextDev::Models::ParseHandleParams::ocr,
        ?pdf: ContextDev::ParseHandleParams::Pdf,
        ?shorten_base64_images: ContextDev::Models::ParseHandleParams::shorten_base64_images,
        ?tags: ::Array[String],
        ?use_main_content_only: ContextDev::Models::ParseHandleParams::use_main_content_only,
        ?request_options: ContextDev::request_opts
      ) -> void

      def to_hash: -> {
        body: ContextDev::Internal::file_input,
        client: String,
        extension: ContextDev::Models::ParseHandleParams::extension,
        include_images: ContextDev::Models::ParseHandleParams::include_images,
        include_links: ContextDev::Models::ParseHandleParams::include_links,
        ocr: ContextDev::Models::ParseHandleParams::ocr,
        pdf: ContextDev::ParseHandleParams::Pdf,
        :shorten_base64_images => ContextDev::Models::ParseHandleParams::shorten_base64_images,
        tags: ::Array[String],
        use_main_content_only: ContextDev::Models::ParseHandleParams::use_main_content_only,
        request_options: ContextDev::RequestOptions
      }

      type extension =
        :txt
        | :text
        | :md
        | :markdown
        | :html
        | :htm
        | :xhtml
        | :xml
        | :rss
        | :atom
        | :csv
        | :tsv
        | :yaml
        | :yml
        | :py
        | :java
        | :js
        | :jsx
        | :mjs
        | :cjs
        | :json
        | :jsonl
        | :ndjson
        | :php
        | :sh
        | :bash
        | :zsh
        | :fish
        | :rb
        | :ts
        | :tsx
        | :rtf
        | :srt
        | :css
        | :scss
        | :less
        | :styl
        | :sass
        | :svg
        | :pdf
        | :docx
        | :doc
        | :xlsx
        | :xlsm
        | :xlsb
        | :xltx
        | :xltm
        | :xls
        | :pptx
        | :pptm
        | :ppsx
        | :ppsm
        | :potx
        | :potm
        | :ppt
        | :pps
        | :pot
        | :jpg
        | :jpeg
        | :jpe
        | :png
        | :gif
        | :bmp
        | :tiff
        | :tif
        | :webp
        | :ppm
        | :pbm
        | :pgm
        | :pnm

      module Extension
        extend ContextDev::Internal::Type::Enum

        TXT: :txt
        TEXT: :text
        MD: :md
        MARKDOWN: :markdown
        HTML: :html
        HTM: :htm
        XHTML: :xhtml
        XML: :xml
        RSS: :rss
        ATOM: :atom
        CSV: :csv
        TSV: :tsv
        YAML: :yaml
        YML: :yml
        PY: :py
        JAVA: :java
        JS: :js
        JSX: :jsx
        MJS: :mjs
        CJS: :cjs
        JSON: :json
        JSONL: :jsonl
        NDJSON: :ndjson
        PHP: :php
        SH: :sh
        BASH: :bash
        ZSH: :zsh
        FISH: :fish
        RB: :rb
        TS: :ts
        TSX: :tsx
        RTF: :rtf
        SRT: :srt
        CSS: :css
        SCSS: :scss
        LESS: :less
        STYL: :styl
        SASS: :sass
        SVG: :svg
        PDF: :pdf
        DOCX: :docx
        DOC: :doc
        XLSX: :xlsx
        XLSM: :xlsm
        XLSB: :xlsb
        XLTX: :xltx
        XLTM: :xltm
        XLS: :xls
        PPTX: :pptx
        PPTM: :pptm
        PPSX: :ppsx
        PPSM: :ppsm
        POTX: :potx
        POTM: :potm
        PPT: :ppt
        PPS: :pps
        POT: :pot
        JPG: :jpg
        JPEG: :jpeg
        JPE: :jpe
        PNG: :png
        GIF: :gif
        BMP: :bmp
        TIFF: :tiff
        TIF: :tif
        WEBP: :webp
        PPM: :ppm
        PBM: :pbm
        PGM: :pgm
        PNM: :pnm

        def self?.values: -> ::Array[ContextDev::Models::ParseHandleParams::extension]
      end

      type include_images = bool | :true | :false

      module IncludeImages
        extend ContextDev::Internal::Type::Union

        def self?.variants: -> ::Array[ContextDev::Models::ParseHandleParams::include_images]

        TRUE: :true
        FALSE: :false
      end

      type include_links = bool | :true | :false

      module IncludeLinks
        extend ContextDev::Internal::Type::Union

        def self?.variants: -> ::Array[ContextDev::Models::ParseHandleParams::include_links]

        TRUE: :true
        FALSE: :false
      end

      type ocr = bool | :true | :false

      module Ocr
        extend ContextDev::Internal::Type::Union

        def self?.variants: -> ::Array[ContextDev::Models::ParseHandleParams::ocr]

        TRUE: :true
        FALSE: :false
      end

      type pdf = { end_: Integer, start: Integer }

      class Pdf < ContextDev::Internal::Type::BaseModel
        attr_reader end_: Integer?

        def end_=: (Integer) -> Integer

        attr_reader start: Integer?

        def start=: (Integer) -> Integer

        def initialize: (?end_: Integer, ?start: Integer) -> void

        def to_hash: -> { end_: Integer, start: Integer }
      end

      type shorten_base64_images = bool | :true | :false

      module ShortenBase64Images
        extend ContextDev::Internal::Type::Union

        def self?.variants: -> ::Array[ContextDev::Models::ParseHandleParams::shorten_base64_images]

        TRUE: :true
        FALSE: :false
      end

      type use_main_content_only = bool | :true | :false

      module UseMainContentOnly
        extend ContextDev::Internal::Type::Union

        def self?.variants: -> ::Array[ContextDev::Models::ParseHandleParams::use_main_content_only]

        TRUE: :true
        FALSE: :false
      end
    end
  end
end
