module ContextDev
  module Models
    type utility_prefetch_params =
      {
        identifier: ContextDev::Models::UtilityPrefetchParams::identifier,
        type: ContextDev::Models::UtilityPrefetchParams::type_,
        tags: ::Array[String],
        timeout_opts: ContextDev::UtilityPrefetchParams::TimeoutOpts
      }
      & ContextDev::Internal::Type::request_parameters

    class UtilityPrefetchParams < ContextDev::Internal::Type::BaseModel
      extend ContextDev::Internal::Type::RequestParameters::Converter
      include ContextDev::Internal::Type::RequestParameters

      attr_accessor identifier: ContextDev::Models::UtilityPrefetchParams::identifier

      attr_accessor type: ContextDev::Models::UtilityPrefetchParams::type_

      attr_reader tags: ::Array[String]?

      def tags=: (::Array[String]) -> ::Array[String]

      attr_reader timeout_opts: ContextDev::UtilityPrefetchParams::TimeoutOpts?

      def timeout_opts=: (
        ContextDev::UtilityPrefetchParams::TimeoutOpts
      ) -> ContextDev::UtilityPrefetchParams::TimeoutOpts

      def initialize: (
        identifier: ContextDev::Models::UtilityPrefetchParams::identifier,
        type: ContextDev::Models::UtilityPrefetchParams::type_,
        ?tags: ::Array[String],
        ?timeout_opts: ContextDev::UtilityPrefetchParams::TimeoutOpts,
        ?request_options: ContextDev::request_opts
      ) -> void

      def to_hash: -> {
        identifier: ContextDev::Models::UtilityPrefetchParams::identifier,
        type: ContextDev::Models::UtilityPrefetchParams::type_,
        tags: ::Array[String],
        timeout_opts: ContextDev::UtilityPrefetchParams::TimeoutOpts,
        request_options: ContextDev::RequestOptions
      }

      type identifier =
        ContextDev::UtilityPrefetchParams::Identifier::UtilityPrefetchDomainIdentifier
        | ContextDev::UtilityPrefetchParams::Identifier::UtilityPrefetchEmailIdentifier

      module Identifier
        extend ContextDev::Internal::Type::Union

        type utility_prefetch_domain_identifier = { domain: String }

        class UtilityPrefetchDomainIdentifier < ContextDev::Internal::Type::BaseModel
          attr_accessor domain: String

          def initialize: (domain: String) -> void

          def to_hash: -> { domain: String }
        end

        type utility_prefetch_email_identifier = { email: String }

        class UtilityPrefetchEmailIdentifier < ContextDev::Internal::Type::BaseModel
          attr_accessor email: String

          def initialize: (email: String) -> void

          def to_hash: -> { email: String }
        end

        def self?.variants: -> ::Array[ContextDev::Models::UtilityPrefetchParams::identifier]
      end

      type type_ = :brand | :styleguide

      module Type
        extend ContextDev::Internal::Type::Enum

        BRAND: :brand
        STYLEGUIDE: :styleguide

        def self?.values: -> ::Array[ContextDev::Models::UtilityPrefetchParams::type_]
      end

      type timeout_opts =
        {
          milliseconds: Integer,
          behavior: ContextDev::Models::UtilityPrefetchParams::TimeoutOpts::behavior
        }

      class TimeoutOpts < ContextDev::Internal::Type::BaseModel
        attr_accessor milliseconds: Integer

        attr_reader behavior: ContextDev::Models::UtilityPrefetchParams::TimeoutOpts::behavior?

        def behavior=: (
          ContextDev::Models::UtilityPrefetchParams::TimeoutOpts::behavior
        ) -> ContextDev::Models::UtilityPrefetchParams::TimeoutOpts::behavior

        def initialize: (
          milliseconds: Integer,
          ?behavior: ContextDev::Models::UtilityPrefetchParams::TimeoutOpts::behavior
        ) -> void

        def to_hash: -> {
          milliseconds: Integer,
          behavior: ContextDev::Models::UtilityPrefetchParams::TimeoutOpts::behavior
        }

        type behavior = :fail

        module Behavior
          extend ContextDev::Internal::Type::Enum

          FAIL: :fail

          def self?.values: -> ::Array[ContextDev::Models::UtilityPrefetchParams::TimeoutOpts::behavior]
        end
      end
    end
  end
end
