module ContextDev
  module Models
    type utility_prefetch_params =
      {
        identifier: ContextDev::UtilityPrefetchParams::Identifier,
        type: ContextDev::Models::UtilityPrefetchParams::type_,
        timeout_ms: Integer
      }
      & ContextDev::Internal::Type::request_parameters

    class UtilityPrefetchParams < ContextDev::Internal::Type::BaseModel
      extend ContextDev::Internal::Type::RequestParameters::Converter
      include ContextDev::Internal::Type::RequestParameters

      attr_accessor identifier: ContextDev::UtilityPrefetchParams::Identifier

      attr_accessor type: ContextDev::Models::UtilityPrefetchParams::type_

      attr_reader timeout_ms: Integer?

      def timeout_ms=: (Integer) -> Integer

      def initialize: (
        identifier: ContextDev::UtilityPrefetchParams::Identifier,
        type: ContextDev::Models::UtilityPrefetchParams::type_,
        ?timeout_ms: Integer,
        ?request_options: ContextDev::request_opts
      ) -> void

      def to_hash: -> {
        identifier: ContextDev::UtilityPrefetchParams::Identifier,
        type: ContextDev::Models::UtilityPrefetchParams::type_,
        timeout_ms: Integer,
        request_options: ContextDev::RequestOptions
      }

      type identifier = { domain: String, email: String }

      class Identifier < ContextDev::Internal::Type::BaseModel
        attr_reader domain: String?

        def domain=: (String) -> String

        attr_reader email: String?

        def email=: (String) -> String

        def initialize: (?domain: String, ?email: String) -> void

        def to_hash: -> { domain: String, email: String }
      end

      type type_ = :brand

      module Type
        extend ContextDev::Internal::Type::Enum

        BRAND: :brand

        def self?.values: -> ::Array[ContextDev::Models::UtilityPrefetchParams::type_]
      end
    end
  end
end
