module ContextDev
  module Models
    type utility_prefetch_by_email_response =
      {
        domain: String,
        key_metadata: ContextDev::Models::UtilityPrefetchByEmailResponse::KeyMetadata,
        message: String,
        status: String
      }

    class UtilityPrefetchByEmailResponse < ContextDev::Internal::Type::BaseModel
      attr_reader domain: String?

      def domain=: (String) -> String

      attr_reader key_metadata: ContextDev::Models::UtilityPrefetchByEmailResponse::KeyMetadata?

      def key_metadata=: (
        ContextDev::Models::UtilityPrefetchByEmailResponse::KeyMetadata
      ) -> ContextDev::Models::UtilityPrefetchByEmailResponse::KeyMetadata

      attr_reader message: String?

      def message=: (String) -> String

      attr_reader status: String?

      def status=: (String) -> String

      def initialize: (
        ?domain: String,
        ?key_metadata: ContextDev::Models::UtilityPrefetchByEmailResponse::KeyMetadata,
        ?message: String,
        ?status: String
      ) -> void

      def to_hash: -> {
        domain: String,
        key_metadata: ContextDev::Models::UtilityPrefetchByEmailResponse::KeyMetadata,
        message: String,
        status: String
      }

      type key_metadata =
        { credits_consumed: Integer, credits_remaining: Integer }

      class KeyMetadata < ContextDev::Internal::Type::BaseModel
        attr_accessor credits_consumed: Integer

        attr_accessor credits_remaining: Integer

        def initialize: (
          credits_consumed: Integer,
          credits_remaining: Integer
        ) -> void

        def to_hash: -> {
          credits_consumed: Integer,
          credits_remaining: Integer
        }
      end
    end
  end
end
