module ContextDev
  module Models
    type utility_prefetch_response =
      {
        domain: String,
        key_metadata: ContextDev::Models::UtilityPrefetchResponse::KeyMetadata,
        message: String,
        status: String,
        type: ContextDev::Models::UtilityPrefetchResponse::type_
      }

    class UtilityPrefetchResponse < ContextDev::Internal::Type::BaseModel
      attr_reader domain: String?

      def domain=: (String) -> String

      attr_reader key_metadata: ContextDev::Models::UtilityPrefetchResponse::KeyMetadata?

      def key_metadata=: (
        ContextDev::Models::UtilityPrefetchResponse::KeyMetadata
      ) -> ContextDev::Models::UtilityPrefetchResponse::KeyMetadata

      attr_reader message: String?

      def message=: (String) -> String

      attr_reader status: String?

      def status=: (String) -> String

      attr_reader type: ContextDev::Models::UtilityPrefetchResponse::type_?

      def type=: (
        ContextDev::Models::UtilityPrefetchResponse::type_
      ) -> ContextDev::Models::UtilityPrefetchResponse::type_

      def initialize: (
        ?domain: String,
        ?key_metadata: ContextDev::Models::UtilityPrefetchResponse::KeyMetadata,
        ?message: String,
        ?status: String,
        ?type: ContextDev::Models::UtilityPrefetchResponse::type_
      ) -> void

      def to_hash: -> {
        domain: String,
        key_metadata: ContextDev::Models::UtilityPrefetchResponse::KeyMetadata,
        message: String,
        status: String,
        type: ContextDev::Models::UtilityPrefetchResponse::type_
      }

      type key_metadata =
        { credits_consumed: Integer, credits_remaining: Integer }

      class KeyMetadata < ContextDev::Internal::Type::BaseModel
        attr_accessor credits_consumed: Integer

        attr_accessor credits_remaining: Integer

        def initialize: (
          credits_consumed: Integer,
          credits_remaining: Integer
        ) -> void

        def to_hash: -> {
          credits_consumed: Integer,
          credits_remaining: Integer
        }
      end

      type type_ = :brand | :styleguide

      module Type
        extend ContextDev::Internal::Type::Enum

        BRAND: :brand
        STYLEGUIDE: :styleguide

        def self?.values: -> ::Array[ContextDev::Models::UtilityPrefetchResponse::type_]
      end
    end
  end
end
