module ContextDev
  module Models
    type web_answers_params =
      {
        task: String,
        json_format: ::Hash[Symbol, top],
        mode: ContextDev::Models::WebAnswersParams::mode,
        tags: ::Array[String],
        timeout_opts: ContextDev::WebAnswersParams::TimeoutOpts,
        zdr: ContextDev::Models::WebAnswersParams::zdr
      }
      & ContextDev::Internal::Type::request_parameters

    class WebAnswersParams < ContextDev::Internal::Type::BaseModel
      extend ContextDev::Internal::Type::RequestParameters::Converter
      include ContextDev::Internal::Type::RequestParameters

      attr_accessor task: String

      attr_reader json_format: ::Hash[Symbol, top]?

      def json_format=: (::Hash[Symbol, top]) -> ::Hash[Symbol, top]

      attr_reader mode: ContextDev::Models::WebAnswersParams::mode?

      def mode=: (
        ContextDev::Models::WebAnswersParams::mode
      ) -> ContextDev::Models::WebAnswersParams::mode

      attr_reader tags: ::Array[String]?

      def tags=: (::Array[String]) -> ::Array[String]

      attr_reader timeout_opts: ContextDev::WebAnswersParams::TimeoutOpts?

      def timeout_opts=: (
        ContextDev::WebAnswersParams::TimeoutOpts
      ) -> ContextDev::WebAnswersParams::TimeoutOpts

      attr_reader zdr: ContextDev::Models::WebAnswersParams::zdr?

      def zdr=: (
        ContextDev::Models::WebAnswersParams::zdr
      ) -> ContextDev::Models::WebAnswersParams::zdr

      def initialize: (
        task: String,
        ?json_format: ::Hash[Symbol, top],
        ?mode: ContextDev::Models::WebAnswersParams::mode,
        ?tags: ::Array[String],
        ?timeout_opts: ContextDev::WebAnswersParams::TimeoutOpts,
        ?zdr: ContextDev::Models::WebAnswersParams::zdr,
        ?request_options: ContextDev::request_opts
      ) -> void

      def to_hash: -> {
        task: String,
        json_format: ::Hash[Symbol, top],
        mode: ContextDev::Models::WebAnswersParams::mode,
        tags: ::Array[String],
        timeout_opts: ContextDev::WebAnswersParams::TimeoutOpts,
        zdr: ContextDev::Models::WebAnswersParams::zdr,
        request_options: ContextDev::RequestOptions
      }

      type mode = :fast | :ultra

      module Mode
        extend ContextDev::Internal::Type::Enum

        FAST: :fast
        ULTRA: :ultra

        def self?.values: -> ::Array[ContextDev::Models::WebAnswersParams::mode]
      end

      type timeout_opts =
        {
          milliseconds: Integer,
          behavior: ContextDev::Models::WebAnswersParams::TimeoutOpts::behavior
        }

      class TimeoutOpts < ContextDev::Internal::Type::BaseModel
        attr_accessor milliseconds: Integer

        attr_reader behavior: ContextDev::Models::WebAnswersParams::TimeoutOpts::behavior?

        def behavior=: (
          ContextDev::Models::WebAnswersParams::TimeoutOpts::behavior
        ) -> ContextDev::Models::WebAnswersParams::TimeoutOpts::behavior

        def initialize: (
          milliseconds: Integer,
          ?behavior: ContextDev::Models::WebAnswersParams::TimeoutOpts::behavior
        ) -> void

        def to_hash: -> {
          milliseconds: Integer,
          behavior: ContextDev::Models::WebAnswersParams::TimeoutOpts::behavior
        }

        type behavior = :fail | :"return-partial"

        module Behavior
          extend ContextDev::Internal::Type::Enum

          FAIL: :fail
          RETURN_PARTIAL: :"return-partial"

          def self?.values: -> ::Array[ContextDev::Models::WebAnswersParams::TimeoutOpts::behavior]
        end
      end

      type zdr = :enabled | :disabled

      module Zdr
        extend ContextDev::Internal::Type::Enum

        ENABLED: :enabled
        DISABLED: :disabled

        def self?.values: -> ::Array[ContextDev::Models::WebAnswersParams::zdr]
      end
    end
  end
end
