module ContextDev
  module Models
    type web_web_crawl_md_response =
      {
        metadata: ContextDev::Models::WebWebCrawlMdResponse::Metadata,
        results: ::Array[ContextDev::Models::WebWebCrawlMdResponse::Result],
        key_metadata: ContextDev::Models::WebWebCrawlMdResponse::KeyMetadata
      }

    class WebWebCrawlMdResponse < ContextDev::Internal::Type::BaseModel
      attr_accessor metadata: ContextDev::Models::WebWebCrawlMdResponse::Metadata

      attr_accessor results: ::Array[ContextDev::Models::WebWebCrawlMdResponse::Result]

      attr_reader key_metadata: ContextDev::Models::WebWebCrawlMdResponse::KeyMetadata?

      def key_metadata=: (
        ContextDev::Models::WebWebCrawlMdResponse::KeyMetadata
      ) -> ContextDev::Models::WebWebCrawlMdResponse::KeyMetadata

      def initialize: (
        metadata: ContextDev::Models::WebWebCrawlMdResponse::Metadata,
        results: ::Array[ContextDev::Models::WebWebCrawlMdResponse::Result],
        ?key_metadata: ContextDev::Models::WebWebCrawlMdResponse::KeyMetadata
      ) -> void

      def to_hash: -> {
        metadata: ContextDev::Models::WebWebCrawlMdResponse::Metadata,
        results: ::Array[ContextDev::Models::WebWebCrawlMdResponse::Result],
        key_metadata: ContextDev::Models::WebWebCrawlMdResponse::KeyMetadata
      }

      type metadata =
        {
          max_crawl_depth: Integer,
          num_failed: Integer,
          num_skipped: Integer,
          num_succeeded: Integer,
          num_urls: Integer
        }

      class Metadata < ContextDev::Internal::Type::BaseModel
        attr_accessor max_crawl_depth: Integer

        attr_accessor num_failed: Integer

        attr_accessor num_skipped: Integer

        attr_accessor num_succeeded: Integer

        attr_accessor num_urls: Integer

        def initialize: (
          max_crawl_depth: Integer,
          num_failed: Integer,
          num_skipped: Integer,
          num_succeeded: Integer,
          num_urls: Integer
        ) -> void

        def to_hash: -> {
          max_crawl_depth: Integer,
          num_failed: Integer,
          num_skipped: Integer,
          num_succeeded: Integer,
          num_urls: Integer
        }
      end

      type result =
        {
          markdown: String,
          metadata: ContextDev::Models::WebWebCrawlMdResponse::Result::Metadata
        }

      class Result < ContextDev::Internal::Type::BaseModel
        attr_accessor markdown: String

        attr_accessor metadata: ContextDev::Models::WebWebCrawlMdResponse::Result::Metadata

        def initialize: (
          markdown: String,
          metadata: ContextDev::Models::WebWebCrawlMdResponse::Result::Metadata
        ) -> void

        def to_hash: -> {
          markdown: String,
          metadata: ContextDev::Models::WebWebCrawlMdResponse::Result::Metadata
        }

        type metadata =
          {
            crawl_depth: Integer,
            final_url: String,
            source_url: String,
            status_code: Integer,
            success: bool,
            title: String,
            url: String,
            additional_meta: ::Hash[Symbol, ContextDev::Models::WebWebCrawlMdResponse::Result::Metadata::additional_meta],
            alternates: ::Array[ContextDev::Models::WebWebCrawlMdResponse::Result::Metadata::Alternate],
            author: String,
            canonical_url: String,
            description: String,
            favicon: String,
            headings: ::Array[ContextDev::Models::WebWebCrawlMdResponse::Result::Metadata::Heading],
            image: String,
            json_ld: ::Array[::Hash[Symbol, top]],
            keywords: ::Array[String],
            language: String,
            modified_time: String,
            open_graph: ::Hash[Symbol, ContextDev::Models::WebWebCrawlMdResponse::Result::Metadata::open_graph],
            published_time: String,
            robots: String,
            site_name: String,
            twitter: ::Hash[Symbol, ContextDev::Models::WebWebCrawlMdResponse::Result::Metadata::twitter]
          }

        class Metadata < ContextDev::Internal::Type::BaseModel
          attr_accessor crawl_depth: Integer

          attr_accessor final_url: String

          attr_accessor source_url: String

          attr_accessor status_code: Integer

          attr_accessor success: bool

          attr_accessor title: String

          attr_accessor url: String

          attr_reader additional_meta: ::Hash[Symbol, ContextDev::Models::WebWebCrawlMdResponse::Result::Metadata::additional_meta]?

          def additional_meta=: (
            ::Hash[Symbol, ContextDev::Models::WebWebCrawlMdResponse::Result::Metadata::additional_meta]
          ) -> ::Hash[Symbol, ContextDev::Models::WebWebCrawlMdResponse::Result::Metadata::additional_meta]

          attr_reader alternates: ::Array[ContextDev::Models::WebWebCrawlMdResponse::Result::Metadata::Alternate]?

          def alternates=: (
            ::Array[ContextDev::Models::WebWebCrawlMdResponse::Result::Metadata::Alternate]
          ) -> ::Array[ContextDev::Models::WebWebCrawlMdResponse::Result::Metadata::Alternate]

          attr_reader author: String?

          def author=: (String) -> String

          attr_reader canonical_url: String?

          def canonical_url=: (String) -> String

          attr_reader description: String?

          def description=: (String) -> String

          attr_reader favicon: String?

          def favicon=: (String) -> String

          attr_reader headings: ::Array[ContextDev::Models::WebWebCrawlMdResponse::Result::Metadata::Heading]?

          def headings=: (
            ::Array[ContextDev::Models::WebWebCrawlMdResponse::Result::Metadata::Heading]
          ) -> ::Array[ContextDev::Models::WebWebCrawlMdResponse::Result::Metadata::Heading]

          attr_reader image: String?

          def image=: (String) -> String

          attr_reader json_ld: ::Array[::Hash[Symbol, top]]?

          def json_ld=: (
            ::Array[::Hash[Symbol, top]]
          ) -> ::Array[::Hash[Symbol, top]]

          attr_reader keywords: ::Array[String]?

          def keywords=: (::Array[String]) -> ::Array[String]

          attr_reader language: String?

          def language=: (String) -> String

          attr_reader modified_time: String?

          def modified_time=: (String) -> String

          attr_reader open_graph: ::Hash[Symbol, ContextDev::Models::WebWebCrawlMdResponse::Result::Metadata::open_graph]?

          def open_graph=: (
            ::Hash[Symbol, ContextDev::Models::WebWebCrawlMdResponse::Result::Metadata::open_graph]
          ) -> ::Hash[Symbol, ContextDev::Models::WebWebCrawlMdResponse::Result::Metadata::open_graph]

          attr_reader published_time: String?

          def published_time=: (String) -> String

          attr_reader robots: String?

          def robots=: (String) -> String

          attr_reader site_name: String?

          def site_name=: (String) -> String

          attr_reader twitter: ::Hash[Symbol, ContextDev::Models::WebWebCrawlMdResponse::Result::Metadata::twitter]?

          def twitter=: (
            ::Hash[Symbol, ContextDev::Models::WebWebCrawlMdResponse::Result::Metadata::twitter]
          ) -> ::Hash[Symbol, ContextDev::Models::WebWebCrawlMdResponse::Result::Metadata::twitter]

          def initialize: (
            crawl_depth: Integer,
            final_url: String,
            source_url: String,
            status_code: Integer,
            success: bool,
            title: String,
            url: String,
            ?additional_meta: ::Hash[Symbol, ContextDev::Models::WebWebCrawlMdResponse::Result::Metadata::additional_meta],
            ?alternates: ::Array[ContextDev::Models::WebWebCrawlMdResponse::Result::Metadata::Alternate],
            ?author: String,
            ?canonical_url: String,
            ?description: String,
            ?favicon: String,
            ?headings: ::Array[ContextDev::Models::WebWebCrawlMdResponse::Result::Metadata::Heading],
            ?image: String,
            ?json_ld: ::Array[::Hash[Symbol, top]],
            ?keywords: ::Array[String],
            ?language: String,
            ?modified_time: String,
            ?open_graph: ::Hash[Symbol, ContextDev::Models::WebWebCrawlMdResponse::Result::Metadata::open_graph],
            ?published_time: String,
            ?robots: String,
            ?site_name: String,
            ?twitter: ::Hash[Symbol, ContextDev::Models::WebWebCrawlMdResponse::Result::Metadata::twitter]
          ) -> void

          def to_hash: -> {
            crawl_depth: Integer,
            final_url: String,
            source_url: String,
            status_code: Integer,
            success: bool,
            title: String,
            url: String,
            additional_meta: ::Hash[Symbol, ContextDev::Models::WebWebCrawlMdResponse::Result::Metadata::additional_meta],
            alternates: ::Array[ContextDev::Models::WebWebCrawlMdResponse::Result::Metadata::Alternate],
            author: String,
            canonical_url: String,
            description: String,
            favicon: String,
            headings: ::Array[ContextDev::Models::WebWebCrawlMdResponse::Result::Metadata::Heading],
            image: String,
            json_ld: ::Array[::Hash[Symbol, top]],
            keywords: ::Array[String],
            language: String,
            modified_time: String,
            open_graph: ::Hash[Symbol, ContextDev::Models::WebWebCrawlMdResponse::Result::Metadata::open_graph],
            published_time: String,
            robots: String,
            site_name: String,
            twitter: ::Hash[Symbol, ContextDev::Models::WebWebCrawlMdResponse::Result::Metadata::twitter]
          }

          type additional_meta = String | ::Array[String]

          module AdditionalMeta
            extend ContextDev::Internal::Type::Union

            def self?.variants: -> ::Array[ContextDev::Models::WebWebCrawlMdResponse::Result::Metadata::additional_meta]

            StringArray: ContextDev::Internal::Type::Converter
          end

          type alternate =
            { href: String, hreflang: String, title: String, type: String }

          class Alternate < ContextDev::Internal::Type::BaseModel
            attr_accessor href: String

            attr_reader hreflang: String?

            def hreflang=: (String) -> String

            attr_reader title: String?

            def title=: (String) -> String

            attr_reader type: String?

            def type=: (String) -> String

            def initialize: (
              href: String,
              ?hreflang: String,
              ?title: String,
              ?type: String
            ) -> void

            def to_hash: -> {
              href: String,
              hreflang: String,
              title: String,
              type: String
            }
          end

          type heading = { level: Integer, text: String }

          class Heading < ContextDev::Internal::Type::BaseModel
            attr_accessor level: Integer

            attr_accessor text: String

            def initialize: (level: Integer, text: String) -> void

            def to_hash: -> { level: Integer, text: String }
          end

          type open_graph = String | ::Array[String]

          module OpenGraph
            extend ContextDev::Internal::Type::Union

            def self?.variants: -> ::Array[ContextDev::Models::WebWebCrawlMdResponse::Result::Metadata::open_graph]

            StringArray: ContextDev::Internal::Type::Converter
          end

          type twitter = String | ::Array[String]

          module Twitter
            extend ContextDev::Internal::Type::Union

            def self?.variants: -> ::Array[ContextDev::Models::WebWebCrawlMdResponse::Result::Metadata::twitter]

            StringArray: ContextDev::Internal::Type::Converter
          end
        end
      end

      type key_metadata =
        { credits_consumed: Integer, credits_remaining: Integer }

      class KeyMetadata < ContextDev::Internal::Type::BaseModel
        attr_accessor credits_consumed: Integer

        attr_accessor credits_remaining: Integer

        def initialize: (
          credits_consumed: Integer,
          credits_remaining: Integer
        ) -> void

        def to_hash: -> {
          credits_consumed: Integer,
          credits_remaining: Integer
        }
      end
    end
  end
end
