module ContextDev
  module Models
    type web_screenshot_params =
      {
        direct_url: String,
        domain: String,
        full_screenshot: ContextDev::Models::WebScreenshotParams::full_screenshot,
        max_age_ms: Integer,
        page: ContextDev::Models::WebScreenshotParams::page,
        prioritize: ContextDev::Models::WebScreenshotParams::prioritize,
        viewport: ContextDev::WebScreenshotParams::Viewport
      }
      & ContextDev::Internal::Type::request_parameters

    class WebScreenshotParams < ContextDev::Internal::Type::BaseModel
      extend ContextDev::Internal::Type::RequestParameters::Converter
      include ContextDev::Internal::Type::RequestParameters

      attr_reader direct_url: String?

      def direct_url=: (String) -> String

      attr_reader domain: String?

      def domain=: (String) -> String

      attr_reader full_screenshot: ContextDev::Models::WebScreenshotParams::full_screenshot?

      def full_screenshot=: (
        ContextDev::Models::WebScreenshotParams::full_screenshot
      ) -> ContextDev::Models::WebScreenshotParams::full_screenshot

      attr_reader max_age_ms: Integer?

      def max_age_ms=: (Integer) -> Integer

      attr_reader page: ContextDev::Models::WebScreenshotParams::page?

      def page=: (
        ContextDev::Models::WebScreenshotParams::page
      ) -> ContextDev::Models::WebScreenshotParams::page

      attr_reader prioritize: ContextDev::Models::WebScreenshotParams::prioritize?

      def prioritize=: (
        ContextDev::Models::WebScreenshotParams::prioritize
      ) -> ContextDev::Models::WebScreenshotParams::prioritize

      attr_reader viewport: ContextDev::WebScreenshotParams::Viewport?

      def viewport=: (
        ContextDev::WebScreenshotParams::Viewport
      ) -> ContextDev::WebScreenshotParams::Viewport

      def initialize: (
        ?direct_url: String,
        ?domain: String,
        ?full_screenshot: ContextDev::Models::WebScreenshotParams::full_screenshot,
        ?max_age_ms: Integer,
        ?page: ContextDev::Models::WebScreenshotParams::page,
        ?prioritize: ContextDev::Models::WebScreenshotParams::prioritize,
        ?viewport: ContextDev::WebScreenshotParams::Viewport,
        ?request_options: ContextDev::request_opts
      ) -> void

      def to_hash: -> {
        direct_url: String,
        domain: String,
        full_screenshot: ContextDev::Models::WebScreenshotParams::full_screenshot,
        max_age_ms: Integer,
        page: ContextDev::Models::WebScreenshotParams::page,
        prioritize: ContextDev::Models::WebScreenshotParams::prioritize,
        viewport: ContextDev::WebScreenshotParams::Viewport,
        request_options: ContextDev::RequestOptions
      }

      type full_screenshot = :true | :false

      module FullScreenshot
        extend ContextDev::Internal::Type::Enum

        TRUE: :true
        FALSE: :false

        def self?.values: -> ::Array[ContextDev::Models::WebScreenshotParams::full_screenshot]
      end

      type page =
        :login
        | :signup
        | :blog
        | :careers
        | :pricing
        | :terms
        | :privacy
        | :contact

      module Page
        extend ContextDev::Internal::Type::Enum

        LOGIN: :login
        SIGNUP: :signup
        BLOG: :blog
        CAREERS: :careers
        PRICING: :pricing
        TERMS: :terms
        PRIVACY: :privacy
        CONTACT: :contact

        def self?.values: -> ::Array[ContextDev::Models::WebScreenshotParams::page]
      end

      type prioritize = :speed | :quality

      module Prioritize
        extend ContextDev::Internal::Type::Enum

        SPEED: :speed
        QUALITY: :quality

        def self?.values: -> ::Array[ContextDev::Models::WebScreenshotParams::prioritize]
      end

      type viewport = { height: Integer, width: Integer }

      class Viewport < ContextDev::Internal::Type::BaseModel
        attr_reader height: Integer?

        def height=: (Integer) -> Integer

        attr_reader width: Integer?

        def width=: (Integer) -> Integer

        def initialize: (?height: Integer, ?width: Integer) -> void

        def to_hash: -> { height: Integer, width: Integer }
      end
    end
  end
end
