module ContextDev
  module Models
    type web_web_scrape_md_params =
      {
        url: String,
        headers: ::Hash[Symbol, String],
        include_frames: bool,
        include_images: bool,
        include_links: bool,
        max_age_ms: Integer,
        pdf: ContextDev::WebWebScrapeMdParams::Pdf,
        :shorten_base64_images => bool,
        timeout_ms: Integer,
        use_main_content_only: bool,
        wait_for_ms: Integer
      }
      & ContextDev::Internal::Type::request_parameters

    class WebWebScrapeMdParams < ContextDev::Internal::Type::BaseModel
      extend ContextDev::Internal::Type::RequestParameters::Converter
      include ContextDev::Internal::Type::RequestParameters

      attr_accessor url: String

      attr_reader headers: ::Hash[Symbol, String]?

      def headers=: (::Hash[Symbol, String]) -> ::Hash[Symbol, String]

      attr_reader include_frames: bool?

      def include_frames=: (bool) -> bool

      attr_reader include_images: bool?

      def include_images=: (bool) -> bool

      attr_reader include_links: bool?

      def include_links=: (bool) -> bool

      attr_reader max_age_ms: Integer?

      def max_age_ms=: (Integer) -> Integer

      attr_reader pdf: ContextDev::WebWebScrapeMdParams::Pdf?

      def pdf=: (
        ContextDev::WebWebScrapeMdParams::Pdf
      ) -> ContextDev::WebWebScrapeMdParams::Pdf

      attr_reader shorten_base64_images: bool?

      def shorten_base64_images=: (bool) -> bool

      attr_reader timeout_ms: Integer?

      def timeout_ms=: (Integer) -> Integer

      attr_reader use_main_content_only: bool?

      def use_main_content_only=: (bool) -> bool

      attr_reader wait_for_ms: Integer?

      def wait_for_ms=: (Integer) -> Integer

      def initialize: (
        url: String,
        ?headers: ::Hash[Symbol, String],
        ?include_frames: bool,
        ?include_images: bool,
        ?include_links: bool,
        ?max_age_ms: Integer,
        ?pdf: ContextDev::WebWebScrapeMdParams::Pdf,
        ?shorten_base64_images: bool,
        ?timeout_ms: Integer,
        ?use_main_content_only: bool,
        ?wait_for_ms: Integer,
        ?request_options: ContextDev::request_opts
      ) -> void

      def to_hash: -> {
        url: String,
        headers: ::Hash[Symbol, String],
        include_frames: bool,
        include_images: bool,
        include_links: bool,
        max_age_ms: Integer,
        pdf: ContextDev::WebWebScrapeMdParams::Pdf,
        :shorten_base64_images => bool,
        timeout_ms: Integer,
        use_main_content_only: bool,
        wait_for_ms: Integer,
        request_options: ContextDev::RequestOptions
      }

      type pdf = { end_: Integer, should_parse: bool, start: Integer }

      class Pdf < ContextDev::Internal::Type::BaseModel
        attr_reader end_: Integer?

        def end_=: (Integer) -> Integer

        attr_reader should_parse: bool?

        def should_parse=: (bool) -> bool

        attr_reader start: Integer?

        def start=: (Integer) -> Integer

        def initialize: (
          ?end_: Integer,
          ?should_parse: bool,
          ?start: Integer
        ) -> void

        def to_hash: -> { end_: Integer, should_parse: bool, start: Integer }
      end
    end
  end
end
