module ContextDev
  module Models
    type web_web_scrape_sitemap_params =
      {
        domain: String,
        headers: ::Hash[Symbol, String],
        max_links: Integer,
        search: String,
        sitemap_url: String,
        tags: ::Array[String],
        timeout_ms: Integer,
        url_regex: String,
        zdr: ContextDev::Models::WebWebScrapeSitemapParams::zdr
      }
      & ContextDev::Internal::Type::request_parameters

    class WebWebScrapeSitemapParams < ContextDev::Internal::Type::BaseModel
      extend ContextDev::Internal::Type::RequestParameters::Converter
      include ContextDev::Internal::Type::RequestParameters

      attr_accessor domain: String

      attr_reader headers: ::Hash[Symbol, String]?

      def headers=: (::Hash[Symbol, String]) -> ::Hash[Symbol, String]

      attr_reader max_links: Integer?

      def max_links=: (Integer) -> Integer

      attr_reader search: String?

      def search=: (String) -> String

      attr_reader sitemap_url: String?

      def sitemap_url=: (String) -> String

      attr_reader tags: ::Array[String]?

      def tags=: (::Array[String]) -> ::Array[String]

      attr_reader timeout_ms: Integer?

      def timeout_ms=: (Integer) -> Integer

      attr_reader url_regex: String?

      def url_regex=: (String) -> String

      attr_reader zdr: ContextDev::Models::WebWebScrapeSitemapParams::zdr?

      def zdr=: (
        ContextDev::Models::WebWebScrapeSitemapParams::zdr
      ) -> ContextDev::Models::WebWebScrapeSitemapParams::zdr

      def initialize: (
        domain: String,
        ?headers: ::Hash[Symbol, String],
        ?max_links: Integer,
        ?search: String,
        ?sitemap_url: String,
        ?tags: ::Array[String],
        ?timeout_ms: Integer,
        ?url_regex: String,
        ?zdr: ContextDev::Models::WebWebScrapeSitemapParams::zdr,
        ?request_options: ContextDev::request_opts
      ) -> void

      def to_hash: -> {
        domain: String,
        headers: ::Hash[Symbol, String],
        max_links: Integer,
        search: String,
        sitemap_url: String,
        tags: ::Array[String],
        timeout_ms: Integer,
        url_regex: String,
        zdr: ContextDev::Models::WebWebScrapeSitemapParams::zdr,
        request_options: ContextDev::RequestOptions
      }

      type zdr = :enabled | :disabled

      module Zdr
        extend ContextDev::Internal::Type::Enum

        ENABLED: :enabled
        DISABLED: :disabled

        def self?.values: -> ::Array[ContextDev::Models::WebWebScrapeSitemapParams::zdr]
      end
    end
  end
end
