module ContextDev
  module Models
    type web_web_scrape_sitemap_response =
      {
        domain: String,
        meta: ContextDev::Models::WebWebScrapeSitemapResponse::Meta,
        request_id: String,
        success: ContextDev::Models::WebWebScrapeSitemapResponse::success,
        urls: ::Array[String],
        key_metadata: ContextDev::Models::WebWebScrapeSitemapResponse::KeyMetadata,
        partial: bool
      }

    class WebWebScrapeSitemapResponse < ContextDev::Internal::Type::BaseModel
      attr_accessor domain: String

      attr_accessor meta: ContextDev::Models::WebWebScrapeSitemapResponse::Meta

      attr_accessor request_id: String

      attr_accessor success: ContextDev::Models::WebWebScrapeSitemapResponse::success

      attr_accessor urls: ::Array[String]

      attr_reader key_metadata: ContextDev::Models::WebWebScrapeSitemapResponse::KeyMetadata?

      def key_metadata=: (
        ContextDev::Models::WebWebScrapeSitemapResponse::KeyMetadata
      ) -> ContextDev::Models::WebWebScrapeSitemapResponse::KeyMetadata

      attr_reader partial: bool?

      def partial=: (bool) -> bool

      def initialize: (
        domain: String,
        meta: ContextDev::Models::WebWebScrapeSitemapResponse::Meta,
        request_id: String,
        success: ContextDev::Models::WebWebScrapeSitemapResponse::success,
        urls: ::Array[String],
        ?key_metadata: ContextDev::Models::WebWebScrapeSitemapResponse::KeyMetadata,
        ?partial: bool
      ) -> void

      def to_hash: -> {
        domain: String,
        meta: ContextDev::Models::WebWebScrapeSitemapResponse::Meta,
        request_id: String,
        success: ContextDev::Models::WebWebScrapeSitemapResponse::success,
        urls: ::Array[String],
        key_metadata: ContextDev::Models::WebWebScrapeSitemapResponse::KeyMetadata,
        partial: bool
      }

      type meta =
        {
          errors: Integer,
          sitemaps_discovered: Integer,
          sitemaps_fetched: Integer,
          sitemaps_skipped: Integer
        }

      class Meta < ContextDev::Internal::Type::BaseModel
        attr_accessor errors: Integer

        attr_accessor sitemaps_discovered: Integer

        attr_accessor sitemaps_fetched: Integer

        attr_accessor sitemaps_skipped: Integer

        def initialize: (
          errors: Integer,
          sitemaps_discovered: Integer,
          sitemaps_fetched: Integer,
          sitemaps_skipped: Integer
        ) -> void

        def to_hash: -> {
          errors: Integer,
          sitemaps_discovered: Integer,
          sitemaps_fetched: Integer,
          sitemaps_skipped: Integer
        }
      end

      type success = true

      module Success
        extend ContextDev::Internal::Type::Enum

        TRUE: true

        def self?.values: -> ::Array[ContextDev::Models::WebWebScrapeSitemapResponse::success]
      end

      type key_metadata =
        { credits_consumed: Integer, credits_remaining: Integer }

      class KeyMetadata < ContextDev::Internal::Type::BaseModel
        attr_accessor credits_consumed: Integer

        attr_accessor credits_remaining: Integer

        def initialize: (
          credits_consumed: Integer,
          credits_remaining: Integer
        ) -> void

        def to_hash: -> {
          credits_consumed: Integer,
          credits_remaining: Integer
        }
      end
    end
  end
end
