module ContextDev
  module Models
    type web_extract_response =
      {
        data: ::Hash[Symbol, top],
        metadata: ContextDev::Models::WebExtractResponse::Metadata,
        status: String,
        url: String,
        urls_analyzed: ::Array[String],
        key_metadata: ContextDev::Models::WebExtractResponse::KeyMetadata
      }

    class WebExtractResponse < ContextDev::Internal::Type::BaseModel
      attr_accessor data: ::Hash[Symbol, top]

      attr_accessor metadata: ContextDev::Models::WebExtractResponse::Metadata

      attr_accessor status: String

      attr_accessor url: String

      attr_accessor urls_analyzed: ::Array[String]

      attr_reader key_metadata: ContextDev::Models::WebExtractResponse::KeyMetadata?

      def key_metadata=: (
        ContextDev::Models::WebExtractResponse::KeyMetadata
      ) -> ContextDev::Models::WebExtractResponse::KeyMetadata

      def initialize: (
        data: ::Hash[Symbol, top],
        metadata: ContextDev::Models::WebExtractResponse::Metadata,
        status: String,
        url: String,
        urls_analyzed: ::Array[String],
        ?key_metadata: ContextDev::Models::WebExtractResponse::KeyMetadata
      ) -> void

      def to_hash: -> {
        data: ::Hash[Symbol, top],
        metadata: ContextDev::Models::WebExtractResponse::Metadata,
        status: String,
        url: String,
        urls_analyzed: ::Array[String],
        key_metadata: ContextDev::Models::WebExtractResponse::KeyMetadata
      }

      type metadata =
        {
          max_crawl_depth: Integer,
          num_failed: Integer,
          num_skipped: Integer,
          num_succeeded: Integer,
          num_urls: Integer
        }

      class Metadata < ContextDev::Internal::Type::BaseModel
        attr_accessor max_crawl_depth: Integer

        attr_accessor num_failed: Integer

        attr_accessor num_skipped: Integer

        attr_accessor num_succeeded: Integer

        attr_accessor num_urls: Integer

        def initialize: (
          max_crawl_depth: Integer,
          num_failed: Integer,
          num_skipped: Integer,
          num_succeeded: Integer,
          num_urls: Integer
        ) -> void

        def to_hash: -> {
          max_crawl_depth: Integer,
          num_failed: Integer,
          num_skipped: Integer,
          num_succeeded: Integer,
          num_urls: Integer
        }
      end

      type key_metadata =
        { credits_consumed: Integer, credits_remaining: Integer }

      class KeyMetadata < ContextDev::Internal::Type::BaseModel
        attr_accessor credits_consumed: Integer

        attr_accessor credits_remaining: Integer

        def initialize: (
          credits_consumed: Integer,
          credits_remaining: Integer
        ) -> void

        def to_hash: -> {
          credits_consumed: Integer,
          credits_remaining: Integer
        }
      end
    end
  end
end
