module ContextDev
  module Models
    type web_extract_fonts_params =
      {
        direct_url: String,
        domain: String,
        max_age_ms: Integer?,
        tags: ::Array[String],
        timeout_opts: ContextDev::WebExtractFontsParams::TimeoutOpts
      }
      & ContextDev::Internal::Type::request_parameters

    class WebExtractFontsParams < ContextDev::Internal::Type::BaseModel
      extend ContextDev::Internal::Type::RequestParameters::Converter
      include ContextDev::Internal::Type::RequestParameters

      attr_reader direct_url: String?

      def direct_url=: (String) -> String

      attr_reader domain: String?

      def domain=: (String) -> String

      attr_accessor max_age_ms: Integer?

      attr_reader tags: ::Array[String]?

      def tags=: (::Array[String]) -> ::Array[String]

      attr_reader timeout_opts: ContextDev::WebExtractFontsParams::TimeoutOpts?

      def timeout_opts=: (
        ContextDev::WebExtractFontsParams::TimeoutOpts
      ) -> ContextDev::WebExtractFontsParams::TimeoutOpts

      def initialize: (
        ?direct_url: String,
        ?domain: String,
        ?max_age_ms: Integer?,
        ?tags: ::Array[String],
        ?timeout_opts: ContextDev::WebExtractFontsParams::TimeoutOpts,
        ?request_options: ContextDev::request_opts
      ) -> void

      def to_hash: -> {
        direct_url: String,
        domain: String,
        max_age_ms: Integer?,
        tags: ::Array[String],
        timeout_opts: ContextDev::WebExtractFontsParams::TimeoutOpts,
        request_options: ContextDev::RequestOptions
      }

      type timeout_opts =
        {
          milliseconds: Integer,
          behavior: ContextDev::Models::WebExtractFontsParams::TimeoutOpts::behavior
        }

      class TimeoutOpts < ContextDev::Internal::Type::BaseModel
        attr_accessor milliseconds: Integer

        attr_reader behavior: ContextDev::Models::WebExtractFontsParams::TimeoutOpts::behavior?

        def behavior=: (
          ContextDev::Models::WebExtractFontsParams::TimeoutOpts::behavior
        ) -> ContextDev::Models::WebExtractFontsParams::TimeoutOpts::behavior

        def initialize: (
          milliseconds: Integer,
          ?behavior: ContextDev::Models::WebExtractFontsParams::TimeoutOpts::behavior
        ) -> void

        def to_hash: -> {
          milliseconds: Integer,
          behavior: ContextDev::Models::WebExtractFontsParams::TimeoutOpts::behavior
        }

        type behavior = :fail | :"return-partial"

        module Behavior
          extend ContextDev::Internal::Type::Enum

          FAIL: :fail
          RETURN_PARTIAL: :"return-partial"

          def self?.values: -> ::Array[ContextDev::Models::WebExtractFontsParams::TimeoutOpts::behavior]
        end
      end
    end
  end
end
