module ContextDev
  module Models
    type web_web_scrape_images_params =
      {
        url: String,
        actions: ::Array[ContextDev::Models::WebWebScrapeImagesParams::action]?,
        dedupe: bool,
        enrichment: ContextDev::WebWebScrapeImagesParams::Enrichment?,
        headers: ::Hash[Symbol, String],
        max_age_ms: Integer?,
        tags: ::Array[String],
        timeout_ms: Integer,
        wait_for_ms: Integer?
      }
      & ContextDev::Internal::Type::request_parameters

    class WebWebScrapeImagesParams < ContextDev::Internal::Type::BaseModel
      extend ContextDev::Internal::Type::RequestParameters::Converter
      include ContextDev::Internal::Type::RequestParameters

      attr_accessor url: String

      attr_accessor actions: ::Array[ContextDev::Models::WebWebScrapeImagesParams::action]?

      attr_reader dedupe: bool?

      def dedupe=: (bool) -> bool

      attr_accessor enrichment: ContextDev::WebWebScrapeImagesParams::Enrichment?

      attr_reader headers: ::Hash[Symbol, String]?

      def headers=: (::Hash[Symbol, String]) -> ::Hash[Symbol, String]

      attr_accessor max_age_ms: Integer?

      attr_reader tags: ::Array[String]?

      def tags=: (::Array[String]) -> ::Array[String]

      attr_reader timeout_ms: Integer?

      def timeout_ms=: (Integer) -> Integer

      attr_accessor wait_for_ms: Integer?

      def initialize: (
        url: String,
        ?actions: ::Array[ContextDev::Models::WebWebScrapeImagesParams::action]?,
        ?dedupe: bool,
        ?enrichment: ContextDev::WebWebScrapeImagesParams::Enrichment?,
        ?headers: ::Hash[Symbol, String],
        ?max_age_ms: Integer?,
        ?tags: ::Array[String],
        ?timeout_ms: Integer,
        ?wait_for_ms: Integer?,
        ?request_options: ContextDev::request_opts
      ) -> void

      def to_hash: -> {
        url: String,
        actions: ::Array[ContextDev::Models::WebWebScrapeImagesParams::action]?,
        dedupe: bool,
        enrichment: ContextDev::WebWebScrapeImagesParams::Enrichment?,
        headers: ::Hash[Symbol, String],
        max_age_ms: Integer?,
        tags: ::Array[String],
        timeout_ms: Integer,
        wait_for_ms: Integer?,
        request_options: ContextDev::RequestOptions
      }

      type action =
        ContextDev::WebWebScrapeImagesParams::Action::Wait
        | ContextDev::WebWebScrapeImagesParams::Action::Perform

      module Action
        extend ContextDev::Internal::Type::Union

        type wait = { do_: :wait, time_ms: Integer }

        class Wait < ContextDev::Internal::Type::BaseModel
          attr_accessor do_: :wait

          attr_accessor time_ms: Integer

          def initialize: (time_ms: Integer, ?do_: :wait) -> void

          def to_hash: -> { do_: :wait, time_ms: Integer }
        end

        type perform = { action: String, do_: :perform }

        class Perform < ContextDev::Internal::Type::BaseModel
          attr_accessor action: String

          attr_accessor do_: :perform

          def initialize: (action: String, ?do_: :perform) -> void

          def to_hash: -> { action: String, do_: :perform }
        end

        def self?.variants: -> ::Array[ContextDev::Models::WebWebScrapeImagesParams::action]
      end

      type enrichment =
        {
          classification: bool,
          hosted_url: bool,
          max_time_per_ms: Integer,
          resolution: bool
        }

      class Enrichment < ContextDev::Internal::Type::BaseModel
        attr_reader classification: bool?

        def classification=: (bool) -> bool

        attr_reader hosted_url: bool?

        def hosted_url=: (bool) -> bool

        attr_reader max_time_per_ms: Integer?

        def max_time_per_ms=: (Integer) -> Integer

        attr_reader resolution: bool?

        def resolution=: (bool) -> bool

        def initialize: (
          ?classification: bool,
          ?hosted_url: bool,
          ?max_time_per_ms: Integer,
          ?resolution: bool
        ) -> void

        def to_hash: -> {
          classification: bool,
          hosted_url: bool,
          max_time_per_ms: Integer,
          resolution: bool
        }
      end
    end
  end
end
