module ContextDev
  module Models
    type web_search_params =
      {
        query: String,
        country: ContextDev::Models::WebSearchParams::country,
        exclude_domains: ::Array[String],
        freshness: ContextDev::Models::WebSearchParams::freshness,
        include_domains: ::Array[String],
        markdown_options: ContextDev::WebSearchParams::MarkdownOptions,
        num_results: Integer,
        query_fanout: bool,
        timeout_ms: Integer
      }
      & ContextDev::Internal::Type::request_parameters

    class WebSearchParams < ContextDev::Internal::Type::BaseModel
      extend ContextDev::Internal::Type::RequestParameters::Converter
      include ContextDev::Internal::Type::RequestParameters

      attr_accessor query: String

      attr_reader country: ContextDev::Models::WebSearchParams::country?

      def country=: (
        ContextDev::Models::WebSearchParams::country
      ) -> ContextDev::Models::WebSearchParams::country

      attr_reader exclude_domains: ::Array[String]?

      def exclude_domains=: (::Array[String]) -> ::Array[String]

      attr_reader freshness: ContextDev::Models::WebSearchParams::freshness?

      def freshness=: (
        ContextDev::Models::WebSearchParams::freshness
      ) -> ContextDev::Models::WebSearchParams::freshness

      attr_reader include_domains: ::Array[String]?

      def include_domains=: (::Array[String]) -> ::Array[String]

      attr_reader markdown_options: ContextDev::WebSearchParams::MarkdownOptions?

      def markdown_options=: (
        ContextDev::WebSearchParams::MarkdownOptions
      ) -> ContextDev::WebSearchParams::MarkdownOptions

      attr_reader num_results: Integer?

      def num_results=: (Integer) -> Integer

      attr_reader query_fanout: bool?

      def query_fanout=: (bool) -> bool

      attr_reader timeout_ms: Integer?

      def timeout_ms=: (Integer) -> Integer

      def initialize: (
        query: String,
        ?country: ContextDev::Models::WebSearchParams::country,
        ?exclude_domains: ::Array[String],
        ?freshness: ContextDev::Models::WebSearchParams::freshness,
        ?include_domains: ::Array[String],
        ?markdown_options: ContextDev::WebSearchParams::MarkdownOptions,
        ?num_results: Integer,
        ?query_fanout: bool,
        ?timeout_ms: Integer,
        ?request_options: ContextDev::request_opts
      ) -> void

      def to_hash: -> {
        query: String,
        country: ContextDev::Models::WebSearchParams::country,
        exclude_domains: ::Array[String],
        freshness: ContextDev::Models::WebSearchParams::freshness,
        include_domains: ::Array[String],
        markdown_options: ContextDev::WebSearchParams::MarkdownOptions,
        num_results: Integer,
        query_fanout: bool,
        timeout_ms: Integer,
        request_options: ContextDev::RequestOptions
      }

      type country =
        :af
        | :al
        | :dz
        | :as
        | :ad
        | :ao
        | :ai
        | :aq
        | :ag
        | :ar
        | :am
        | :aw
        | :au
        | :at
        | :az
        | :bs
        | :bh
        | :bd
        | :bb
        | :by
        | :be
        | :bz
        | :bj
        | :bm
        | :bt
        | :bo
        | :ba
        | :bw
        | :bv
        | :br
        | :io
        | :bn
        | :bg
        | :bf
        | :bi
        | :kh
        | :cm
        | :ca
        | :cv
        | :ky
        | :cf
        | :td
        | :cl
        | :cn
        | :cx
        | :cc
        | :co
        | :km
        | :cg
        | :cd
        | :ck
        | :cr
        | :ci
        | :hr
        | :cu
        | :cy
        | :cz
        | :dk
        | :dj
        | :dm
        | :do
        | :ec
        | :eg
        | :sv
        | :gq
        | :er
        | :ee
        | :et
        | :fk
        | :fo
        | :fj
        | :fi
        | :fr
        | :gf
        | :pf
        | :tf
        | :ga
        | :gm
        | :ge
        | :de
        | :gh
        | :gi
        | :gr
        | :gl
        | :gd
        | :gp
        | :gu
        | :gt
        | :gn
        | :gw
        | :gy
        | :ht
        | :hm
        | :va
        | :hn
        | :hk
        | :hu
        | :is
        | :in
        | :id
        | :ir
        | :iq
        | :ie
        | :il
        | :it
        | :jm
        | :jp
        | :jo
        | :kz
        | :ke
        | :ki
        | :kp
        | :kr
        | :kw
        | :kg
        | :la
        | :lv
        | :lb
        | :ls
        | :lr
        | :ly
        | :li
        | :lt
        | :lu
        | :mo
        | :mk
        | :mg
        | :mw
        | :my
        | :mv
        | :ml
        | :mt
        | :mh
        | :mq
        | :mr
        | :mu
        | :yt
        | :mx
        | :fm
        | :md
        | :mc
        | :mn
        | :ms
        | :ma
        | :mz
        | :mm
        | :na
        | :nr
        | :np
        | :nl
        | :an
        | :nc
        | :nz
        | :ni
        | :ne
        | :ng
        | :nu
        | :nf
        | :mp
        | :no
        | :om
        | :pk
        | :pw
        | :ps
        | :pa
        | :pg
        | :py
        | :pe
        | :ph
        | :pn
        | :pl
        | :pt
        | :pr
        | :qa
        | :re
        | :ro
        | :ru
        | :rw
        | :sh
        | :kn
        | :lc
        | :pm
        | :vc
        | :ws
        | :sm
        | :st
        | :sa
        | :sn
        | :rs
        | :sc
        | :sl
        | :sg
        | :sk
        | :si
        | :sb
        | :so
        | :za
        | :gs
        | :es
        | :lk
        | :sd
        | :sr
        | :sj
        | :sz
        | :se
        | :ch
        | :sy
        | :tw
        | :tj
        | :tz
        | :th
        | :tl
        | :tg
        | :tk
        | :to
        | :tt
        | :tn
        | :tr
        | :tm
        | :tc
        | :tv
        | :ug
        | :ua
        | :ae
        | :gb
        | :us
        | :um
        | :uy
        | :uz
        | :vu
        | :ve
        | :vn
        | :vg
        | :vi
        | :wf
        | :eh
        | :ye
        | :zm
        | :zw

      module Country
        extend ContextDev::Internal::Type::Enum

        AF: :af
        AL: :al
        DZ: :dz
        AS: :as
        AD: :ad
        AO: :ao
        AI: :ai
        AQ: :aq
        AG: :ag
        AR: :ar
        AM: :am
        AW: :aw
        AU: :au
        AT: :at
        AZ: :az
        BS: :bs
        BH: :bh
        BD: :bd
        BB: :bb
        BY: :by
        BE: :be
        BZ: :bz
        BJ: :bj
        BM: :bm
        BT: :bt
        BO: :bo
        BA: :ba
        BW: :bw
        BV: :bv
        BR: :br
        IO: :io
        BN: :bn
        BG: :bg
        BF: :bf
        BI: :bi
        KH: :kh
        CM: :cm
        CA: :ca
        CV: :cv
        KY: :ky
        CF: :cf
        TD: :td
        CL: :cl
        CN: :cn
        CX: :cx
        CC: :cc
        CO: :co
        KM: :km
        CG: :cg
        CD: :cd
        CK: :ck
        CR: :cr
        CI: :ci
        HR: :hr
        CU: :cu
        CY: :cy
        CZ: :cz
        DK: :dk
        DJ: :dj
        DM: :dm
        DO: :do
        EC: :ec
        EG: :eg
        SV: :sv
        GQ: :gq
        ER: :er
        EE: :ee
        ET: :et
        FK: :fk
        FO: :fo
        FJ: :fj
        FI: :fi
        FR: :fr
        GF: :gf
        PF: :pf
        TF: :tf
        GA: :ga
        GM: :gm
        GE: :ge
        DE: :de
        GH: :gh
        GI: :gi
        GR: :gr
        GL: :gl
        GD: :gd
        GP: :gp
        GU: :gu
        GT: :gt
        GN: :gn
        GW: :gw
        GY: :gy
        HT: :ht
        HM: :hm
        VA: :va
        HN: :hn
        HK: :hk
        HU: :hu
        IS: :is
        IN: :in
        ID: :id
        IR: :ir
        IQ: :iq
        IE: :ie
        IL: :il
        IT: :it
        JM: :jm
        JP: :jp
        JO: :jo
        KZ: :kz
        KE: :ke
        KI: :ki
        KP: :kp
        KR: :kr
        KW: :kw
        KG: :kg
        LA: :la
        LV: :lv
        LB: :lb
        LS: :ls
        LR: :lr
        LY: :ly
        LI: :li
        LT: :lt
        LU: :lu
        MO: :mo
        MK: :mk
        MG: :mg
        MW: :mw
        MY: :my
        MV: :mv
        ML: :ml
        MT: :mt
        MH: :mh
        MQ: :mq
        MR: :mr
        MU: :mu
        YT: :yt
        MX: :mx
        FM: :fm
        MD: :md
        MC: :mc
        MN: :mn
        MS: :ms
        MA: :ma
        MZ: :mz
        MM: :mm
        NA: :na
        NR: :nr
        NP: :np
        NL: :nl
        AN: :an
        NC: :nc
        NZ: :nz
        NI: :ni
        NE: :ne
        NG: :ng
        NU: :nu
        NF: :nf
        MP: :mp
        NO: :no
        OM: :om
        PK: :pk
        PW: :pw
        PS: :ps
        PA: :pa
        PG: :pg
        PY: :py
        PE: :pe
        PH: :ph
        PN: :pn
        PL: :pl
        PT: :pt
        PR: :pr
        QA: :qa
        RE: :re
        RO: :ro
        RU: :ru
        RW: :rw
        SH: :sh
        KN: :kn
        LC: :lc
        PM: :pm
        VC: :vc
        WS: :ws
        SM: :sm
        ST: :st
        SA: :sa
        SN: :sn
        RS: :rs
        SC: :sc
        SL: :sl
        SG: :sg
        SK: :sk
        SI: :si
        SB: :sb
        SO: :so
        ZA: :za
        GS: :gs
        ES: :es
        LK: :lk
        SD: :sd
        SR: :sr
        SJ: :sj
        SZ: :sz
        SE: :se
        CH: :ch
        SY: :sy
        TW: :tw
        TJ: :tj
        TZ: :tz
        TH: :th
        TL: :tl
        TG: :tg
        TK: :tk
        TO: :to
        TT: :tt
        TN: :tn
        TR: :tr
        TM: :tm
        TC: :tc
        TV: :tv
        UG: :ug
        UA: :ua
        AE: :ae
        GB: :gb
        US: :us
        UM: :um
        UY: :uy
        UZ: :uz
        VU: :vu
        VE: :ve
        VN: :vn
        VG: :vg
        VI: :vi
        WF: :wf
        EH: :eh
        YE: :ye
        ZM: :zm
        ZW: :zw

        def self?.values: -> ::Array[ContextDev::Models::WebSearchParams::country]
      end

      type freshness = :last_24_hours | :last_week | :last_month | :last_year

      module Freshness
        extend ContextDev::Internal::Type::Enum

        LAST_24_HOURS: :last_24_hours
        LAST_WEEK: :last_week
        LAST_MONTH: :last_month
        LAST_YEAR: :last_year

        def self?.values: -> ::Array[ContextDev::Models::WebSearchParams::freshness]
      end

      type markdown_options =
        {
          enabled: bool,
          include_frames: bool,
          include_images: bool,
          include_links: bool,
          max_age_ms: Integer,
          pdf: ContextDev::WebSearchParams::MarkdownOptions::Pdf,
          :shorten_base64_images => bool,
          timeout_ms: Integer,
          use_main_content_only: bool,
          wait_for_ms: Integer
        }

      class MarkdownOptions < ContextDev::Internal::Type::BaseModel
        attr_reader enabled: bool?

        def enabled=: (bool) -> bool

        attr_reader include_frames: bool?

        def include_frames=: (bool) -> bool

        attr_reader include_images: bool?

        def include_images=: (bool) -> bool

        attr_reader include_links: bool?

        def include_links=: (bool) -> bool

        attr_reader max_age_ms: Integer?

        def max_age_ms=: (Integer) -> Integer

        attr_reader pdf: ContextDev::WebSearchParams::MarkdownOptions::Pdf?

        def pdf=: (
          ContextDev::WebSearchParams::MarkdownOptions::Pdf
        ) -> ContextDev::WebSearchParams::MarkdownOptions::Pdf

        attr_reader shorten_base64_images: bool?

        def shorten_base64_images=: (bool) -> bool

        attr_reader timeout_ms: Integer?

        def timeout_ms=: (Integer) -> Integer

        attr_reader use_main_content_only: bool?

        def use_main_content_only=: (bool) -> bool

        attr_reader wait_for_ms: Integer?

        def wait_for_ms=: (Integer) -> Integer

        def initialize: (
          ?enabled: bool,
          ?include_frames: bool,
          ?include_images: bool,
          ?include_links: bool,
          ?max_age_ms: Integer,
          ?pdf: ContextDev::WebSearchParams::MarkdownOptions::Pdf,
          ?shorten_base64_images: bool,
          ?timeout_ms: Integer,
          ?use_main_content_only: bool,
          ?wait_for_ms: Integer
        ) -> void

        def to_hash: -> {
          enabled: bool,
          include_frames: bool,
          include_images: bool,
          include_links: bool,
          max_age_ms: Integer,
          pdf: ContextDev::WebSearchParams::MarkdownOptions::Pdf,
          :shorten_base64_images => bool,
          timeout_ms: Integer,
          use_main_content_only: bool,
          wait_for_ms: Integer
        }

        type pdf = { end_: Integer, should_parse: bool, start: Integer }

        class Pdf < ContextDev::Internal::Type::BaseModel
          attr_reader end_: Integer?

          def end_=: (Integer) -> Integer

          attr_reader should_parse: bool?

          def should_parse=: (bool) -> bool

          attr_reader start: Integer?

          def start=: (Integer) -> Integer

          def initialize: (
            ?end_: Integer,
            ?should_parse: bool,
            ?start: Integer
          ) -> void

          def to_hash: -> { end_: Integer, should_parse: bool, start: Integer }
        end
      end
    end
  end
end
