module ContextDev
  module Models
    type web_screenshot_response =
      {
        cache_metadata: ContextDev::Models::WebScreenshotResponse::CacheMetadata,
        request_id: String,
        code: Integer,
        domain: String,
        height: Integer,
        key_metadata: ContextDev::Models::WebScreenshotResponse::KeyMetadata,
        screenshot: String,
        screenshot_type: ContextDev::Models::WebScreenshotResponse::screenshot_type,
        status: String,
        width: Integer
      }

    class WebScreenshotResponse < ContextDev::Internal::Type::BaseModel
      attr_accessor cache_metadata: ContextDev::Models::WebScreenshotResponse::CacheMetadata

      attr_accessor request_id: String

      attr_reader code: Integer?

      def code=: (Integer) -> Integer

      attr_reader domain: String?

      def domain=: (String) -> String

      attr_reader height: Integer?

      def height=: (Integer) -> Integer

      attr_reader key_metadata: ContextDev::Models::WebScreenshotResponse::KeyMetadata?

      def key_metadata=: (
        ContextDev::Models::WebScreenshotResponse::KeyMetadata
      ) -> ContextDev::Models::WebScreenshotResponse::KeyMetadata

      attr_reader screenshot: String?

      def screenshot=: (String) -> String

      attr_reader screenshot_type: ContextDev::Models::WebScreenshotResponse::screenshot_type?

      def screenshot_type=: (
        ContextDev::Models::WebScreenshotResponse::screenshot_type
      ) -> ContextDev::Models::WebScreenshotResponse::screenshot_type

      attr_reader status: String?

      def status=: (String) -> String

      attr_reader width: Integer?

      def width=: (Integer) -> Integer

      def initialize: (
        cache_metadata: ContextDev::Models::WebScreenshotResponse::CacheMetadata,
        request_id: String,
        ?code: Integer,
        ?domain: String,
        ?height: Integer,
        ?key_metadata: ContextDev::Models::WebScreenshotResponse::KeyMetadata,
        ?screenshot: String,
        ?screenshot_type: ContextDev::Models::WebScreenshotResponse::screenshot_type,
        ?status: String,
        ?width: Integer
      ) -> void

      def to_hash: -> {
        cache_metadata: ContextDev::Models::WebScreenshotResponse::CacheMetadata,
        request_id: String,
        code: Integer,
        domain: String,
        height: Integer,
        key_metadata: ContextDev::Models::WebScreenshotResponse::KeyMetadata,
        screenshot: String,
        screenshot_type: ContextDev::Models::WebScreenshotResponse::screenshot_type,
        status: String,
        width: Integer
      }

      type cache_metadata =
        {
          age_ms: Integer,
          status: ContextDev::Models::WebScreenshotResponse::CacheMetadata::status
        }

      class CacheMetadata < ContextDev::Internal::Type::BaseModel
        attr_accessor age_ms: Integer

        attr_accessor status: ContextDev::Models::WebScreenshotResponse::CacheMetadata::status

        def initialize: (
          age_ms: Integer,
          status: ContextDev::Models::WebScreenshotResponse::CacheMetadata::status
        ) -> void

        def to_hash: -> {
          age_ms: Integer,
          status: ContextDev::Models::WebScreenshotResponse::CacheMetadata::status
        }

        type status = :hit | :miss | :zdr

        module Status
          extend ContextDev::Internal::Type::Enum

          HIT: :hit
          MISS: :miss
          ZDR: :zdr

          def self?.values: -> ::Array[ContextDev::Models::WebScreenshotResponse::CacheMetadata::status]
        end
      end

      type key_metadata =
        { credits_consumed: Integer, credits_remaining: Integer }

      class KeyMetadata < ContextDev::Internal::Type::BaseModel
        attr_accessor credits_consumed: Integer

        attr_accessor credits_remaining: Integer

        def initialize: (
          credits_consumed: Integer,
          credits_remaining: Integer
        ) -> void

        def to_hash: -> {
          credits_consumed: Integer,
          credits_remaining: Integer
        }
      end

      type screenshot_type = :viewport | :fullPage

      module ScreenshotType
        extend ContextDev::Internal::Type::Enum

        VIEWPORT: :viewport
        FULL_PAGE: :fullPage

        def self?.values: -> ::Array[ContextDev::Models::WebScreenshotResponse::screenshot_type]
      end
    end
  end
end
