module ContextDev
  module Models
    type web_web_scrape_screenshot_response =
      {
        cache_metadata: ContextDev::Models::WebWebScrapeScreenshotResponse::CacheMetadata,
        height: Integer,
        request_id: String,
        screenshot: String,
        url: String,
        width: Integer,
        final_dom_state: ContextDev::Models::WebWebScrapeScreenshotResponse::final_dom_state,
        key_metadata: ContextDev::Models::WebWebScrapeScreenshotResponse::KeyMetadata
      }

    class WebWebScrapeScreenshotResponse < ContextDev::Internal::Type::BaseModel
      attr_accessor cache_metadata: ContextDev::Models::WebWebScrapeScreenshotResponse::CacheMetadata

      attr_accessor height: Integer

      attr_accessor request_id: String

      attr_accessor screenshot: String

      attr_accessor url: String

      attr_accessor width: Integer

      attr_reader final_dom_state: ContextDev::Models::WebWebScrapeScreenshotResponse::final_dom_state?

      def final_dom_state=: (
        ContextDev::Models::WebWebScrapeScreenshotResponse::final_dom_state
      ) -> ContextDev::Models::WebWebScrapeScreenshotResponse::final_dom_state

      attr_reader key_metadata: ContextDev::Models::WebWebScrapeScreenshotResponse::KeyMetadata?

      def key_metadata=: (
        ContextDev::Models::WebWebScrapeScreenshotResponse::KeyMetadata
      ) -> ContextDev::Models::WebWebScrapeScreenshotResponse::KeyMetadata

      def initialize: (
        cache_metadata: ContextDev::Models::WebWebScrapeScreenshotResponse::CacheMetadata,
        height: Integer,
        request_id: String,
        screenshot: String,
        url: String,
        width: Integer,
        ?final_dom_state: ContextDev::Models::WebWebScrapeScreenshotResponse::final_dom_state,
        ?key_metadata: ContextDev::Models::WebWebScrapeScreenshotResponse::KeyMetadata
      ) -> void

      def to_hash: -> {
        cache_metadata: ContextDev::Models::WebWebScrapeScreenshotResponse::CacheMetadata,
        height: Integer,
        request_id: String,
        screenshot: String,
        url: String,
        width: Integer,
        final_dom_state: ContextDev::Models::WebWebScrapeScreenshotResponse::final_dom_state,
        key_metadata: ContextDev::Models::WebWebScrapeScreenshotResponse::KeyMetadata
      }

      type cache_metadata =
        {
          age_ms: Integer,
          status: ContextDev::Models::WebWebScrapeScreenshotResponse::CacheMetadata::status
        }

      class CacheMetadata < ContextDev::Internal::Type::BaseModel
        attr_accessor age_ms: Integer

        attr_accessor status: ContextDev::Models::WebWebScrapeScreenshotResponse::CacheMetadata::status

        def initialize: (
          age_ms: Integer,
          status: ContextDev::Models::WebWebScrapeScreenshotResponse::CacheMetadata::status
        ) -> void

        def to_hash: -> {
          age_ms: Integer,
          status: ContextDev::Models::WebWebScrapeScreenshotResponse::CacheMetadata::status
        }

        type status = :hit | :miss | :zdr

        module Status
          extend ContextDev::Internal::Type::Enum

          HIT: :hit
          MISS: :miss
          ZDR: :zdr

          def self?.values: -> ::Array[ContextDev::Models::WebWebScrapeScreenshotResponse::CacheMetadata::status]
        end
      end

      type final_dom_state = :loaded | :"still-loading"

      module FinalDomState
        extend ContextDev::Internal::Type::Enum

        LOADED: :loaded
        STILL_LOADING: :"still-loading"

        def self?.values: -> ::Array[ContextDev::Models::WebWebScrapeScreenshotResponse::final_dom_state]
      end

      type key_metadata =
        { credits_consumed: Integer, credits_remaining: Integer }

      class KeyMetadata < ContextDev::Internal::Type::BaseModel
        attr_accessor credits_consumed: Integer

        attr_accessor credits_remaining: Integer

        def initialize: (
          credits_consumed: Integer,
          credits_remaining: Integer
        ) -> void

        def to_hash: -> {
          credits_consumed: Integer,
          credits_remaining: Integer
        }
      end
    end
  end
end
