module ContextDev
  module Models
    type web_extract_competitors_response =
      {
        competitors: ::Array[ContextDev::Models::WebExtractCompetitorsResponse::Competitor],
        domain: String,
        request_id: String,
        status: ContextDev::Models::WebExtractCompetitorsResponse::status,
        target: ContextDev::Models::WebExtractCompetitorsResponse::Target,
        key_metadata: ContextDev::Models::WebExtractCompetitorsResponse::KeyMetadata
      }

    class WebExtractCompetitorsResponse < ContextDev::Internal::Type::BaseModel
      attr_accessor competitors: ::Array[ContextDev::Models::WebExtractCompetitorsResponse::Competitor]

      attr_accessor domain: String

      attr_accessor request_id: String

      attr_accessor status: ContextDev::Models::WebExtractCompetitorsResponse::status

      attr_accessor target: ContextDev::Models::WebExtractCompetitorsResponse::Target

      attr_reader key_metadata: ContextDev::Models::WebExtractCompetitorsResponse::KeyMetadata?

      def key_metadata=: (
        ContextDev::Models::WebExtractCompetitorsResponse::KeyMetadata
      ) -> ContextDev::Models::WebExtractCompetitorsResponse::KeyMetadata

      def initialize: (
        competitors: ::Array[ContextDev::Models::WebExtractCompetitorsResponse::Competitor],
        domain: String,
        request_id: String,
        status: ContextDev::Models::WebExtractCompetitorsResponse::status,
        target: ContextDev::Models::WebExtractCompetitorsResponse::Target,
        ?key_metadata: ContextDev::Models::WebExtractCompetitorsResponse::KeyMetadata
      ) -> void

      def to_hash: -> {
        competitors: ::Array[ContextDev::Models::WebExtractCompetitorsResponse::Competitor],
        domain: String,
        request_id: String,
        status: ContextDev::Models::WebExtractCompetitorsResponse::status,
        target: ContextDev::Models::WebExtractCompetitorsResponse::Target,
        key_metadata: ContextDev::Models::WebExtractCompetitorsResponse::KeyMetadata
      }

      type competitor =
        {
          confidence: ContextDev::Models::WebExtractCompetitorsResponse::Competitor::confidence,
          description: String,
          domain: String,
          name: String,
          source_urls: ::Array[String],
          url: String
        }

      class Competitor < ContextDev::Internal::Type::BaseModel
        attr_accessor confidence: ContextDev::Models::WebExtractCompetitorsResponse::Competitor::confidence

        attr_accessor description: String

        attr_accessor domain: String

        attr_accessor name: String

        attr_accessor source_urls: ::Array[String]

        attr_accessor url: String

        def initialize: (
          confidence: ContextDev::Models::WebExtractCompetitorsResponse::Competitor::confidence,
          description: String,
          domain: String,
          name: String,
          source_urls: ::Array[String],
          url: String
        ) -> void

        def to_hash: -> {
          confidence: ContextDev::Models::WebExtractCompetitorsResponse::Competitor::confidence,
          description: String,
          domain: String,
          name: String,
          source_urls: ::Array[String],
          url: String
        }

        type confidence = :high | :medium

        module Confidence
          extend ContextDev::Internal::Type::Enum

          HIGH: :high
          MEDIUM: :medium

          def self?.values: -> ::Array[ContextDev::Models::WebExtractCompetitorsResponse::Competitor::confidence]
        end
      end

      type status = :ok

      module Status
        extend ContextDev::Internal::Type::Enum

        OK: :ok

        def self?.values: -> ::Array[ContextDev::Models::WebExtractCompetitorsResponse::status]
      end

      type target =
        {
          company_name: String,
          field: String,
          field_description: String,
          website_url: String
        }

      class Target < ContextDev::Internal::Type::BaseModel
        attr_accessor company_name: String

        attr_accessor field: String

        attr_accessor field_description: String

        attr_accessor website_url: String

        def initialize: (
          company_name: String,
          field: String,
          field_description: String,
          website_url: String
        ) -> void

        def to_hash: -> {
          company_name: String,
          field: String,
          field_description: String,
          website_url: String
        }
      end

      type key_metadata =
        { credits_consumed: Integer, credits_remaining: Integer }

      class KeyMetadata < ContextDev::Internal::Type::BaseModel
        attr_accessor credits_consumed: Integer

        attr_accessor credits_remaining: Integer

        def initialize: (
          credits_consumed: Integer,
          credits_remaining: Integer
        ) -> void

        def to_hash: -> {
          credits_consumed: Integer,
          credits_remaining: Integer
        }
      end
    end
  end
end
