module ContextDev
  module Models
    type web_search_response =
      {
        cache_metadata: ContextDev::Models::WebSearchResponse::CacheMetadata,
        query: String,
        results: ::Array[ContextDev::Models::WebSearchResponse::Result],
        key_metadata: ContextDev::Models::WebSearchResponse::KeyMetadata
      }

    class WebSearchResponse < ContextDev::Internal::Type::BaseModel
      attr_accessor cache_metadata: ContextDev::Models::WebSearchResponse::CacheMetadata

      attr_accessor query: String

      attr_accessor results: ::Array[ContextDev::Models::WebSearchResponse::Result]

      attr_reader key_metadata: ContextDev::Models::WebSearchResponse::KeyMetadata?

      def key_metadata=: (
        ContextDev::Models::WebSearchResponse::KeyMetadata
      ) -> ContextDev::Models::WebSearchResponse::KeyMetadata

      def initialize: (
        cache_metadata: ContextDev::Models::WebSearchResponse::CacheMetadata,
        query: String,
        results: ::Array[ContextDev::Models::WebSearchResponse::Result],
        ?key_metadata: ContextDev::Models::WebSearchResponse::KeyMetadata
      ) -> void

      def to_hash: -> {
        cache_metadata: ContextDev::Models::WebSearchResponse::CacheMetadata,
        query: String,
        results: ::Array[ContextDev::Models::WebSearchResponse::Result],
        key_metadata: ContextDev::Models::WebSearchResponse::KeyMetadata
      }

      type cache_metadata =
        {
          age_ms: Integer,
          status: ContextDev::Models::WebSearchResponse::CacheMetadata::status
        }

      class CacheMetadata < ContextDev::Internal::Type::BaseModel
        attr_accessor age_ms: Integer

        attr_accessor status: ContextDev::Models::WebSearchResponse::CacheMetadata::status

        def initialize: (
          age_ms: Integer,
          status: ContextDev::Models::WebSearchResponse::CacheMetadata::status
        ) -> void

        def to_hash: -> {
          age_ms: Integer,
          status: ContextDev::Models::WebSearchResponse::CacheMetadata::status
        }

        type status = :hit | :miss | :zdr

        module Status
          extend ContextDev::Internal::Type::Enum

          HIT: :hit
          MISS: :miss
          ZDR: :zdr

          def self?.values: -> ::Array[ContextDev::Models::WebSearchResponse::CacheMetadata::status]
        end
      end

      type result =
        {
          description: String,
          markdown: ContextDev::Models::WebSearchResponse::Result::Markdown,
          relevance: ContextDev::Models::WebSearchResponse::Result::relevance,
          title: String,
          url: String
        }

      class Result < ContextDev::Internal::Type::BaseModel
        attr_accessor description: String

        attr_accessor markdown: ContextDev::Models::WebSearchResponse::Result::Markdown

        attr_accessor relevance: ContextDev::Models::WebSearchResponse::Result::relevance

        attr_accessor title: String

        attr_accessor url: String

        def initialize: (
          description: String,
          markdown: ContextDev::Models::WebSearchResponse::Result::Markdown,
          relevance: ContextDev::Models::WebSearchResponse::Result::relevance,
          title: String,
          url: String
        ) -> void

        def to_hash: -> {
          description: String,
          markdown: ContextDev::Models::WebSearchResponse::Result::Markdown,
          relevance: ContextDev::Models::WebSearchResponse::Result::relevance,
          title: String,
          url: String
        }

        type markdown =
          {
            code: ContextDev::Models::WebSearchResponse::Result::Markdown::code,
            markdown: String?
          }

        class Markdown < ContextDev::Internal::Type::BaseModel
          attr_accessor code: ContextDev::Models::WebSearchResponse::Result::Markdown::code

          attr_accessor markdown: String?

          def initialize: (
            code: ContextDev::Models::WebSearchResponse::Result::Markdown::code,
            markdown: String?
          ) -> void

          def to_hash: -> {
            code: ContextDev::Models::WebSearchResponse::Result::Markdown::code,
            markdown: String?
          }

          type code =
            :SUCCESS
            | :NOT_REQUESTED
            | :TIMEOUT
            | :CONTENT_TOO_LARGE
            | :WEBSITE_ACCESS_ERROR
            | :ERROR

          module Code
            extend ContextDev::Internal::Type::Enum

            SUCCESS: :SUCCESS
            NOT_REQUESTED: :NOT_REQUESTED
            TIMEOUT: :TIMEOUT
            CONTENT_TOO_LARGE: :CONTENT_TOO_LARGE
            WEBSITE_ACCESS_ERROR: :WEBSITE_ACCESS_ERROR
            ERROR: :ERROR

            def self?.values: -> ::Array[ContextDev::Models::WebSearchResponse::Result::Markdown::code]
          end
        end

        type relevance = :high | :medium | :low

        module Relevance
          extend ContextDev::Internal::Type::Enum

          HIGH: :high
          MEDIUM: :medium
          LOW: :low

          def self?.values: -> ::Array[ContextDev::Models::WebSearchResponse::Result::relevance]
        end
      end

      type key_metadata =
        { credits_consumed: Integer, credits_remaining: Integer }

      class KeyMetadata < ContextDev::Internal::Type::BaseModel
        attr_accessor credits_consumed: Integer

        attr_accessor credits_remaining: Integer

        def initialize: (
          credits_consumed: Integer,
          credits_remaining: Integer
        ) -> void

        def to_hash: -> {
          credits_consumed: Integer,
          credits_remaining: Integer
        }
      end
    end
  end
end
