module ContextDev
  module Models
    type web_web_scrape_html_params =
      {
        url: String,
        include_frames: bool,
        max_age_ms: Integer,
        parse_pdf: bool,
        timeout_ms: Integer,
        wait_for_ms: Integer
      }
      & ContextDev::Internal::Type::request_parameters

    class WebWebScrapeHTMLParams < ContextDev::Internal::Type::BaseModel
      extend ContextDev::Internal::Type::RequestParameters::Converter
      include ContextDev::Internal::Type::RequestParameters

      attr_accessor url: String

      attr_reader include_frames: bool?

      def include_frames=: (bool) -> bool

      attr_reader max_age_ms: Integer?

      def max_age_ms=: (Integer) -> Integer

      attr_reader parse_pdf: bool?

      def parse_pdf=: (bool) -> bool

      attr_reader timeout_ms: Integer?

      def timeout_ms=: (Integer) -> Integer

      attr_reader wait_for_ms: Integer?

      def wait_for_ms=: (Integer) -> Integer

      def initialize: (
        url: String,
        ?include_frames: bool,
        ?max_age_ms: Integer,
        ?parse_pdf: bool,
        ?timeout_ms: Integer,
        ?wait_for_ms: Integer,
        ?request_options: ContextDev::request_opts
      ) -> void

      def to_hash: -> {
        url: String,
        include_frames: bool,
        max_age_ms: Integer,
        parse_pdf: bool,
        timeout_ms: Integer,
        wait_for_ms: Integer,
        request_options: ContextDev::RequestOptions
      }
    end
  end
end
