module ContextDev
  module Models
    type web_extract_fonts_response =
      {
        code: Integer,
        domain: String,
        fonts: ::Array[ContextDev::Models::WebExtractFontsResponse::Font],
        status: String,
        font_links: ::Hash[Symbol, ContextDev::Models::WebExtractFontsResponse::FontLink],
        key_metadata: ContextDev::Models::WebExtractFontsResponse::KeyMetadata
      }

    class WebExtractFontsResponse < ContextDev::Internal::Type::BaseModel
      attr_accessor code: Integer

      attr_accessor domain: String

      attr_accessor fonts: ::Array[ContextDev::Models::WebExtractFontsResponse::Font]

      attr_accessor status: String

      attr_reader font_links: ::Hash[Symbol, ContextDev::Models::WebExtractFontsResponse::FontLink]?

      def font_links=: (
        ::Hash[Symbol, ContextDev::Models::WebExtractFontsResponse::FontLink]
      ) -> ::Hash[Symbol, ContextDev::Models::WebExtractFontsResponse::FontLink]

      attr_reader key_metadata: ContextDev::Models::WebExtractFontsResponse::KeyMetadata?

      def key_metadata=: (
        ContextDev::Models::WebExtractFontsResponse::KeyMetadata
      ) -> ContextDev::Models::WebExtractFontsResponse::KeyMetadata

      def initialize: (
        code: Integer,
        domain: String,
        fonts: ::Array[ContextDev::Models::WebExtractFontsResponse::Font],
        status: String,
        ?font_links: ::Hash[Symbol, ContextDev::Models::WebExtractFontsResponse::FontLink],
        ?key_metadata: ContextDev::Models::WebExtractFontsResponse::KeyMetadata
      ) -> void

      def to_hash: -> {
        code: Integer,
        domain: String,
        fonts: ::Array[ContextDev::Models::WebExtractFontsResponse::Font],
        status: String,
        font_links: ::Hash[Symbol, ContextDev::Models::WebExtractFontsResponse::FontLink],
        key_metadata: ContextDev::Models::WebExtractFontsResponse::KeyMetadata
      }

      type font =
        {
          fallbacks: ::Array[String],
          font: String,
          num_elements: Float,
          num_words: Float,
          percent_elements: Float,
          percent_words: Float,
          uses: ::Array[String]
        }

      class Font < ContextDev::Internal::Type::BaseModel
        attr_accessor fallbacks: ::Array[String]

        attr_accessor font: String

        attr_accessor num_elements: Float

        attr_accessor num_words: Float

        attr_accessor percent_elements: Float

        attr_accessor percent_words: Float

        attr_accessor uses: ::Array[String]

        def initialize: (
          fallbacks: ::Array[String],
          font: String,
          num_elements: Float,
          num_words: Float,
          percent_elements: Float,
          percent_words: Float,
          uses: ::Array[String]
        ) -> void

        def to_hash: -> {
          fallbacks: ::Array[String],
          font: String,
          num_elements: Float,
          num_words: Float,
          percent_elements: Float,
          percent_words: Float,
          uses: ::Array[String]
        }
      end

      type font_link =
        {
          files: ::Hash[Symbol, String],
          type: ContextDev::Models::WebExtractFontsResponse::FontLink::type_,
          category: String,
          display_name: String
        }

      class FontLink < ContextDev::Internal::Type::BaseModel
        attr_accessor files: ::Hash[Symbol, String]

        attr_accessor type: ContextDev::Models::WebExtractFontsResponse::FontLink::type_

        attr_reader category: String?

        def category=: (String) -> String

        attr_reader display_name: String?

        def display_name=: (String) -> String

        def initialize: (
          files: ::Hash[Symbol, String],
          type: ContextDev::Models::WebExtractFontsResponse::FontLink::type_,
          ?category: String,
          ?display_name: String
        ) -> void

        def to_hash: -> {
          files: ::Hash[Symbol, String],
          type: ContextDev::Models::WebExtractFontsResponse::FontLink::type_,
          category: String,
          display_name: String
        }

        type type_ = :google | :custom

        module Type
          extend ContextDev::Internal::Type::Enum

          GOOGLE: :google
          CUSTOM: :custom

          def self?.values: -> ::Array[ContextDev::Models::WebExtractFontsResponse::FontLink::type_]
        end
      end

      type key_metadata =
        { credits_consumed: Integer, credits_remaining: Integer }

      class KeyMetadata < ContextDev::Internal::Type::BaseModel
        attr_accessor credits_consumed: Integer

        attr_accessor credits_remaining: Integer

        def initialize: (
          credits_consumed: Integer,
          credits_remaining: Integer
        ) -> void

        def to_hash: -> {
          credits_consumed: Integer,
          credits_remaining: Integer
        }
      end
    end
  end
end
