module ContextDev
  module Models
    type web_web_scrape_sitemap_params =
      {
        domain: String,
        headers: ::Hash[Symbol, String],
        max_links: Integer,
        timeout_ms: Integer,
        url_regex: String
      }
      & ContextDev::Internal::Type::request_parameters

    class WebWebScrapeSitemapParams < ContextDev::Internal::Type::BaseModel
      extend ContextDev::Internal::Type::RequestParameters::Converter
      include ContextDev::Internal::Type::RequestParameters

      attr_accessor domain: String

      attr_reader headers: ::Hash[Symbol, String]?

      def headers=: (::Hash[Symbol, String]) -> ::Hash[Symbol, String]

      attr_reader max_links: Integer?

      def max_links=: (Integer) -> Integer

      attr_reader timeout_ms: Integer?

      def timeout_ms=: (Integer) -> Integer

      attr_reader url_regex: String?

      def url_regex=: (String) -> String

      def initialize: (
        domain: String,
        ?headers: ::Hash[Symbol, String],
        ?max_links: Integer,
        ?timeout_ms: Integer,
        ?url_regex: String,
        ?request_options: ContextDev::request_opts
      ) -> void

      def to_hash: -> {
        domain: String,
        headers: ::Hash[Symbol, String],
        max_links: Integer,
        timeout_ms: Integer,
        url_regex: String,
        request_options: ContextDev::RequestOptions
      }
    end
  end
end
