module ContextDev
  module Models
    type web_web_scrape_images_response =
      {
        images: ::Array[ContextDev::Models::WebWebScrapeImagesResponse::Image],
        success: ContextDev::Models::WebWebScrapeImagesResponse::success,
        url: String
      }

    class WebWebScrapeImagesResponse < ContextDev::Internal::Type::BaseModel
      attr_accessor images: ::Array[ContextDev::Models::WebWebScrapeImagesResponse::Image]

      attr_accessor success: ContextDev::Models::WebWebScrapeImagesResponse::success

      attr_accessor url: String

      def initialize: (
        images: ::Array[ContextDev::Models::WebWebScrapeImagesResponse::Image],
        success: ContextDev::Models::WebWebScrapeImagesResponse::success,
        url: String
      ) -> void

      def to_hash: -> {
        images: ::Array[ContextDev::Models::WebWebScrapeImagesResponse::Image],
        success: ContextDev::Models::WebWebScrapeImagesResponse::success,
        url: String
      }

      type image =
        {
          alt: String?,
          element: ContextDev::Models::WebWebScrapeImagesResponse::Image::element,
          src: String,
          type: ContextDev::Models::WebWebScrapeImagesResponse::Image::type_,
          enrichment: ContextDev::Models::WebWebScrapeImagesResponse::Image::Enrichment
        }

      class Image < ContextDev::Internal::Type::BaseModel
        attr_accessor alt: String?

        attr_accessor element: ContextDev::Models::WebWebScrapeImagesResponse::Image::element

        attr_accessor src: String

        attr_accessor type: ContextDev::Models::WebWebScrapeImagesResponse::Image::type_

        attr_reader enrichment: ContextDev::Models::WebWebScrapeImagesResponse::Image::Enrichment?

        def enrichment=: (
          ContextDev::Models::WebWebScrapeImagesResponse::Image::Enrichment
        ) -> ContextDev::Models::WebWebScrapeImagesResponse::Image::Enrichment

        def initialize: (
          alt: String?,
          element: ContextDev::Models::WebWebScrapeImagesResponse::Image::element,
          src: String,
          type: ContextDev::Models::WebWebScrapeImagesResponse::Image::type_,
          ?enrichment: ContextDev::Models::WebWebScrapeImagesResponse::Image::Enrichment
        ) -> void

        def to_hash: -> {
          alt: String?,
          element: ContextDev::Models::WebWebScrapeImagesResponse::Image::element,
          src: String,
          type: ContextDev::Models::WebWebScrapeImagesResponse::Image::type_,
          enrichment: ContextDev::Models::WebWebScrapeImagesResponse::Image::Enrichment
        }

        type element =
          :img
          | :svg
          | :link
          | :source
          | :video
          | :css
          | :object
          | :meta
          | :background

        module Element
          extend ContextDev::Internal::Type::Enum

          IMG: :img
          SVG: :svg
          LINK: :link
          SOURCE: :source
          VIDEO: :video
          CSS: :css
          OBJECT: :object
          META: :meta
          BACKGROUND: :background

          def self?.values: -> ::Array[ContextDev::Models::WebWebScrapeImagesResponse::Image::element]
        end

        type type_ = :url | :html | :base64

        module Type
          extend ContextDev::Internal::Type::Enum

          URL: :url
          HTML: :html
          BASE64: :base64

          def self?.values: -> ::Array[ContextDev::Models::WebWebScrapeImagesResponse::Image::type_]
        end

        type enrichment =
          {
            height: Integer,
            mimetype: String,
            type: ContextDev::Models::WebWebScrapeImagesResponse::Image::Enrichment::type_,
            url: String,
            width: Integer
          }

        class Enrichment < ContextDev::Internal::Type::BaseModel
          attr_reader height: Integer?

          def height=: (Integer) -> Integer

          attr_reader mimetype: String?

          def mimetype=: (String) -> String

          attr_reader type: ContextDev::Models::WebWebScrapeImagesResponse::Image::Enrichment::type_?

          def type=: (
            ContextDev::Models::WebWebScrapeImagesResponse::Image::Enrichment::type_
          ) -> ContextDev::Models::WebWebScrapeImagesResponse::Image::Enrichment::type_

          attr_reader url: String?

          def url=: (String) -> String

          attr_reader width: Integer?

          def width=: (Integer) -> Integer

          def initialize: (
            ?height: Integer,
            ?mimetype: String,
            ?type: ContextDev::Models::WebWebScrapeImagesResponse::Image::Enrichment::type_,
            ?url: String,
            ?width: Integer
          ) -> void

          def to_hash: -> {
            height: Integer,
            mimetype: String,
            type: ContextDev::Models::WebWebScrapeImagesResponse::Image::Enrichment::type_,
            url: String,
            width: Integer
          }

          type type_ =
            :photography
            | :illustration
            | :logo
            | :wordmark
            | :icon
            | :pattern
            | :graphic
            | :other

          module Type
            extend ContextDev::Internal::Type::Enum

            PHOTOGRAPHY: :photography
            ILLUSTRATION: :illustration
            LOGO: :logo
            WORDMARK: :wordmark
            ICON: :icon
            PATTERN: :pattern
            GRAPHIC: :graphic
            OTHER: :other

            def self?.values: -> ::Array[ContextDev::Models::WebWebScrapeImagesResponse::Image::Enrichment::type_]
          end
        end
      end

      type success = true

      module Success
        extend ContextDev::Internal::Type::Enum

        TRUE: true

        def self?.values: -> ::Array[ContextDev::Models::WebWebScrapeImagesResponse::success]
      end
    end
  end
end
