module ContextDev
  module Models
    type web_extract_styleguide_response =
      {
        cache_metadata: ContextDev::Models::WebExtractStyleguideResponse::CacheMetadata,
        code: Integer,
        domain: String,
        key_metadata: ContextDev::Models::WebExtractStyleguideResponse::KeyMetadata,
        status: String,
        styleguide: ContextDev::Models::WebExtractStyleguideResponse::Styleguide
      }

    class WebExtractStyleguideResponse < ContextDev::Internal::Type::BaseModel
      attr_accessor cache_metadata: ContextDev::Models::WebExtractStyleguideResponse::CacheMetadata

      attr_reader code: Integer?

      def code=: (Integer) -> Integer

      attr_reader domain: String?

      def domain=: (String) -> String

      attr_reader key_metadata: ContextDev::Models::WebExtractStyleguideResponse::KeyMetadata?

      def key_metadata=: (
        ContextDev::Models::WebExtractStyleguideResponse::KeyMetadata
      ) -> ContextDev::Models::WebExtractStyleguideResponse::KeyMetadata

      attr_reader status: String?

      def status=: (String) -> String

      attr_reader styleguide: ContextDev::Models::WebExtractStyleguideResponse::Styleguide?

      def styleguide=: (
        ContextDev::Models::WebExtractStyleguideResponse::Styleguide
      ) -> ContextDev::Models::WebExtractStyleguideResponse::Styleguide

      def initialize: (
        cache_metadata: ContextDev::Models::WebExtractStyleguideResponse::CacheMetadata,
        ?code: Integer,
        ?domain: String,
        ?key_metadata: ContextDev::Models::WebExtractStyleguideResponse::KeyMetadata,
        ?status: String,
        ?styleguide: ContextDev::Models::WebExtractStyleguideResponse::Styleguide
      ) -> void

      def to_hash: -> {
        cache_metadata: ContextDev::Models::WebExtractStyleguideResponse::CacheMetadata,
        code: Integer,
        domain: String,
        key_metadata: ContextDev::Models::WebExtractStyleguideResponse::KeyMetadata,
        status: String,
        styleguide: ContextDev::Models::WebExtractStyleguideResponse::Styleguide
      }

      type cache_metadata =
        {
          age_ms: Integer,
          status: ContextDev::Models::WebExtractStyleguideResponse::CacheMetadata::status
        }

      class CacheMetadata < ContextDev::Internal::Type::BaseModel
        attr_accessor age_ms: Integer

        attr_accessor status: ContextDev::Models::WebExtractStyleguideResponse::CacheMetadata::status

        def initialize: (
          age_ms: Integer,
          status: ContextDev::Models::WebExtractStyleguideResponse::CacheMetadata::status
        ) -> void

        def to_hash: -> {
          age_ms: Integer,
          status: ContextDev::Models::WebExtractStyleguideResponse::CacheMetadata::status
        }

        type status = :hit | :miss | :zdr

        module Status
          extend ContextDev::Internal::Type::Enum

          HIT: :hit
          MISS: :miss
          ZDR: :zdr

          def self?.values: -> ::Array[ContextDev::Models::WebExtractStyleguideResponse::CacheMetadata::status]
        end
      end

      type key_metadata =
        { credits_consumed: Integer, credits_remaining: Integer }

      class KeyMetadata < ContextDev::Internal::Type::BaseModel
        attr_accessor credits_consumed: Integer

        attr_accessor credits_remaining: Integer

        def initialize: (
          credits_consumed: Integer,
          credits_remaining: Integer
        ) -> void

        def to_hash: -> {
          credits_consumed: Integer,
          credits_remaining: Integer
        }
      end

      type styleguide =
        {
          colors: ContextDev::Models::WebExtractStyleguideResponse::Styleguide::Colors,
          components: ContextDev::Models::WebExtractStyleguideResponse::Styleguide::Components,
          element_spacing: ContextDev::Models::WebExtractStyleguideResponse::Styleguide::ElementSpacing,
          font_links: ::Hash[Symbol, ContextDev::Models::WebExtractStyleguideResponse::Styleguide::FontLink],
          mode: ContextDev::Models::WebExtractStyleguideResponse::Styleguide::mode,
          shadows: ContextDev::Models::WebExtractStyleguideResponse::Styleguide::Shadows,
          typography: ContextDev::Models::WebExtractStyleguideResponse::Styleguide::Typography
        }

      class Styleguide < ContextDev::Internal::Type::BaseModel
        attr_accessor colors: ContextDev::Models::WebExtractStyleguideResponse::Styleguide::Colors

        attr_accessor components: ContextDev::Models::WebExtractStyleguideResponse::Styleguide::Components

        attr_accessor element_spacing: ContextDev::Models::WebExtractStyleguideResponse::Styleguide::ElementSpacing

        attr_accessor font_links: ::Hash[Symbol, ContextDev::Models::WebExtractStyleguideResponse::Styleguide::FontLink]

        attr_accessor mode: ContextDev::Models::WebExtractStyleguideResponse::Styleguide::mode

        attr_accessor shadows: ContextDev::Models::WebExtractStyleguideResponse::Styleguide::Shadows

        attr_accessor typography: ContextDev::Models::WebExtractStyleguideResponse::Styleguide::Typography

        def initialize: (
          colors: ContextDev::Models::WebExtractStyleguideResponse::Styleguide::Colors,
          components: ContextDev::Models::WebExtractStyleguideResponse::Styleguide::Components,
          element_spacing: ContextDev::Models::WebExtractStyleguideResponse::Styleguide::ElementSpacing,
          font_links: ::Hash[Symbol, ContextDev::Models::WebExtractStyleguideResponse::Styleguide::FontLink],
          mode: ContextDev::Models::WebExtractStyleguideResponse::Styleguide::mode,
          shadows: ContextDev::Models::WebExtractStyleguideResponse::Styleguide::Shadows,
          typography: ContextDev::Models::WebExtractStyleguideResponse::Styleguide::Typography
        ) -> void

        def to_hash: -> {
          colors: ContextDev::Models::WebExtractStyleguideResponse::Styleguide::Colors,
          components: ContextDev::Models::WebExtractStyleguideResponse::Styleguide::Components,
          element_spacing: ContextDev::Models::WebExtractStyleguideResponse::Styleguide::ElementSpacing,
          font_links: ::Hash[Symbol, ContextDev::Models::WebExtractStyleguideResponse::Styleguide::FontLink],
          mode: ContextDev::Models::WebExtractStyleguideResponse::Styleguide::mode,
          shadows: ContextDev::Models::WebExtractStyleguideResponse::Styleguide::Shadows,
          typography: ContextDev::Models::WebExtractStyleguideResponse::Styleguide::Typography
        }

        type colors = { accent: String, background: String, text: String }

        class Colors < ContextDev::Internal::Type::BaseModel
          attr_accessor accent: String

          attr_accessor background: String

          attr_accessor text: String

          def initialize: (
            accent: String,
            background: String,
            text: String
          ) -> void

          def to_hash: -> { accent: String, background: String, text: String }
        end

        type components =
          {
            button: ContextDev::Models::WebExtractStyleguideResponse::Styleguide::Components::Button,
            card: ContextDev::Models::WebExtractStyleguideResponse::Styleguide::Components::Card
          }

        class Components < ContextDev::Internal::Type::BaseModel
          attr_accessor button: ContextDev::Models::WebExtractStyleguideResponse::Styleguide::Components::Button

          attr_reader card: ContextDev::Models::WebExtractStyleguideResponse::Styleguide::Components::Card?

          def card=: (
            ContextDev::Models::WebExtractStyleguideResponse::Styleguide::Components::Card
          ) -> ContextDev::Models::WebExtractStyleguideResponse::Styleguide::Components::Card

          def initialize: (
            button: ContextDev::Models::WebExtractStyleguideResponse::Styleguide::Components::Button,
            ?card: ContextDev::Models::WebExtractStyleguideResponse::Styleguide::Components::Card
          ) -> void

          def to_hash: -> {
            button: ContextDev::Models::WebExtractStyleguideResponse::Styleguide::Components::Button,
            card: ContextDev::Models::WebExtractStyleguideResponse::Styleguide::Components::Card
          }

          type button =
            {
              link: ContextDev::Models::WebExtractStyleguideResponse::Styleguide::Components::Button::Link,
              primary: ContextDev::Models::WebExtractStyleguideResponse::Styleguide::Components::Button::Primary,
              secondary: ContextDev::Models::WebExtractStyleguideResponse::Styleguide::Components::Button::Secondary
            }

          class Button < ContextDev::Internal::Type::BaseModel
            attr_reader link: ContextDev::Models::WebExtractStyleguideResponse::Styleguide::Components::Button::Link?

            def link=: (
              ContextDev::Models::WebExtractStyleguideResponse::Styleguide::Components::Button::Link
            ) -> ContextDev::Models::WebExtractStyleguideResponse::Styleguide::Components::Button::Link

            attr_reader primary: ContextDev::Models::WebExtractStyleguideResponse::Styleguide::Components::Button::Primary?

            def primary=: (
              ContextDev::Models::WebExtractStyleguideResponse::Styleguide::Components::Button::Primary
            ) -> ContextDev::Models::WebExtractStyleguideResponse::Styleguide::Components::Button::Primary

            attr_reader secondary: ContextDev::Models::WebExtractStyleguideResponse::Styleguide::Components::Button::Secondary?

            def secondary=: (
              ContextDev::Models::WebExtractStyleguideResponse::Styleguide::Components::Button::Secondary
            ) -> ContextDev::Models::WebExtractStyleguideResponse::Styleguide::Components::Button::Secondary

            def initialize: (
              ?link: ContextDev::Models::WebExtractStyleguideResponse::Styleguide::Components::Button::Link,
              ?primary: ContextDev::Models::WebExtractStyleguideResponse::Styleguide::Components::Button::Primary,
              ?secondary: ContextDev::Models::WebExtractStyleguideResponse::Styleguide::Components::Button::Secondary
            ) -> void

            def to_hash: -> {
              link: ContextDev::Models::WebExtractStyleguideResponse::Styleguide::Components::Button::Link,
              primary: ContextDev::Models::WebExtractStyleguideResponse::Styleguide::Components::Button::Primary,
              secondary: ContextDev::Models::WebExtractStyleguideResponse::Styleguide::Components::Button::Secondary
            }

            type link =
              {
                background_color: String,
                border_color: String,
                border_radius: String,
                border_style: String,
                border_width: String,
                box_shadow: String,
                color: String,
                css: String,
                font_size: String,
                font_weight: Float,
                min_height: String,
                min_width: String,
                padding: String,
                text_decoration: String,
                font_fallbacks: ::Array[String],
                font_family: String,
                text_decoration_color: String
              }

            class Link < ContextDev::Internal::Type::BaseModel
              attr_accessor background_color: String

              attr_accessor border_color: String

              attr_accessor border_radius: String

              attr_accessor border_style: String

              attr_accessor border_width: String

              attr_accessor box_shadow: String

              attr_accessor color: String

              attr_accessor css: String

              attr_accessor font_size: String

              attr_accessor font_weight: Float

              attr_accessor min_height: String

              attr_accessor min_width: String

              attr_accessor padding: String

              attr_accessor text_decoration: String

              attr_reader font_fallbacks: ::Array[String]?

              def font_fallbacks=: (::Array[String]) -> ::Array[String]

              attr_reader font_family: String?

              def font_family=: (String) -> String

              attr_reader text_decoration_color: String?

              def text_decoration_color=: (String) -> String

              def initialize: (
                background_color: String,
                border_color: String,
                border_radius: String,
                border_style: String,
                border_width: String,
                box_shadow: String,
                color: String,
                css: String,
                font_size: String,
                font_weight: Float,
                min_height: String,
                min_width: String,
                padding: String,
                text_decoration: String,
                ?font_fallbacks: ::Array[String],
                ?font_family: String,
                ?text_decoration_color: String
              ) -> void

              def to_hash: -> {
                background_color: String,
                border_color: String,
                border_radius: String,
                border_style: String,
                border_width: String,
                box_shadow: String,
                color: String,
                css: String,
                font_size: String,
                font_weight: Float,
                min_height: String,
                min_width: String,
                padding: String,
                text_decoration: String,
                font_fallbacks: ::Array[String],
                font_family: String,
                text_decoration_color: String
              }
            end

            type primary =
              {
                background_color: String,
                border_color: String,
                border_radius: String,
                border_style: String,
                border_width: String,
                box_shadow: String,
                color: String,
                css: String,
                font_size: String,
                font_weight: Float,
                min_height: String,
                min_width: String,
                padding: String,
                text_decoration: String,
                font_fallbacks: ::Array[String],
                font_family: String,
                text_decoration_color: String
              }

            class Primary < ContextDev::Internal::Type::BaseModel
              attr_accessor background_color: String

              attr_accessor border_color: String

              attr_accessor border_radius: String

              attr_accessor border_style: String

              attr_accessor border_width: String

              attr_accessor box_shadow: String

              attr_accessor color: String

              attr_accessor css: String

              attr_accessor font_size: String

              attr_accessor font_weight: Float

              attr_accessor min_height: String

              attr_accessor min_width: String

              attr_accessor padding: String

              attr_accessor text_decoration: String

              attr_reader font_fallbacks: ::Array[String]?

              def font_fallbacks=: (::Array[String]) -> ::Array[String]

              attr_reader font_family: String?

              def font_family=: (String) -> String

              attr_reader text_decoration_color: String?

              def text_decoration_color=: (String) -> String

              def initialize: (
                background_color: String,
                border_color: String,
                border_radius: String,
                border_style: String,
                border_width: String,
                box_shadow: String,
                color: String,
                css: String,
                font_size: String,
                font_weight: Float,
                min_height: String,
                min_width: String,
                padding: String,
                text_decoration: String,
                ?font_fallbacks: ::Array[String],
                ?font_family: String,
                ?text_decoration_color: String
              ) -> void

              def to_hash: -> {
                background_color: String,
                border_color: String,
                border_radius: String,
                border_style: String,
                border_width: String,
                box_shadow: String,
                color: String,
                css: String,
                font_size: String,
                font_weight: Float,
                min_height: String,
                min_width: String,
                padding: String,
                text_decoration: String,
                font_fallbacks: ::Array[String],
                font_family: String,
                text_decoration_color: String
              }
            end

            type secondary =
              {
                background_color: String,
                border_color: String,
                border_radius: String,
                border_style: String,
                border_width: String,
                box_shadow: String,
                color: String,
                css: String,
                font_size: String,
                font_weight: Float,
                min_height: String,
                min_width: String,
                padding: String,
                text_decoration: String,
                font_fallbacks: ::Array[String],
                font_family: String,
                text_decoration_color: String
              }

            class Secondary < ContextDev::Internal::Type::BaseModel
              attr_accessor background_color: String

              attr_accessor border_color: String

              attr_accessor border_radius: String

              attr_accessor border_style: String

              attr_accessor border_width: String

              attr_accessor box_shadow: String

              attr_accessor color: String

              attr_accessor css: String

              attr_accessor font_size: String

              attr_accessor font_weight: Float

              attr_accessor min_height: String

              attr_accessor min_width: String

              attr_accessor padding: String

              attr_accessor text_decoration: String

              attr_reader font_fallbacks: ::Array[String]?

              def font_fallbacks=: (::Array[String]) -> ::Array[String]

              attr_reader font_family: String?

              def font_family=: (String) -> String

              attr_reader text_decoration_color: String?

              def text_decoration_color=: (String) -> String

              def initialize: (
                background_color: String,
                border_color: String,
                border_radius: String,
                border_style: String,
                border_width: String,
                box_shadow: String,
                color: String,
                css: String,
                font_size: String,
                font_weight: Float,
                min_height: String,
                min_width: String,
                padding: String,
                text_decoration: String,
                ?font_fallbacks: ::Array[String],
                ?font_family: String,
                ?text_decoration_color: String
              ) -> void

              def to_hash: -> {
                background_color: String,
                border_color: String,
                border_radius: String,
                border_style: String,
                border_width: String,
                box_shadow: String,
                color: String,
                css: String,
                font_size: String,
                font_weight: Float,
                min_height: String,
                min_width: String,
                padding: String,
                text_decoration: String,
                font_fallbacks: ::Array[String],
                font_family: String,
                text_decoration_color: String
              }
            end
          end

          type card =
            {
              background_color: String,
              border_color: String,
              border_radius: String,
              border_style: String,
              border_width: String,
              box_shadow: String,
              css: String,
              padding: String,
              text_color: String
            }

          class Card < ContextDev::Internal::Type::BaseModel
            attr_accessor background_color: String

            attr_accessor border_color: String

            attr_accessor border_radius: String

            attr_accessor border_style: String

            attr_accessor border_width: String

            attr_accessor box_shadow: String

            attr_accessor css: String

            attr_accessor padding: String

            attr_accessor text_color: String

            def initialize: (
              background_color: String,
              border_color: String,
              border_radius: String,
              border_style: String,
              border_width: String,
              box_shadow: String,
              css: String,
              padding: String,
              text_color: String
            ) -> void

            def to_hash: -> {
              background_color: String,
              border_color: String,
              border_radius: String,
              border_style: String,
              border_width: String,
              box_shadow: String,
              css: String,
              padding: String,
              text_color: String
            }
          end
        end

        type element_spacing =
          { lg: String, md: String, sm: String, xl: String, xs: String }

        class ElementSpacing < ContextDev::Internal::Type::BaseModel
          attr_accessor lg: String

          attr_accessor md: String

          attr_accessor sm: String

          attr_accessor xl: String

          attr_accessor xs: String

          def initialize: (
            lg: String,
            md: String,
            sm: String,
            xl: String,
            xs: String
          ) -> void

          def to_hash: -> {
            lg: String,
            md: String,
            sm: String,
            xl: String,
            xs: String
          }
        end

        type font_link =
          {
            files: ::Hash[Symbol, String],
            type: ContextDev::Models::WebExtractStyleguideResponse::Styleguide::FontLink::type_,
            category: String,
            display_name: String
          }

        class FontLink < ContextDev::Internal::Type::BaseModel
          attr_accessor files: ::Hash[Symbol, String]

          attr_accessor type: ContextDev::Models::WebExtractStyleguideResponse::Styleguide::FontLink::type_

          attr_reader category: String?

          def category=: (String) -> String

          attr_reader display_name: String?

          def display_name=: (String) -> String

          def initialize: (
            files: ::Hash[Symbol, String],
            type: ContextDev::Models::WebExtractStyleguideResponse::Styleguide::FontLink::type_,
            ?category: String,
            ?display_name: String
          ) -> void

          def to_hash: -> {
            files: ::Hash[Symbol, String],
            type: ContextDev::Models::WebExtractStyleguideResponse::Styleguide::FontLink::type_,
            category: String,
            display_name: String
          }

          type type_ = :google | :custom

          module Type
            extend ContextDev::Internal::Type::Enum

            GOOGLE: :google
            CUSTOM: :custom

            def self?.values: -> ::Array[ContextDev::Models::WebExtractStyleguideResponse::Styleguide::FontLink::type_]
          end
        end

        type mode = :light | :dark

        module Mode
          extend ContextDev::Internal::Type::Enum

          LIGHT: :light
          DARK: :dark

          def self?.values: -> ::Array[ContextDev::Models::WebExtractStyleguideResponse::Styleguide::mode]
        end

        type shadows =
          { inner: String, lg: String, md: String, sm: String, xl: String }

        class Shadows < ContextDev::Internal::Type::BaseModel
          attr_accessor inner: String

          attr_accessor lg: String

          attr_accessor md: String

          attr_accessor sm: String

          attr_accessor xl: String

          def initialize: (
            inner: String,
            lg: String,
            md: String,
            sm: String,
            xl: String
          ) -> void

          def to_hash: -> {
            inner: String,
            lg: String,
            md: String,
            sm: String,
            xl: String
          }
        end

        type typography =
          {
            headings: ContextDev::Models::WebExtractStyleguideResponse::Styleguide::Typography::Headings,
            p_: ContextDev::Models::WebExtractStyleguideResponse::Styleguide::Typography::P
          }

        class Typography < ContextDev::Internal::Type::BaseModel
          attr_accessor headings: ContextDev::Models::WebExtractStyleguideResponse::Styleguide::Typography::Headings

          attr_reader p_: ContextDev::Models::WebExtractStyleguideResponse::Styleguide::Typography::P?

          def p_=: (
            ContextDev::Models::WebExtractStyleguideResponse::Styleguide::Typography::P
          ) -> ContextDev::Models::WebExtractStyleguideResponse::Styleguide::Typography::P

          def initialize: (
            headings: ContextDev::Models::WebExtractStyleguideResponse::Styleguide::Typography::Headings,
            ?p_: ContextDev::Models::WebExtractStyleguideResponse::Styleguide::Typography::P
          ) -> void

          def to_hash: -> {
            headings: ContextDev::Models::WebExtractStyleguideResponse::Styleguide::Typography::Headings,
            p_: ContextDev::Models::WebExtractStyleguideResponse::Styleguide::Typography::P
          }

          type headings =
            {
              :h1 => ContextDev::Models::WebExtractStyleguideResponse::Styleguide::Typography::Headings::H1,
              :h2 => ContextDev::Models::WebExtractStyleguideResponse::Styleguide::Typography::Headings::H2,
              :h3 => ContextDev::Models::WebExtractStyleguideResponse::Styleguide::Typography::Headings::H3,
              :h4 => ContextDev::Models::WebExtractStyleguideResponse::Styleguide::Typography::Headings::H4
            }

          class Headings < ContextDev::Internal::Type::BaseModel
            attr_reader h1: ContextDev::Models::WebExtractStyleguideResponse::Styleguide::Typography::Headings::H1?

            def h1=: (
              ContextDev::Models::WebExtractStyleguideResponse::Styleguide::Typography::Headings::H1
            ) -> ContextDev::Models::WebExtractStyleguideResponse::Styleguide::Typography::Headings::H1

            attr_reader h2: ContextDev::Models::WebExtractStyleguideResponse::Styleguide::Typography::Headings::H2?

            def h2=: (
              ContextDev::Models::WebExtractStyleguideResponse::Styleguide::Typography::Headings::H2
            ) -> ContextDev::Models::WebExtractStyleguideResponse::Styleguide::Typography::Headings::H2

            attr_reader h3: ContextDev::Models::WebExtractStyleguideResponse::Styleguide::Typography::Headings::H3?

            def h3=: (
              ContextDev::Models::WebExtractStyleguideResponse::Styleguide::Typography::Headings::H3
            ) -> ContextDev::Models::WebExtractStyleguideResponse::Styleguide::Typography::Headings::H3

            attr_reader h4: ContextDev::Models::WebExtractStyleguideResponse::Styleguide::Typography::Headings::H4?

            def h4=: (
              ContextDev::Models::WebExtractStyleguideResponse::Styleguide::Typography::Headings::H4
            ) -> ContextDev::Models::WebExtractStyleguideResponse::Styleguide::Typography::Headings::H4

            def initialize: (
              ?h1: ContextDev::Models::WebExtractStyleguideResponse::Styleguide::Typography::Headings::H1,
              ?h2: ContextDev::Models::WebExtractStyleguideResponse::Styleguide::Typography::Headings::H2,
              ?h3: ContextDev::Models::WebExtractStyleguideResponse::Styleguide::Typography::Headings::H3,
              ?h4: ContextDev::Models::WebExtractStyleguideResponse::Styleguide::Typography::Headings::H4
            ) -> void

            def to_hash: -> {
              :h1 => ContextDev::Models::WebExtractStyleguideResponse::Styleguide::Typography::Headings::H1,
              :h2 => ContextDev::Models::WebExtractStyleguideResponse::Styleguide::Typography::Headings::H2,
              :h3 => ContextDev::Models::WebExtractStyleguideResponse::Styleguide::Typography::Headings::H3,
              :h4 => ContextDev::Models::WebExtractStyleguideResponse::Styleguide::Typography::Headings::H4
            }

            type h1 =
              {
                font_fallbacks: ::Array[String],
                font_family: String,
                font_size: String,
                font_weight: Float,
                letter_spacing: String,
                line_height: String
              }

            class H1 < ContextDev::Internal::Type::BaseModel
              attr_accessor font_fallbacks: ::Array[String]

              attr_accessor font_family: String

              attr_accessor font_size: String

              attr_accessor font_weight: Float

              attr_accessor letter_spacing: String

              attr_accessor line_height: String

              def initialize: (
                font_fallbacks: ::Array[String],
                font_family: String,
                font_size: String,
                font_weight: Float,
                letter_spacing: String,
                line_height: String
              ) -> void

              def to_hash: -> {
                font_fallbacks: ::Array[String],
                font_family: String,
                font_size: String,
                font_weight: Float,
                letter_spacing: String,
                line_height: String
              }
            end

            type h2 =
              {
                font_fallbacks: ::Array[String],
                font_family: String,
                font_size: String,
                font_weight: Float,
                letter_spacing: String,
                line_height: String
              }

            class H2 < ContextDev::Internal::Type::BaseModel
              attr_accessor font_fallbacks: ::Array[String]

              attr_accessor font_family: String

              attr_accessor font_size: String

              attr_accessor font_weight: Float

              attr_accessor letter_spacing: String

              attr_accessor line_height: String

              def initialize: (
                font_fallbacks: ::Array[String],
                font_family: String,
                font_size: String,
                font_weight: Float,
                letter_spacing: String,
                line_height: String
              ) -> void

              def to_hash: -> {
                font_fallbacks: ::Array[String],
                font_family: String,
                font_size: String,
                font_weight: Float,
                letter_spacing: String,
                line_height: String
              }
            end

            type h3 =
              {
                font_fallbacks: ::Array[String],
                font_family: String,
                font_size: String,
                font_weight: Float,
                letter_spacing: String,
                line_height: String
              }

            class H3 < ContextDev::Internal::Type::BaseModel
              attr_accessor font_fallbacks: ::Array[String]

              attr_accessor font_family: String

              attr_accessor font_size: String

              attr_accessor font_weight: Float

              attr_accessor letter_spacing: String

              attr_accessor line_height: String

              def initialize: (
                font_fallbacks: ::Array[String],
                font_family: String,
                font_size: String,
                font_weight: Float,
                letter_spacing: String,
                line_height: String
              ) -> void

              def to_hash: -> {
                font_fallbacks: ::Array[String],
                font_family: String,
                font_size: String,
                font_weight: Float,
                letter_spacing: String,
                line_height: String
              }
            end

            type h4 =
              {
                font_fallbacks: ::Array[String],
                font_family: String,
                font_size: String,
                font_weight: Float,
                letter_spacing: String,
                line_height: String
              }

            class H4 < ContextDev::Internal::Type::BaseModel
              attr_accessor font_fallbacks: ::Array[String]

              attr_accessor font_family: String

              attr_accessor font_size: String

              attr_accessor font_weight: Float

              attr_accessor letter_spacing: String

              attr_accessor line_height: String

              def initialize: (
                font_fallbacks: ::Array[String],
                font_family: String,
                font_size: String,
                font_weight: Float,
                letter_spacing: String,
                line_height: String
              ) -> void

              def to_hash: -> {
                font_fallbacks: ::Array[String],
                font_family: String,
                font_size: String,
                font_weight: Float,
                letter_spacing: String,
                line_height: String
              }
            end
          end

          type p_ =
            {
              font_fallbacks: ::Array[String],
              font_family: String,
              font_size: String,
              font_weight: Float,
              letter_spacing: String,
              line_height: String
            }

          class P < ContextDev::Internal::Type::BaseModel
            attr_accessor font_fallbacks: ::Array[String]

            attr_accessor font_family: String

            attr_accessor font_size: String

            attr_accessor font_weight: Float

            attr_accessor letter_spacing: String

            attr_accessor line_height: String

            def initialize: (
              font_fallbacks: ::Array[String],
              font_family: String,
              font_size: String,
              font_weight: Float,
              letter_spacing: String,
              line_height: String
            ) -> void

            def to_hash: -> {
              font_fallbacks: ::Array[String],
              font_family: String,
              font_size: String,
              font_weight: Float,
              letter_spacing: String,
              line_height: String
            }
          end
        end
      end
    end
  end
end
