module ContextDev
  module Models
    type web_web_crawl_md_response =
      {
        metadata: ContextDev::Models::WebWebCrawlMdResponse::Metadata,
        results: ::Array[ContextDev::Models::WebWebCrawlMdResponse::Result]
      }

    class WebWebCrawlMdResponse < ContextDev::Internal::Type::BaseModel
      attr_accessor metadata: ContextDev::Models::WebWebCrawlMdResponse::Metadata

      attr_accessor results: ::Array[ContextDev::Models::WebWebCrawlMdResponse::Result]

      def initialize: (
        metadata: ContextDev::Models::WebWebCrawlMdResponse::Metadata,
        results: ::Array[ContextDev::Models::WebWebCrawlMdResponse::Result]
      ) -> void

      def to_hash: -> {
        metadata: ContextDev::Models::WebWebCrawlMdResponse::Metadata,
        results: ::Array[ContextDev::Models::WebWebCrawlMdResponse::Result]
      }

      type metadata =
        {
          max_crawl_depth: Integer,
          num_failed: Integer,
          num_succeeded: Integer,
          num_urls: Integer
        }

      class Metadata < ContextDev::Internal::Type::BaseModel
        attr_accessor max_crawl_depth: Integer

        attr_accessor num_failed: Integer

        attr_accessor num_succeeded: Integer

        attr_accessor num_urls: Integer

        def initialize: (
          max_crawl_depth: Integer,
          num_failed: Integer,
          num_succeeded: Integer,
          num_urls: Integer
        ) -> void

        def to_hash: -> {
          max_crawl_depth: Integer,
          num_failed: Integer,
          num_succeeded: Integer,
          num_urls: Integer
        }
      end

      type result =
        {
          markdown: String,
          metadata: ContextDev::Models::WebWebCrawlMdResponse::Result::Metadata
        }

      class Result < ContextDev::Internal::Type::BaseModel
        attr_accessor markdown: String

        attr_accessor metadata: ContextDev::Models::WebWebCrawlMdResponse::Result::Metadata

        def initialize: (
          markdown: String,
          metadata: ContextDev::Models::WebWebCrawlMdResponse::Result::Metadata
        ) -> void

        def to_hash: -> {
          markdown: String,
          metadata: ContextDev::Models::WebWebCrawlMdResponse::Result::Metadata
        }

        type metadata =
          {
            crawl_depth: Integer,
            status_code: Integer,
            success: bool,
            title: String,
            url: String
          }

        class Metadata < ContextDev::Internal::Type::BaseModel
          attr_accessor crawl_depth: Integer

          attr_accessor status_code: Integer

          attr_accessor success: bool

          attr_accessor title: String

          attr_accessor url: String

          def initialize: (
            crawl_depth: Integer,
            status_code: Integer,
            success: bool,
            title: String,
            url: String
          ) -> void

          def to_hash: -> {
            crawl_depth: Integer,
            status_code: Integer,
            success: bool,
            title: String,
            url: String
          }
        end
      end
    end
  end
end
