module ContextDev
  module Models
    type web_web_scrape_html_params =
      { url: String, max_age_ms: Integer }
      & ContextDev::Internal::Type::request_parameters

    class WebWebScrapeHTMLParams < ContextDev::Internal::Type::BaseModel
      extend ContextDev::Internal::Type::RequestParameters::Converter
      include ContextDev::Internal::Type::RequestParameters

      attr_accessor url: String

      attr_reader max_age_ms: Integer?

      def max_age_ms=: (Integer) -> Integer

      def initialize: (
        url: String,
        ?max_age_ms: Integer,
        ?request_options: ContextDev::request_opts
      ) -> void

      def to_hash: -> {
        url: String,
        max_age_ms: Integer,
        request_options: ContextDev::RequestOptions
      }
    end
  end
end
