module ContextDev
  module Models
    type web_web_scrape_html_response =
      {
        html: String,
        success: ContextDev::Models::WebWebScrapeHTMLResponse::success,
        type: ContextDev::Models::WebWebScrapeHTMLResponse::type_,
        url: String,
        key_metadata: ContextDev::Models::WebWebScrapeHTMLResponse::KeyMetadata
      }

    class WebWebScrapeHTMLResponse < ContextDev::Internal::Type::BaseModel
      attr_accessor html: String

      attr_accessor success: ContextDev::Models::WebWebScrapeHTMLResponse::success

      attr_accessor type: ContextDev::Models::WebWebScrapeHTMLResponse::type_

      attr_accessor url: String

      attr_reader key_metadata: ContextDev::Models::WebWebScrapeHTMLResponse::KeyMetadata?

      def key_metadata=: (
        ContextDev::Models::WebWebScrapeHTMLResponse::KeyMetadata
      ) -> ContextDev::Models::WebWebScrapeHTMLResponse::KeyMetadata

      def initialize: (
        html: String,
        success: ContextDev::Models::WebWebScrapeHTMLResponse::success,
        type: ContextDev::Models::WebWebScrapeHTMLResponse::type_,
        url: String,
        ?key_metadata: ContextDev::Models::WebWebScrapeHTMLResponse::KeyMetadata
      ) -> void

      def to_hash: -> {
        html: String,
        success: ContextDev::Models::WebWebScrapeHTMLResponse::success,
        type: ContextDev::Models::WebWebScrapeHTMLResponse::type_,
        url: String,
        key_metadata: ContextDev::Models::WebWebScrapeHTMLResponse::KeyMetadata
      }

      type success = true

      module Success
        extend ContextDev::Internal::Type::Enum

        TRUE: true

        def self?.values: -> ::Array[ContextDev::Models::WebWebScrapeHTMLResponse::success]
      end

      type type_ = :html | :xml | :json | :text | :csv | :markdown | :svg | :pdf

      module Type
        extend ContextDev::Internal::Type::Enum

        HTML: :html
        XML: :xml
        JSON: :json
        TEXT: :text
        CSV: :csv
        MARKDOWN: :markdown
        SVG: :svg
        PDF: :pdf

        def self?.values: -> ::Array[ContextDev::Models::WebWebScrapeHTMLResponse::type_]
      end

      type key_metadata =
        { credits_consumed: Integer, credits_remaining: Integer }

      class KeyMetadata < ContextDev::Internal::Type::BaseModel
        attr_accessor credits_consumed: Integer

        attr_accessor credits_remaining: Integer

        def initialize: (
          credits_consumed: Integer,
          credits_remaining: Integer
        ) -> void

        def to_hash: -> {
          credits_consumed: Integer,
          credits_remaining: Integer
        }
      end
    end
  end
end
