module ContextDev
  module Models
    module Webhooks
      type delivery_retry_response =
        {
          key_metadata: ContextDev::Models::Webhooks::DeliveryRetryResponse::KeyMetadata
        }

      class DeliveryRetryResponse < ContextDev::Models::Webhooks::Delivery
        def key_metadata: -> ContextDev::Models::Webhooks::DeliveryRetryResponse::KeyMetadata?

        def key_metadata=: (
          ContextDev::Models::Webhooks::DeliveryRetryResponse::KeyMetadata _
        ) -> ContextDev::Models::Webhooks::DeliveryRetryResponse::KeyMetadata

        def initialize: (
          ?key_metadata: ContextDev::Models::Webhooks::DeliveryRetryResponse::KeyMetadata
        ) -> void

        def to_hash: -> {
          key_metadata: ContextDev::Models::Webhooks::DeliveryRetryResponse::KeyMetadata
        }

        type key_metadata =
          { credits_consumed: Integer, credits_remaining: Integer }

        class KeyMetadata < ContextDev::Internal::Type::BaseModel
          attr_accessor credits_consumed: Integer

          attr_accessor credits_remaining: Integer

          def initialize: (
            credits_consumed: Integer,
            credits_remaining: Integer
          ) -> void

          def to_hash: -> {
            credits_consumed: Integer,
            credits_remaining: Integer
          }
        end
      end
    end
  end
end
