module ContextDev
  module Models
    module Webhooks
      type delivery_list_attempts_response =
        {
          data: ::Array[ContextDev::Webhooks::Attempt],
          has_more: bool,
          next_cursor: String?,
          request_id: String,
          key_metadata: ContextDev::Models::Webhooks::DeliveryListAttemptsResponse::KeyMetadata
        }

      class DeliveryListAttemptsResponse < ContextDev::Internal::Type::BaseModel
        attr_accessor data: ::Array[ContextDev::Webhooks::Attempt]

        attr_accessor has_more: bool

        attr_accessor next_cursor: String?

        attr_accessor request_id: String

        attr_reader key_metadata: ContextDev::Models::Webhooks::DeliveryListAttemptsResponse::KeyMetadata?

        def key_metadata=: (
          ContextDev::Models::Webhooks::DeliveryListAttemptsResponse::KeyMetadata
        ) -> ContextDev::Models::Webhooks::DeliveryListAttemptsResponse::KeyMetadata

        def initialize: (
          data: ::Array[ContextDev::Webhooks::Attempt],
          has_more: bool,
          next_cursor: String?,
          request_id: String,
          ?key_metadata: ContextDev::Models::Webhooks::DeliveryListAttemptsResponse::KeyMetadata
        ) -> void

        def to_hash: -> {
          data: ::Array[ContextDev::Webhooks::Attempt],
          has_more: bool,
          next_cursor: String?,
          request_id: String,
          key_metadata: ContextDev::Models::Webhooks::DeliveryListAttemptsResponse::KeyMetadata
        }

        type key_metadata =
          { credits_consumed: Integer, credits_remaining: Integer }

        class KeyMetadata < ContextDev::Internal::Type::BaseModel
          attr_accessor credits_consumed: Integer

          attr_accessor credits_remaining: Integer

          def initialize: (
            credits_consumed: Integer,
            credits_remaining: Integer
          ) -> void

          def to_hash: -> {
            credits_consumed: Integer,
            credits_remaining: Integer
          }
        end
      end
    end
  end
end
