module ContextDev
  module Models
    module Webhooks
      type delivery_list_params =
        {
          batch_id: String,
          cursor: String,
          limit: Integer,
          monitor_id: String,
          run_id: String,
          status: ContextDev::Models::Webhooks::DeliveryListParams::status,
          tags: ::Array[String]
        }
        & ContextDev::Internal::Type::request_parameters

      class DeliveryListParams < ContextDev::Internal::Type::BaseModel
        extend ContextDev::Internal::Type::RequestParameters::Converter
        include ContextDev::Internal::Type::RequestParameters

        attr_reader batch_id: String?

        def batch_id=: (String) -> String

        attr_reader cursor: String?

        def cursor=: (String) -> String

        attr_reader limit: Integer?

        def limit=: (Integer) -> Integer

        attr_reader monitor_id: String?

        def monitor_id=: (String) -> String

        attr_reader run_id: String?

        def run_id=: (String) -> String

        attr_reader status: ContextDev::Models::Webhooks::DeliveryListParams::status?

        def status=: (
          ContextDev::Models::Webhooks::DeliveryListParams::status
        ) -> ContextDev::Models::Webhooks::DeliveryListParams::status

        attr_reader tags: ::Array[String]?

        def tags=: (::Array[String]) -> ::Array[String]

        def initialize: (
          ?batch_id: String,
          ?cursor: String,
          ?limit: Integer,
          ?monitor_id: String,
          ?run_id: String,
          ?status: ContextDev::Models::Webhooks::DeliveryListParams::status,
          ?tags: ::Array[String],
          ?request_options: ContextDev::request_opts
        ) -> void

        def to_hash: -> {
          batch_id: String,
          cursor: String,
          limit: Integer,
          monitor_id: String,
          run_id: String,
          status: ContextDev::Models::Webhooks::DeliveryListParams::status,
          tags: ::Array[String],
          request_options: ContextDev::RequestOptions
        }

        type status =
          :pending | :delivering | :retrying | :delivered | :failed | :cancelled

        module Status
          extend ContextDev::Internal::Type::Enum

          PENDING: :pending
          DELIVERING: :delivering
          RETRYING: :retrying
          DELIVERED: :delivered
          FAILED: :failed
          CANCELLED: :cancelled

          def self?.values: -> ::Array[ContextDev::Models::Webhooks::DeliveryListParams::status]
        end
      end
    end
  end
end
