module ContextDev
  module Models
    module Webhooks
      type delivery_retrieve_params =
        { delivery_id: String, tags: ::Array[String] }
        & ContextDev::Internal::Type::request_parameters

      class DeliveryRetrieveParams < ContextDev::Internal::Type::BaseModel
        extend ContextDev::Internal::Type::RequestParameters::Converter
        include ContextDev::Internal::Type::RequestParameters

        attr_accessor delivery_id: String

        attr_reader tags: ::Array[String]?

        def tags=: (::Array[String]) -> ::Array[String]

        def initialize: (
          delivery_id: String,
          ?tags: ::Array[String],
          ?request_options: ContextDev::request_opts
        ) -> void

        def to_hash: -> {
          delivery_id: String,
          tags: ::Array[String],
          request_options: ContextDev::RequestOptions
        }
      end
    end
  end
end
