module ContextDev
  module Resources
    class Webhooks
      class Deliveries
        def retrieve: (
          String delivery_id,
          ?tags: ::Array[String],
          ?request_options: ContextDev::request_opts
        ) -> ContextDev::Models::Webhooks::DeliveryRetrieveResponse

        def list: (
          body: ContextDev::Models::Webhooks::DeliveryListParams::body,
          ?request_options: ContextDev::request_opts
        ) -> ContextDev::Models::Webhooks::DeliveryListResponse

        def list_attempts: (
          String delivery_id,
          ?cursor: String,
          ?limit: Integer,
          ?tags: ::Array[String],
          ?request_options: ContextDev::request_opts
        ) -> ContextDev::Models::Webhooks::DeliveryListAttemptsResponse

        def retry_: (
          String delivery_id,
          ?force: bool,
          ?tags: ::Array[String],
          ?idempotency_key: String,
          ?request_options: ContextDev::request_opts
        ) -> ContextDev::Models::Webhooks::DeliveryRetryResponse

        def initialize: (client: ContextDev::Client) -> void
      end
    end
  end
end
